-- Schema-only snapshot of local MySQL 5.7.44, 2026-09-28; disposable manual_order_test only. No application data.
CREATE TABLE `contract_order` (
  `quantity_unit_type` varchar(16) DEFAULT NULL,
  `spec_version` bigint DEFAULT NULL,
  `min_order_quantity` decimal(32,16) DEFAULT NULL,
  `quantity_step` decimal(32,16) DEFAULT NULL,
  `min_order_notional` decimal(32,16) DEFAULT NULL,
  `quantity_asset` varchar(16) DEFAULT NULL,

  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `close_time` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  `current_price` decimal(32,16) DEFAULT NULL,
  `fee` decimal(32,16) DEFAULT NULL,
  `margin` decimal(32,16) DEFAULT NULL,
  `open_price` decimal(32,16) DEFAULT NULL,
  `open_time` datetime(6) DEFAULT NULL,
  `price` decimal(32,16) DEFAULT NULL,
  `profit` decimal(32,16) DEFAULT NULL,
  `quantity` decimal(32,16) NOT NULL,
  `side` varchar(10) NOT NULL,
  `status` varchar(20) NOT NULL,
  `stop_loss` decimal(32,16) DEFAULT NULL,
  `symbol` varchar(32) NOT NULL,
  `take_profit` decimal(32,16) DEFAULT NULL,
  `type` varchar(10) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `user_id` bigint(20) NOT NULL,
  `close_price` decimal(32,16) DEFAULT NULL,
  `leverage` decimal(10,2) DEFAULT NULL,
  `limit_match_enabled` bit(1) NOT NULL,
  `lot_size` decimal(32,16) DEFAULT NULL,
  `fx_base_currency` varchar(3) DEFAULT NULL,
  `row_version` bigint(20) NOT NULL,
  `margin_conversion_rate` decimal(32,16) DEFAULT NULL,
  `quote_currency` varchar(16) DEFAULT NULL,
  `quote_source` varchar(16) DEFAULT NULL,
  `settlement_conversion_rate` decimal(32,16) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4;
CREATE TABLE `asset_account` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) NOT NULL,
  `coin` varchar(16) NOT NULL,
  `available` decimal(32,16) NOT NULL DEFAULT '0.0000000000000000',
  `frozen` decimal(32,16) NOT NULL DEFAULT '0.0000000000000000',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `row_version` bigint(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_coin` (`user_id`,`coin`),
  UNIQUE KEY `uk_asset_user_coin` (`user_id`,`coin`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COMMENT='??????';
CREATE TABLE `user_account` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `email` varchar(128) NOT NULL,
  `country_code` varchar(32) DEFAULT NULL,
  `phone` varchar(32) DEFAULT NULL,
  `password_hash` varchar(128) NOT NULL,
  `nickname` varchar(50) DEFAULT NULL,
  `invite_code` varchar(32) DEFAULT NULL,
  `my_invite_code` varchar(32) DEFAULT NULL COMMENT '????????????????',
  `parent_user_id` bigint(20) DEFAULT NULL COMMENT '????ID',
  `status` varchar(20) NOT NULL DEFAULT 'normal',
  `user_type` varchar(20) DEFAULT 'normal' COMMENT '?????normal-????, agent-??',
  `kyc_level` int(11) DEFAULT '0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `kyc_status` varchar(20) DEFAULT NULL,
  `last_login_at` datetime(6) DEFAULT NULL,
  `last_login_ip` varchar(64) DEFAULT NULL,
  `last_login_region` varchar(128) DEFAULT NULL,
  `last_login_domain` varchar(255) DEFAULT NULL,
  `current_token` varchar(128) DEFAULT NULL COMMENT '???????token???????????',
  `remark` varchar(500) DEFAULT NULL COMMENT '??????????',
  `last_activity_at` datetime(6) DEFAULT NULL,
  `row_version` bigint(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`),
  UNIQUE KEY `phone` (`phone`),
  UNIQUE KEY `my_invite_code` (`my_invite_code`),
  KEY `idx_parent_user_id` (`parent_user_id`),
  KEY `idx_user_type` (`user_type`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4;
CREATE TABLE `trading_symbol` (
  `quantity_unit_type` varchar(16) DEFAULT NULL,
  `spec_version` bigint DEFAULT NULL,
  `min_order_quantity` decimal(32,16) DEFAULT NULL,
  `quantity_step` decimal(32,16) DEFAULT NULL,
  `min_order_notional` decimal(32,16) DEFAULT NULL,

  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `symbol` varchar(32) NOT NULL COMMENT '??????? BTCUSD, XAUUSD',
  `base_currency` varchar(16) NOT NULL COMMENT '?????? BTC, XAU',
  `quote_currency` varchar(16) NOT NULL DEFAULT 'USD' COMMENT '?????? USD',
  `name` varchar(64) NOT NULL COMMENT '?????? ???/??',
  `name_en` varchar(64) DEFAULT NULL COMMENT '????',
  `category` varchar(32) NOT NULL DEFAULT 'US' COMMENT '???US, Crypto, Metal, Forex, CFD',
  `icon_url` varchar(255) DEFAULT NULL COMMENT '??URL',
  `flag_url` varchar(255) DEFAULT NULL COMMENT '????URL',
  `is_hot` tinyint(4) NOT NULL DEFAULT '0' COMMENT '?????0? 1?',
  `is_enabled` tinyint(4) NOT NULL DEFAULT '1' COMMENT '?????0? 1?',
  `sort_order` int(11) NOT NULL DEFAULT '0' COMMENT '????????????',
  `price_precision` int(11) NOT NULL DEFAULT '2' COMMENT '??????????',
  `volume_precision` int(11) NOT NULL DEFAULT '2' COMMENT '??????????',
  `min_trade_amount` decimal(32,16) DEFAULT '0.0000000000000000' COMMENT '??????',
  `alltick_symbol` varchar(64) DEFAULT NULL COMMENT 'Alltick API??symbol???????',
  `current_price` decimal(32,16) DEFAULT '0.0000000000000000' COMMENT '????????',
  `price_change_24h` decimal(32,16) DEFAULT '0.0000000000000000' COMMENT '24?????',
  `price_change_pct_24h` decimal(10,4) DEFAULT '0.0000' COMMENT '24??????????',
  `sparkline_data` text COMMENT 'K????JSON??????????',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `fee_multiplier` decimal(32,16) DEFAULT NULL,
  `lot_size` decimal(32,16) DEFAULT NULL,
  `fx_base_currency` varchar(3) DEFAULT NULL,
  `control_enabled` bit(1) NOT NULL,
  `control_price_offset` decimal(32,16) DEFAULT NULL,
  `leverage` decimal(10,2) DEFAULT NULL,
  `control_completed_at` bigint(20) DEFAULT NULL,
  `control_duration_seconds` int(11) DEFAULT NULL,
  `control_intensity` int(11) DEFAULT NULL,
  `control_random_oscillation` bit(1) DEFAULT NULL,
  `control_restoring` bit(1) DEFAULT NULL,
  `control_start_price` decimal(32,16) DEFAULT NULL,
  `control_started_at` bigint(20) DEFAULT NULL,
  `control_target_price` decimal(32,16) DEFAULT NULL,
  `max_leverage` decimal(10,2) DEFAULT NULL,
  `row_version` bigint(20) NOT NULL DEFAULT '0',
  `random_market_base_price` decimal(32,16) DEFAULT NULL,
  `random_market_enabled` bit(1) DEFAULT NULL,
  `random_market_started_at` bigint(20) DEFAULT NULL,
  `random_market_controls` longtext,
  `market_instrument_key` varchar(128) DEFAULT NULL,
  `market_source` varchar(16) NOT NULL,
  `source_category` varchar(32) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_symbol` (`symbol`),
  UNIQUE KEY `UK_s7aam1xh6nnv6ghru10f6vnuh` (`market_instrument_key`),
  KEY `idx_category` (`category`),
  KEY `idx_is_hot` (`is_hot`),
  KEY `idx_is_enabled` (`is_enabled`),
  KEY `idx_sort_order` (`sort_order`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COMMENT='???/???';
CREATE TABLE `option_order` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `amount` decimal(32,16) NOT NULL,
  `close_price` decimal(32,16) DEFAULT NULL,
  `close_time` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  `direction` varchar(10) NOT NULL,
  `duration` int(11) DEFAULT NULL,
  `profit_rate` decimal(5,4) DEFAULT NULL COMMENT '????????',
  `loss_rate` decimal(5,4) DEFAULT NULL COMMENT '????????',
  `open_price` decimal(32,16) DEFAULT NULL,
  `open_time` datetime(6) DEFAULT NULL,
  `profit` decimal(32,16) DEFAULT NULL,
  `status` varchar(20) NOT NULL,
  `symbol` varchar(32) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `user_id` bigint(20) NOT NULL,
  `preset_profit_type` varchar(10) DEFAULT NULL,
  `row_version` bigint(20) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `loan_record` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `actual_repayment_at` datetime(6) DEFAULT NULL,
  `amount` decimal(32,16) NOT NULL,
  `approved_at` datetime(6) DEFAULT NULL,
  `contract_signed` bit(1) NOT NULL,
  `created_at` datetime(6) NOT NULL,
  `daily_rate` decimal(8,6) NOT NULL,
  `days` int(11) NOT NULL,
  `free_days` int(11) NOT NULL,
  `overdue_fee` decimal(32,16) DEFAULT NULL,
  `overdue_rate` decimal(8,6) DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  `repayment_amount` decimal(32,16) NOT NULL,
  `repayment_date` datetime(6) DEFAULT NULL,
  `signature_image` varchar(500) DEFAULT NULL,
  `status` varchar(20) NOT NULL,
  `total_interest` decimal(32,16) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `user_id` bigint(20) NOT NULL,
  `address` varchar(500) DEFAULT NULL,
  `id_number` varchar(50) DEFAULT NULL,
  `phone` varchar(32) DEFAULT NULL,
  `real_name` varchar(100) DEFAULT NULL,
  `row_version` bigint(20) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4;
CREATE TABLE `financial_yield_record` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `cumulative_yield` decimal(32,16) NOT NULL,
  `daily_yield` decimal(32,16) NOT NULL,
  `order_id` bigint(20) NOT NULL,
  `paid_at` datetime(6) DEFAULT NULL,
  `product_id` bigint(20) NOT NULL,
  `product_name` varchar(100) NOT NULL,
  `status` varchar(20) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `user_id` bigint(20) NOT NULL,
  `yield_date` date NOT NULL,
  `row_version` bigint(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK9dll9ic2smexlc46rjowsrvdy` (`order_id`,`yield_date`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4;
CREATE TABLE `system_config` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `config_key` varchar(100) NOT NULL,
  `config_value` text,
  `created_at` datetime(6) NOT NULL,
  `description` varchar(200) DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_npsxm1erd0lbetjn5d3ayrsof` (`config_key`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4;
CREATE TABLE `asset_snapshot` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `captured_at` bigint(20) NOT NULL,
  `total` decimal(32,16) NOT NULL,
  `user_id` bigint(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_snapshot_user_time` (`user_id`,`captured_at`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1;
