<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import request from '@/utils/request'
import { can } from '@/utils/access'
import ProtectedElementImage from '@/components/ProtectedElementImage.vue'

type Row = Record<string, any>
const api = '/admin/insights/traders'
const rows = ref<Row[]>([]), total = ref(0), page = ref(1), environment = ref('REAL')
const loading = ref(false), busy = ref(false), q = ref(''), status = ref(''), sort = ref('RECOMMENDED'), currency = ref(''), sourceType = ref('')
const opened = ref(false), editing = ref<Row | null>(null), tags = ref(''), reason = ref(''), active = ref('profile'), period = ref('ALL')
const equity = ref<Row>({ content: [] }), history = ref<Row>({ content: [] }), equityPage = ref(1), historyPage = ref(1)
const childOpen = ref(false), childKind = ref('equity'), childId = ref<string | null>(null), childData = ref<Row>({})
const importOpen = ref(false), importText = ref(''), importKind = ref('equity'), importReason = ref(''), importErrors = ref<Row[]>([])
const previewOpen = ref(false), preview = ref<Row | null>(null), auditOpen = ref(false), audits = ref<Row[]>([]), auditPage = ref(0)
const labels: Row = { DRAFT: '草稿', PUBLISHED: '已发布', OFFLINE: '已下架', DISABLED: '已禁用', ADMIN_CURATED: '人工维护', DEMO: '演示', NONE: '无曲线', INSUFFICIENT: '数据不足', ZERO_BASE: '零基数，不计算收益', GAPPED: '曲线有缺点，不连接缺口', AVAILABLE: '已有人工曲线' }
const profileFields = [{ key: 'name', label: '名称', max: 80 }, { key: 'bio', label: '简介', max: 2000 }, { key: 'sourceNote', label: '来源说明', max: 1000 }, { key: 'metricBasisNote', label: '指标口径（人工维护）', max: 1000 }, { key: 'riskNote', label: '收益与风险说明', max: 1000 }, { key: 'authorizationNote', label: '内部展示授权记录（不公开）', max: 1000 }]
const pointFields = [{ key: 'pointAt', label: '曲线时间 UTC（ISO-8601）' }, { key: 'netAsset', label: '净资产（必填十进制）' }, { key: 'cashFlow', label: '该点入出金（未知留空）' }, { key: 'currency', label: '曲线币种（与人物一致）' }, { key: 'sourceNote', label: '曲线来源说明' }]
const historyFields = [{ key: 'recordKey', label: '人工条目编号（非私有订单号）' }, { key: 'closedAt', label: '平仓时间 UTC（ISO-8601）' }, { key: 'symbol', label: '品种代码' }, { key: 'leverage', label: '杠杆（未知留空）' }, { key: 'quantity', label: '数量（未知留空）' }, { key: 'quantityUnit', label: '数量单位（如 BTC / CONTRACT）' }, { key: 'pnl', label: '盈亏（未知留空）' }, { key: 'fees', label: '费用（未知留空）' }, { key: 'currency', label: '历史币种（与人物一致）' }, { key: 'sourceNote', label: '历史来源说明' }, { key: 'evidenceNote', label: '内部证据记录（不公开、不构成核验）' }]
function fail(e: any) { ElMessage.error(e.response?.data?.message || e.message || '请求失败'); if (e.response?.data?.errors) importErrors.value = e.response.data.errors }
async function load(reset = false) {
  if (reset) page.value = 1
  loading.value = true
  try { const r: any = await request.get(api, { params: { q: q.value || undefined, currency: currency.value || undefined, sourceType: sourceType.value || undefined, status: status.value || undefined, sort: sort.value, page: page.value - 1, size: 20 } }); rows.value = r.content; total.value = r.totalElements; environment.value = r.environment } catch (e) { fail(e) } finally { loading.value = false }
}
function fresh() {
  const end = new Date(); end.setUTCSeconds(0, 0)
  return { data: { name: '', avatarUrl: null, bio: '', strategyTags: [], statisticStart: new Date(end.getTime() - 30 * 86400000).toISOString(), statisticEnd: end.toISOString(), currency: 'USD', sourceType: environment.value === 'DEMO' ? 'DEMO' : 'ADMIN_CURATED', pointIntervalHours: 24, sourceNote: '', metricBasisNote: '', riskNote: '', authorizationNote: '', manualRoi: null, manualWinRate: null, manualMaxDrawdown: null } }
}
async function open(row?: Row) { try { editing.value = row ? await request.get(`${api}/${row.traderId}`) as any : fresh(); tags.value = editing.value!.data.strategyTags.join(', '); reason.value = ''; active.value = 'profile'; opened.value = true; equityPage.value = historyPage.value = 1; period.value = 'ALL'; if (row) await loadChildren() } catch (e) { fail(e) } }
async function loadChildren() {
  if (!editing.value?.traderId) return
  try { const id = editing.value.traderId; const result = await Promise.all([request.get(`${api}/${id}/equity`, { params: { period: period.value, page: equityPage.value - 1, size: 100 } }), request.get(`${api}/${id}/history`, { params: { period: period.value, page: historyPage.value - 1, size: 20 } })]); equity.value = result[0] as any; history.value = result[1] as any } catch (e) { fail(e) }
}
async function updateProfile(result?: Row) { if (!editing.value?.traderId && result) editing.value = result; else editing.value = result || await request.get(`${api}/${editing.value!.traderId}`) as any; tags.value = editing.value!.data.strategyTags.join(', '); await loadChildren(); await load() }
async function save() {
  if (!can('traders:edit') || busy.value || !editing.value || !reason.value.trim()) return
  busy.value = true
  try { const d = { ...editing.value!.data, strategyTags: tags.value.split(/[,，]/).map(s => s.trim()).filter(Boolean) }; const body = { rowVersion: editing.value!.rowVersion, reason: reason.value, data: d }; const result: any = editing.value!.traderId ? await request.put(`${api}/${editing.value!.traderId}`, body) : await request.post(api, body); await updateProfile(result); ElMessage.success('资料已保存；修改已发布内容会回到草稿，需重新发布') } catch (e) { fail(e) } finally { busy.value = false }
}
async function change(path: string, fields: Row) {
  const action = ({ publication: 'publish', disable: 'disable', recommendation: 'sort' } as Record<string, string>)[path]
  if (!action || !can(`traders:${action}`) || busy.value || !editing.value?.traderId || !reason.value.trim()) return
  busy.value = true
  try { const result: any = await request.put(`${api}/${editing.value!.traderId}/${path}`, { rowVersion: editing.value!.rowVersion, reason: reason.value, ...fields }); await updateProfile(result); ElMessage.success('状态 / 推荐已保存，公开读取立即生效') } catch (e) { fail(e) } finally { busy.value = false }
}
async function upload(event: Event) {
  if (!can('traders:edit') || busy.value || !editing.value) return
  const file = (event.target as HTMLInputElement).files?.[0]; if (!file) return
  busy.value = true
  try { const data = new FormData(); data.append('file', file); const result: any = await request.post('/upload/image', data); if (!result.success) throw new Error(result.message || '上传失败'); editing.value!.data.avatarUrl = result.url; ElMessage.success('头像已上传，保存资料后生效') } catch (e) { fail(e) } finally { busy.value = false; (event.target as HTMLInputElement).value = '' }
}
const canChild = (kind: string) => ['equity', 'history'].includes(kind) && can(`traders:${kind}`)
function child(kind: string, row?: Row) {
  if (!canChild(kind) || busy.value || !editing.value?.traderId) return
  childKind.value = kind; childId.value = row ? row[kind === 'equity' ? 'pointId' : 'recordId'] : null
  const fields = kind === 'equity' ? pointFields : historyFields
  childData.value = Object.fromEntries(fields.map(f => [f.key, row?.[f.key] ?? (f.key === 'currency' ? editing.value!.data.currency : '')]))
  if (kind === 'history') { childData.value.direction = row?.direction || 'LONG'; childData.value.pnlBasis = row?.pnlBasis || 'NOT_PROVIDED' }
  childOpen.value = true
}
async function saveChild() {
  if (!canChild(childKind.value) || busy.value || !editing.value?.traderId || !reason.value.trim()) return
  busy.value = true
  try { const data = Object.fromEntries(Object.entries(childData.value).map(([k, v]) => [k, v === '' ? null : v])); const path = `${api}/${editing.value!.traderId}/${childKind.value}${childId.value ? `/${childId.value}` : ''}`; const body = { rowVersion: editing.value!.rowVersion, reason: reason.value, data }; if (childId.value) await request.put(path, body); else await request.post(path, body); childOpen.value = false; await updateProfile(); ElMessage.success('子记录已保存；已发布人物回草稿') } catch (e) { fail(e) } finally { busy.value = false }
}
async function remove(kind: string, row: Row) {
  if (!canChild(kind) || busy.value || !editing.value?.traderId || !reason.value.trim()) return
  try { await ElMessageBox.confirm('仅删除本人工展示子记录；已发布人物会回到草稿，不影响用户订单或资金。', '确认删除展示记录', { type: 'warning' }); if (!canChild(kind)) return; busy.value = true; const id = row[kind === 'equity' ? 'pointId' : 'recordId']; const result: any = await request.delete(`${api}/${editing.value!.traderId}/${kind}/${id}`, { data: { rowVersion: editing.value!.rowVersion, reason: reason.value } }); await updateProfile(result); ElMessage.success('人工记录已删除') } catch (e) { if (e !== 'cancel' && e !== 'close') fail(e) } finally { busy.value = false }
}
async function template(kind: string) {
  if (!canChild(kind) || !editing.value?.traderId) return
  try { const result: any = await request.get(`${api}/${editing.value!.traderId}/import-template`, { params: { kind } }); const blob = new Blob([JSON.stringify({ rowVersion: result.rowVersion, reason: '', rows: result.rows }, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `trader-${kind}-template.json`; a.click(); URL.revokeObjectURL(url) } catch (e) { fail(e) }
}
function openImport(kind: string) { if (!canChild(kind) || busy.value || !editing.value?.traderId) return; importKind.value = kind; importText.value = ''; importReason.value = ''; importErrors.value = []; importOpen.value = true }
async function readImport(event: Event) { if (!canChild(importKind.value)) return; const file = (event.target as HTMLInputElement).files?.[0]; if (!file) return; if (file.size > 3000000) { ElMessage.error('JSON 文件最多3MB'); return } importText.value = await file.text() }
async function importRows() {
  if (!canChild(importKind.value) || busy.value || !editing.value?.traderId || !importReason.value.trim()) return
  busy.value = true; importErrors.value = []
  try { const parsed = JSON.parse(importText.value); const body = { rowVersion: parsed.rowVersion ?? editing.value!.rowVersion, reason: importReason.value, rows: parsed.rows }; const result: any = await request.post(`${api}/${editing.value!.traderId}/${importKind.value}/import`, body, { timeout: 60000 }); await updateProfile(result.profile); importOpen.value = false; ElMessage.success(`整批新增 ${result.inserted} 条；人物需重新预览发布`) } catch (e) { fail(e) } finally { busy.value = false }
}
async function showPreview() { try { preview.value = await request.get(`${api}/${editing.value!.traderId}/preview`) as any; previewOpen.value = true } catch (e) { fail(e) } }
async function showAudit(reset = false) { if (reset) auditPage.value = 0; try { audits.value = await request.get(`${api}/audit`, { params: { page: auditPage.value } }) as any; auditOpen.value = true } catch (e) { fail(e) } }
const plot = computed(() => {
  const points: Row[] = equity.value.content; if (points.length < 2) return []
  const values = points.map(p => Number(p.netAsset)), min = Math.min(...values), max = Math.max(...values), span = max - min || 1
  const times = points.map(p => Date.parse(p.pointAt)), timeSpan = times[times.length - 1]! - times[0]! || 1
  return points.map((p, i) => `${i === 0 || points[i - 1]?.gapAfter ? 'M' : 'L'} ${(times[i]! - times[0]!) / timeSpan * 560 + 20} ${150 - (values[i]! - min) / span * 120}`).join(' ')
})
onMounted(() => load())
</script>

<template>
  <section class="trader-management" aria-label="交易员展示管理">
    <header><div><h2>交易员展示</h2><p>管理员人工维护，不是外部交易所榜单，不关联私有订单，不提供跟单。</p></div><div class="actions"><el-button v-permission="'traders:view'" @click="showAudit(true)">交易员操作审计</el-button><el-button v-permission="'traders:edit'" v-if="can('traders:edit')" type="primary" @click="open()" :disabled="busy">新增展示人物</el-button></div></header>
    <el-alert title="推荐排序不是业绩排行。人工 ROI、胜率与回撤必须说明口径；净资产涨幅不当作策略收益。当前不支持 VERIFIED_PLATFORM 或实盘核验。" type="info" :closable="false" />
    <div class="filters"><label>人物名称<input v-model="q" aria-label="人物名称筛选" maxlength="80"></label><label>状态<select v-model="status" aria-label="人物状态筛选"><option value="">全部</option><option v-for="s in ['DRAFT','PUBLISHED','OFFLINE','DISABLED']" :key="s" :value="s">{{ labels[s] }}</option></select></label><label>币种<input v-model="currency" aria-label="人物币种筛选" maxlength="12" placeholder="如 USD"></label><label>资料来源<select v-model="sourceType" aria-label="人物来源筛选"><option value="">全部</option><option value="ADMIN_CURATED">人工维护</option><option value="DEMO">演示（只限演示环境）</option></select></label><label>排序<select v-model="sort" aria-label="人物排序"><option value="RECOMMENDED">推荐排序（非业绩）</option><option value="UPDATED">更新时间</option><option value="NAME">人物名称</option></select></label><el-button v-permission="'traders:view'" :loading="loading" @click="load(true)">查询人物</el-button></div>
    <div class="scroll" v-loading="loading"><table><caption>当前租户 · {{ environment }} · {{ total }} 个人物；没有自动示例人物</caption><thead><tr><th>人物 / ID / 标签</th><th>统计期 / 来源</th><th>人工指标 / 曲线</th><th>状态 / 推荐 / 更新 UTC</th><th>操作</th></tr></thead><tbody><tr v-for="row in rows" :key="row.traderId" :data-trader="row.traderId"><td>{{ row.name }}<br><small>{{ row.traderId }}<br>{{ row.strategyTags.join(' · ') }}</small></td><td>{{ row.statisticStart }}<br>{{ row.statisticEnd }}<br>{{ row.currency }} · {{ labels[row.sourceType] }}</td><td>人工 ROI {{ row.manualRoi ?? '—' }}<span v-if="row.manualRoi !== null">%</span><br>人工胜率 {{ row.manualWinRate ?? '—' }}<br>人工最大回撤 {{ row.manualMaxDrawdown ?? '—' }}<br>{{ labels[row.curveAvailability] }}（{{ row.equityPointCount }} 点）</td><td>{{ labels[row.status] }} · {{ row.recommended ? '推荐' : '不推荐' }} · {{ row.sortOrder }}<br>{{ row.updatedAt }}<br><strong v-if="row.demo">演示，非正式业绩</strong></td><td><el-button v-permission="'traders:view'" @click="open(row)">查看 / 管理人物</el-button></td></tr><tr v-if="!rows.length && !loading"><td colspan="5">没有符合条件的人物。请管理员新增并发布获授权的展示资料，不会采集其他交易所交易员。</td></tr></tbody></table></div>
    <el-pagination v-model:current-page="page" :page-size="20" :total="total" layout="prev, pager, next, total" @current-change="load()" />
    <el-dialog v-model="opened" :title="editing?.traderId ? '人物资料与发布管理' : '新增人工展示人物'" width="min(1050px, 96vw)" :close-on-click-modal="false">
      <div v-if="editing"><p v-if="editing.traderId">{{ editing.traderId }} · {{ environment }} · {{ labels[editing.status] }} · 版本 {{ editing.rowVersion }}</p><el-alert title="资料、曲线和历史编辑会使已发布人物回到草稿；需要重新预览、发布。禁用解除后也不自动发布。" type="warning" :closable="false" />
        <label class="reason">本次操作依据<input v-model="reason" maxlength="1000" aria-label="交易员操作依据" :disabled="busy"></label>
        <el-tabs v-model="active"><el-tab-pane label="资料与发布" name="profile"><form @submit.prevent="save"><fieldset :disabled="busy || !can('traders:edit')"><div class="form-grid"><label v-for="f in profileFields" :key="f.key">{{ f.label }}<textarea v-if="f.key !== 'name'" v-model="editing.data[f.key]" :maxlength="f.max" :aria-label="f.label" rows="2" /><input v-else v-model="editing.data.name" :maxlength="f.max" aria-label="名称" required></label><label>策略标签（逗号分隔，最多10个）<input v-model="tags" aria-label="策略标签"></label><label>币种 / 曲线金额单位<input v-model="editing.data.currency" aria-label="币种 / 曲线金额单位" maxlength="12" required></label><label>统计开始 UTC（ISO-8601）<input v-model="editing.data.statisticStart" aria-label="统计开始 UTC" required></label><label>统计结束 UTC（ISO-8601）<input v-model="editing.data.statisticEnd" aria-label="统计结束 UTC" required></label><label>资料来源<select v-model="editing.data.sourceType" aria-label="资料来源"><option value="ADMIN_CURATED">ADMIN_CURATED · 人工维护</option><option v-if="environment === 'DEMO'" value="DEMO">DEMO · 演示</option></select></label><label>曲线采样间隔（小时）<input v-model.number="editing.data.pointIntervalHours" type="number" min="1" max="720" aria-label="曲线采样间隔"></label><label>人工 ROI %（未知留空）<input v-model="editing.data.manualRoi" inputmode="decimal" aria-label="人工 ROI"></label><label>人工胜率 %（未知留空）<input v-model="editing.data.manualWinRate" inputmode="decimal" aria-label="人工胜率"></label><label>人工最大回撤 %（未知留空）<input v-model="editing.data.manualMaxDrawdown" inputmode="decimal" aria-label="人工最大回撤"></label><label>上传头像（复用已有图片上传）<input type="file" accept="image/png,image/jpeg,image/gif,image/webp" aria-label="上传交易员头像" @change="upload"><ProtectedElementImage v-if="editing.data.avatarUrl" :src="editing.data.avatarUrl" alt="人工展示头像" style="width: 72px; height: 72px" /><small>{{ editing.data.avatarUrl || '未上传；公开人物使用名称占位' }}</small><el-button v-permission="'traders:edit'" v-if="editing.data.avatarUrl" type="default" @click="editing.data.avatarUrl = null">清除头像引用</el-button></label></div></fieldset><el-button v-permission="'traders:edit'" v-if="can('traders:edit')" native-type="submit" type="primary" :disabled="busy || !reason.trim()">保存人物资料</el-button></form>
          <div v-if="editing.traderId" class="publication"><el-button v-permission="'traders:view'" @click="showPreview" :disabled="busy">公开视图预览</el-button><el-button v-permission="'traders:publish'" v-if="can('traders:publish')" type="primary" :disabled="busy || !reason.trim() || editing.status === 'DISABLED'" @click="change('publication', { status: 'PUBLISHED' })">发布人物</el-button><el-button v-permission="'traders:publish'" v-if="can('traders:publish')" :disabled="busy || !reason.trim() || editing.status === 'DISABLED'" @click="change('publication', { status: 'OFFLINE' })">下架人物</el-button><el-button v-permission="'traders:disable'" v-if="can('traders:disable')" :disabled="busy || !reason.trim()" @click="change('disable', { disabled: editing.status !== 'DISABLED' })">{{ editing.status === 'DISABLED' ? '解除禁用（回草稿）' : '禁用人物' }}</el-button></div>
          <fieldset v-if="editing.traderId" :disabled="busy || !can('traders:sort')"><legend>推荐排序（不是业绩排行）</legend><label class="checkbox"><input v-model="editing.recommended" type="checkbox" aria-label="推荐人物">推荐人物</label><label>推荐权重<input v-model.number="editing.sortOrder" type="number" min="-10000" max="10000" aria-label="推荐权重"></label><el-button v-permission="'traders:sort'" v-if="can('traders:sort')" :disabled="busy || !reason.trim()" @click="change('recommendation', { recommended: editing.recommended, sortOrder: editing.sortOrder })">保存推荐排序</el-button></fieldset>
        </el-tab-pane><el-tab-pane v-if="editing.traderId" label="净资产曲线" name="equity"><div class="actions"><label>曲线 / 历史周期<select v-model="period" aria-label="曲线周期" @change="equityPage = historyPage = 1; loadChildren()"><option v-for="p in ['ALL','7D','30D','90D']" :key="p" :value="p">{{ p }}</option></select></label><el-button v-permission="'traders:equity'" v-if="can('traders:equity')" :disabled="busy" @click="child('equity')">新增曲线点</el-button><el-button v-permission="'traders:equity'" v-if="can('traders:equity')" @click="template('equity')">下载曲线 JSON 模板</el-button><el-button v-permission="'traders:equity'" v-if="can('traders:equity')" @click="openImport('equity')">批量导入曲线</el-button></div><p>{{ labels[equity.curveStatus] }} · 缺口 {{ equity.gapCount }} · {{ equity.missingBoundary ? '边界数据不完整' : '边界检查通过' }}。{{ equity.disclosure }}</p><p>本页最多100点，图表仅显示本页；完整资料请分页。未知入出金：{{ equity.unknownCashFlows ? '有' : '无' }}。精确数字以表格为准。</p><svg v-if="equity.content.length > 1" class="curve" viewBox="0 0 600 180" role="img" aria-label="人工净资产曲线（非策略收益）"><path :d="String(plot)" fill="none" stroke="#47633d" stroke-width="2" /></svg><div class="scroll"><table><thead><tr><th>时间 UTC</th><th>人工净资产 / 币种</th><th>入出金</th><th>来源 / 缺点</th><th>操作</th></tr></thead><tbody><tr v-for="p in equity.content" :key="p.pointId" :data-point="p.pointId"><td>{{ p.pointAt }}</td><td>{{ p.netAsset }} {{ p.currency }}</td><td>{{ p.cashFlow ?? '未知' }}</td><td>{{ p.sourceNote || '未提供' }}<br>{{ p.gapAfter ? '此点之后有缺口' : '' }}</td><td><div v-if="can('traders:equity')" class="actions"><el-button v-permission="'traders:equity'" @click="child('equity', p)">编辑曲线点</el-button><el-button v-permission="'traders:equity'" :disabled="busy || !reason.trim()" @click="remove('equity', p)">删除曲线点</el-button></div></td></tr><tr v-if="!equity.content.length"><td colspan="5">本周期无曲线；不生成示例点。</td></tr></tbody></table></div><el-pagination v-model:current-page="equityPage" :page-size="100" :total="equity.totalElements || 0" layout="prev, pager, next, total" @current-change="loadChildren" /></el-tab-pane>
          <el-tab-pane v-if="editing.traderId" label="历史记录·人工维护" name="history"><div class="actions"><el-button v-permission="'traders:history'" v-if="can('traders:history')" @click="child('history')">新增人工历史</el-button><el-button v-permission="'traders:history'" v-if="can('traders:history')" @click="template('history')">下载历史 JSON 模板</el-button><el-button v-permission="'traders:history'" v-if="can('traders:history')" @click="openImport('history')">批量导入历史</el-button></div><p>{{ history.disclosure }} · 当前周期 {{ period }}。内部证据不构成实盘核验。</p><div class="scroll"><table><thead><tr><th>平仓时间 UTC / 人工编号</th><th>币种 / 方向 / 杠杆</th><th>数量 / 单位</th><th>盈亏 / 费用 / 口径</th><th>操作</th></tr></thead><tbody><tr v-for="h in history.content" :key="h.recordId" :data-record="h.recordId"><td>{{ h.closedAt }}<br>{{ h.recordKey }}</td><td>{{ h.symbol }} · {{ h.direction === 'LONG' ? '多' : '空' }}<br>杠杆 {{ h.leverage ?? '未知' }}</td><td>{{ h.quantity ?? '未知' }} {{ h.quantityUnit || '' }}</td><td>{{ h.pnl ?? '未知' }} {{ h.currency }}<br>费用 {{ h.fees ?? '未知' }}<br>{{ h.pnlBasis }}</td><td><div v-if="can('traders:history')" class="actions"><el-button v-permission="'traders:history'" @click="child('history', h)">编辑人工历史</el-button><el-button v-permission="'traders:history'" :disabled="busy || !reason.trim()" @click="remove('history', h)">删除人工历史</el-button></div></td></tr><tr v-if="!history.content.length"><td colspan="5">无人工历史记录；不读取任何私有用户订单。</td></tr></tbody></table></div><el-pagination v-model:current-page="historyPage" :page-size="20" :total="history.totalElements || 0" layout="prev, pager, next, total" @current-change="loadChildren" /></el-tab-pane></el-tabs>
      </div>
    </el-dialog>
    <el-dialog v-model="childOpen" :title="childKind === 'equity' ? '人工曲线点维护' : '人工闭仓历史维护'" width="min(750px, 96vw)" :close-on-click-modal="false"><p>日期 ISO-8601 UTC；金额用十进制字符串。未知留空，不能填虚构指标。修改依据使用人物详情中的“本次操作依据”。</p><form @submit.prevent="saveChild"><fieldset :disabled="busy"><div class="form-grid"><label v-for="f in childKind === 'equity' ? pointFields : historyFields" :key="f.key">{{ f.label }}<input v-model="childData[f.key]" :aria-label="f.label" maxlength="1000"></label><template v-if="childKind === 'history'"><label>方向<select v-model="childData.direction" aria-label="历史方向"><option value="LONG">多 LONG</option><option value="SHORT">空 SHORT</option></select></label><label>盈亏费用口径<select v-model="childData.pnlBasis" aria-label="盈亏费用口径"><option value="NOT_PROVIDED">盈亏未提供</option><option value="BEFORE_FEES">扣费前</option><option value="AFTER_FEES">扣费后</option></select></label></template></div></fieldset><el-button v-permission="childKind === 'equity' ? 'traders:equity' : 'traders:history'" native-type="submit" type="primary" :disabled="busy || !reason.trim()">保存人工记录</el-button></form></el-dialog>
    <el-dialog v-model="importOpen" title="原子追加导入人工展示记录" width="min(850px, 96vw)" :close-on-click-modal="false"><p>先下载对应 JSON 模板。最多500条，每类最多10000条；同时间曲线点或同人工编号历史重复报错。币种、日期或任意一行失败整批不写，不覆盖现有数据。导入已发布人物回草稿。</p><label>选择 JSON 文件<input type="file" accept="application/json,.json" aria-label="选择交易员 JSON 文件" @change="readImport"></label><label>JSON 内容<textarea v-model="importText" rows="9" aria-label="交易员导入 JSON" /></label><label>导入依据<input v-model="importReason" maxlength="1000" aria-label="交易员导入依据"></label><ul v-if="importErrors.length" role="alert"><li v-for="e in importErrors" :key="e.row">第 {{ e.row }} 行：{{ e.message }}</li></ul><el-button v-permission="importKind === 'equity' ? 'traders:equity' : 'traders:history'" type="primary" :disabled="busy || !importText.trim() || !importReason.trim()" @click="importRows">确认整批导入</el-button></el-dialog>
    <el-dialog v-model="previewOpen" title="公开人物视图预览（非公开草稿接口）" width="min(750px, 96vw)"><div v-if="preview"><h3>{{ preview.name }}</h3><p>{{ preview.sourceType }} · {{ preview.demo ? '演示' : '人工维护' }} · {{ labels[preview.status] }} · {{ preview.publiclyVisible ? '已公开' : '当前不可公开读取' }}</p><p>{{ preview.traderId }} · {{ preview.statisticPeriodId }}</p><p>{{ preview.bio }}</p><p>{{ preview.disclosure }}</p><p>人工 ROI {{ preview.manualRoi ?? '—' }}；人工胜率 {{ preview.manualWinRate ?? '—' }}；人工回撤 {{ preview.manualMaxDrawdown ?? '—' }}。未提供数字不造数。</p><p>{{ preview.metricBasisNote }}</p><p>{{ preview.sourceNote }}</p><p>{{ preview.curveDisclosure }}</p><p>{{ preview.historyDisclosure }}</p><p>{{ preview.riskNote }}</p></div></el-dialog>
    <el-dialog v-model="auditOpen" title="交易员展示修改前后审计" width="min(950px, 96vw)"><details v-for="a in audits" :key="a.id"><summary>{{ a.capturedAt }} · {{ a.actor }} · {{ a.action }} · {{ a.reason }}</summary><p>人物 {{ a.traderId }} · 子记录 {{ a.objectId || '资料 / 批量' }}</p><h4>修改前</h4><pre>{{ a.beforeJson || '新增记录' }}</pre><h4>修改后</h4><pre>{{ a.afterJson || '已删除' }}</pre></details><p v-if="!audits.length">暂无修改审计</p><div class="actions"><el-button v-permission="'traders:view'" :disabled="auditPage === 0" @click="auditPage--; showAudit()">上一页审计</el-button><span>第 {{ auditPage + 1 }} 页</span><el-button v-permission="'traders:view'" :disabled="audits.length < 50" @click="auditPage++; showAudit()">下一页审计</el-button></div></el-dialog>
  </section>
</template>

<style scoped>
.trader-management { --el-color-primary: #47633d; --el-color-primary-light-9: #f2f5ed; --el-color-primary-dark-2: #344d2c; color: #252a30; padding: 16px; min-width: 0; border-radius: 8px; background: white; }
header, .actions, .filters, .publication { display: flex; flex-wrap: wrap; gap: 12px; align-items: center; } header { justify-content: space-between; } h2 { margin: 0; } p, small, h3, summary { overflow-wrap: anywhere; } p, small { color: #59616b; } .filters, .publication, .reason { margin: 16px 0; } label { display: grid; gap: 6px; min-width: 0; } input, select, textarea { box-sizing: border-box; width: 100%; min-height: 44px; padding: 8px; background: white; color: #252a30; border: 1px solid #d9dfd5; border-radius: 5px; font: inherit; } input[type=checkbox] { width: 22px; height: 22px; min-height: 22px; } .checkbox { display: flex; align-items: center; min-height: 44px; } input[type=file] { overflow: hidden; } .form-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 16px; } fieldset { min-width: 0; padding: 12px; margin: 16px 0; border: 1px solid #e9edef; } fieldset:disabled { opacity: .72; } .scroll { overflow-x: auto; max-width: 100%; } table { width: 100%; min-width: 900px; border-collapse: collapse; text-align: left; } caption { text-align: left; padding: 12px 0; } th, td { max-width: 310px; padding: 12px; border-bottom: 1px solid #e9edef; overflow-wrap: anywhere; vertical-align: top; } th { background: #f2f5ed; } .curve { width: 100%; max-height: 240px; background: #f2f5ed; } summary { cursor: pointer; padding: 14px 0; } pre { padding: 12px; background: #f2f5ed; white-space: pre-wrap; overflow-wrap: anywhere; max-height: 350px; overflow: auto; }
:deep(.el-button) { min-height: 44px; margin-left: 0; white-space: normal; } :deep(.el-pagination) { flex-wrap: wrap; margin-top: 16px; } :deep(.el-pagination button), :deep(.el-pager li) { min-width: 44px; min-height: 44px; } :deep(.el-dialog__body) { overflow: auto; } :deep(.el-dialog__headerbtn) { width: 44px; height: 44px; } :deep(.el-tabs__item) { min-height: 44px; } button:focus-visible, input:focus-visible, select:focus-visible, textarea:focus-visible, summary:focus-visible { outline: 2px solid #47633d; outline-offset: 3px; }
@media(max-width: 600px) { .trader-management { padding: 12px; } .form-grid { grid-template-columns: minmax(0, 1fr); } .filters label { width: 100%; } }
</style>
