package com.gtcfesk.exchange.control;
import com.fasterxml.jackson.databind.*;
import com.gtcfesk.exchange.support.SupportService;
import com.gtcfesk.exchange.tenant.TenantContext;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.*;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.test.util.ReflectionTestUtils;
import java.nio.file.*;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.mock;
/** Actual H2 JDBC transactions/files; native MySQL and deployed HTTP acceptance are separate. */
class ChatArchiveTest {
 @TempDir Path root;
 JdbcTemplate jdbc;ObjectMapper json=new ObjectMapper().findAndRegisterModules();ChatArchiveService service;OperationalIssueService issues;Audit audit;
 static class Audit extends ControlAuditService{
  final JdbcTemplate jdbc;boolean failChunk;
  Audit(JdbcTemplate jdbc){super(mock(ControlAuditLogRepository.class));this.jdbc=jdbc;}
  @Override public void record(Long actor,Long tenant,String session,String action,String object,String result,String detail,String reason){if(failChunk&&"CHAT_ARCHIVE_CHUNK".equals(action))throw new IllegalStateException("synthetic audit failure");jdbc.update("INSERT INTO control_audit_log(actor_id,tenant_id,action,object_ref,detail,created_at) VALUES(?,?,?,?,?,CURRENT_TIMESTAMP)",actor,tenant,action,object,detail);}
 }
 @BeforeEach void setup(){DriverManagerDataSource ds=new DriverManagerDataSource("jdbc:h2:mem:archive_"+UUID.randomUUID()+";MODE=MySQL;DB_CLOSE_DELAY=-1","sa","");jdbc=new JdbcTemplate(ds);jdbc.execute("CREATE TABLE tenant(id BIGINT PRIMARY KEY)");jdbc.update("INSERT INTO tenant VALUES(2),(3)");jdbc.execute("CREATE TABLE control_audit_log(id BIGINT AUTO_INCREMENT PRIMARY KEY,actor_id BIGINT,tenant_id BIGINT,action VARCHAR(128),object_ref VARCHAR(255),detail CLOB,created_at TIMESTAMP)");jdbc.execute("CREATE TABLE support_conversation(id BIGINT PRIMARY KEY,tenant_id BIGINT,user_id BIGINT,status VARCHAR(16),created_at TIMESTAMP,closed_at TIMESTAMP,legal_hold BOOLEAN,last_hash VARCHAR(64),user_read_id BIGINT DEFAULT 0,admin_read_id BIGINT DEFAULT 0)");jdbc.execute("CREATE TABLE support_message(id BIGINT PRIMARY KEY,tenant_id BIGINT,conversation_id BIGINT,sender VARCHAR(12),sender_id BIGINT,sender_name VARCHAR(128),request_id VARCHAR(64),text VARCHAR(4000),image BOOLEAN,image_hash VARCHAR(64),created_at TIMESTAMP,previous_hash VARCHAR(64),hash VARCHAR(64))");jdbc.execute("CREATE TABLE support_attachment(message_id BIGINT PRIMARY KEY,tenant_id BIGINT,content BLOB)");jdbc.execute("CREATE TABLE control_chat_archive_job(id VARCHAR(36) PRIMARY KEY,tenant_id BIGINT,conversation_id BIGINT,actor_id BIGINT,owner_key VARCHAR(64),request_key VARCHAR(36),request_hash VARCHAR(64),reason VARCHAR(512),state VARCHAR(16),end_id BIGINT,expected_messages BIGINT,processed_messages BIGINT DEFAULT 0,cursor_id BIGINT DEFAULT 0,chunk_sequence INT DEFAULT 0,attachment_bytes BIGINT DEFAULT 0,chain_hash VARCHAR(64) DEFAULT '',snapshot_sha256 VARCHAR(64),expected_last_hash VARCHAR(64),final_manifest_sha256 VARCHAR(64),failure_type VARCHAR(128),created_at TIMESTAMP,updated_at TIMESTAMP,UNIQUE(tenant_id,conversation_id,owner_key,request_key))");DataSourceTransactionManager manager=new DataSourceTransactionManager(ds);audit=new Audit(jdbc);issues=new OperationalIssueService(jdbc,audit,manager,json);ReflectionTestUtils.setField(issues,"failureDirectory",root.toString());service=new ChatArchiveService(jdbc,manager,audit,json,issues);ReflectionTestUtils.setField(service,"archiveDirectory",root.toString());control(7,false);}
 @AfterEach void clear(){SecurityContextHolder.clearContext();TenantContext.clear();}
 void control(long actor,boolean access){UsernamePasswordAuthenticationToken auth=new UsernamePasswordAuthenticationToken("control",null,List.of(new SimpleGrantedAuthority(access?"ROLE_CONTROL_ACCESS":"ROLE_CONTROL")));auth.setDetails(new ControlIdentity(actor,access?2L:null,access?"session":null));SecurityContextHolder.getContext().setAuthentication(auth);}
 void worker(){SecurityContextHolder.clearContext();TenantContext.clear();}
 long number(Map<String,Object> row,String key){return ((Number)row.get(key)).longValue();}
 byte[] png()throws Exception{java.io.ByteArrayOutputStream out=new java.io.ByteArrayOutputStream();javax.imageio.ImageIO.write(new java.awt.image.BufferedImage(1,1,java.awt.image.BufferedImage.TYPE_INT_RGB),"png",out);return out.toByteArray();}
 void seed(int count)throws Exception{String previous="";byte[] png=png();Timestamp at=Timestamp.from(Instant.parse("2024-01-01T00:00:00Z"));jdbc.update("INSERT INTO support_conversation(id,tenant_id,user_id,status,created_at,closed_at,legal_hold,last_hash) VALUES(9,2,70,'CLOSED',?,?,FALSE,'')",at,at);for(int i=1;i<=count;i++){boolean image=i%100==0;String imageHash=image?SupportService.sha256(png):"",sender=i==1?"SYSTEM":"USER";long actor=i==1?0:70;String hash=SupportService.sha256(json.writeValueAsBytes(Arrays.asList(9L,sender,actor,"fixture","message-"+i,"synthetic "+i,imageHash,at.toInstant().toString(),previous)));jdbc.update("INSERT INTO support_message VALUES(?,2,9,?,?,'fixture',?,?,?,?,?,?,?)",i,sender,actor,"message-"+i,"synthetic "+i,image,imageHash,at,previous,hash);if(image)jdbc.update("INSERT INTO support_attachment VALUES(?,2,?)",i,png);previous=hash;}jdbc.update("UPDATE support_conversation SET last_hash=? WHERE tenant_id=2 AND id=9",previous);}
 String start(){return service.start(2,9,UUID.randomUUID().toString(),"synthetic bounded archive").get("id").toString();}
 @Test void moreThanTwoChunksAreCompleteReadOnlyAuditedAndResumable()throws Exception{
  seed(201);Map<String,Object> before=jdbc.queryForMap("SELECT * FROM support_conversation WHERE tenant_id=2 AND id=9");String key=UUID.randomUUID().toString();Map<String,Object> first=service.start(2,9,key,"synthetic archive");String id=first.get("id").toString();assertEquals(id,service.start(2,9,key,"synthetic archive").get("id"));assertThrows(RuntimeException.class,()->service.start(2,9,key,"different reason"));worker();service.process(2,id);assertEquals(100L,jdbc.queryForObject("SELECT processed_messages FROM control_chat_archive_job WHERE id=?",Long.class,id));service.process(2,id);service.process(2,id);service.process(2,id);control(7,false);Map<String,Object> status=service.status(2,id);assertEquals("COMPLETE",status.get("state"));assertEquals(201L,number(status,"processed_messages"));assertEquals(3L,number(status,"chunk_sequence"));Path manifest=service.download(2,id,"manifest-"+status.get("final_manifest_sha256")+".json");JsonNode body=json.readTree(manifest.toFile());assertEquals(3,body.path("chunks").size());assertEquals(201,body.path("messages").asInt());assertEquals(before,jdbc.queryForMap("SELECT * FROM support_conversation WHERE tenant_id=2 AND id=9"));assertEquals(201L,jdbc.queryForObject("SELECT COUNT(*) FROM support_message WHERE tenant_id=2",Long.class));assertEquals(7L,jdbc.queryForObject("SELECT actor_id FROM control_audit_log WHERE action='CHAT_ARCHIVE_START'",Long.class));assertEquals(3L,jdbc.queryForObject("SELECT COUNT(*) FROM control_audit_log WHERE actor_id IS NULL AND action='CHAT_ARCHIVE_CHUNK'",Long.class));
  JsonNode chunk=json.readTree(service.download(2,id,body.path("chunks").get(0).path("file").asText()).toFile());JsonNode image=chunk.path("attachments").get(0);assertArrayEquals(png(),Files.readAllBytes(service.download(2,id,image.path("file").asText())));assertThrows(RuntimeException.class,()->service.download(2,id,"../job.json"));assertThrows(RuntimeException.class,()->service.download(2,id,"image-1-"+"a".repeat(64)+".png"));
 }
 @Test void wrongRoleActorTenantAndInheritedWorkerContextFailClosed()throws Exception{seed(1);control(7,true);assertThrows(RuntimeException.class,this::start);control(7,false);String id=start();assertThrows(RuntimeException.class,()->service.start(3,9,UUID.randomUUID().toString(),"other tenant"));assertThrows(RuntimeException.class,()->service.process(2,id));control(8,false);assertThrows(RuntimeException.class,()->service.status(2,id));assertThrows(RuntimeException.class,()->service.retry(2,id,"wrong owner"));SecurityContextHolder.clearContext();assertThrows(RuntimeException.class,()->service.status(2,id));assertEquals(1L,jdbc.queryForObject("SELECT COUNT(*) FROM control_chat_archive_job",Long.class));}
 @Test void auditFailureRollsBackProgressAndNewWorkerReplaysPublishedChunkOnce()throws Exception{seed(101);String id=start();worker();audit.failChunk=true;service.run();assertEquals("FAILED",jdbc.queryForObject("SELECT state FROM control_chat_archive_job WHERE id=?",String.class,id));assertEquals(0L,jdbc.queryForObject("SELECT cursor_id FROM control_chat_archive_job WHERE id=?",Long.class,id));assertEquals(101L,jdbc.queryForObject("SELECT COUNT(*) FROM support_message",Long.class));audit.failChunk=false;control(7,false);service.retry(2,id,"actual audit persistence repaired");worker();service.process(2,id);ChatArchiveService restarted=new ChatArchiveService(jdbc,new DataSourceTransactionManager(jdbc.getDataSource()),audit,json,issues);ReflectionTestUtils.setField(restarted,"archiveDirectory",root.toString());restarted.process(2,id);restarted.process(2,id);control(7,false);assertEquals("COMPLETE",restarted.status(2,id).get("state"));try(java.util.stream.Stream<Path> paths=Files.list(root.resolve("tenant-2/job-"+id))){assertEquals(2,paths.filter(p->p.getFileName().toString().startsWith("chunk-")).count());}assertEquals(2L,jdbc.queryForObject("SELECT COUNT(*) FROM control_audit_log WHERE action='CHAT_ARCHIVE_CHUNK'",Long.class));}
 @Test void chainAndAttachmentFailuresPreserveAllRowsAndAreVisible()throws Exception{seed(100);String id=start();jdbc.update("UPDATE support_attachment SET content=? WHERE tenant_id=2 AND message_id=100",new byte[]{1,2,3});worker();service.run();assertEquals("FAILED",jdbc.queryForObject("SELECT state FROM control_chat_archive_job WHERE id=?",String.class,id));assertEquals(100L,jdbc.queryForObject("SELECT COUNT(*) FROM support_message",Long.class));assertEquals(1L,jdbc.queryForObject("SELECT COUNT(*) FROM control_audit_log WHERE action='TENANT_JOB_FAILED'",Long.class));jdbc.update("UPDATE support_attachment SET content=? WHERE tenant_id=2 AND message_id=100",png());control(7,false);service.retry(2,id,"synthetic attachment fault repaired");worker();service.process(2,id);service.process(2,id);control(7,false);assertEquals("COMPLETE",service.status(2,id).get("state"));Map<String,Object> status=service.status(2,id);Path manifest=service.download(2,id,"manifest-"+status.get("final_manifest_sha256")+".json");byte[] original=Files.readAllBytes(manifest);Files.write(manifest,new byte[]{1,2,3});assertThrows(RuntimeException.class,()->service.download(2,id,manifest.getFileName().toString()));Files.write(manifest,original);}
 @Test void unavailableFilesystemPreservesCursorAndSourceThenExplicitRetryCompletes()throws Exception{seed(101);String id=start();worker();service.process(2,id);ReflectionTestUtils.setField(service,"archiveDirectory",root.resolve("missing").toString());service.run();assertEquals("FAILED",jdbc.queryForObject("SELECT state FROM control_chat_archive_job WHERE id=?",String.class,id));assertEquals(100L,jdbc.queryForObject("SELECT cursor_id FROM control_chat_archive_job WHERE id=?",Long.class,id));ReflectionTestUtils.setField(service,"archiveDirectory",root.toString());control(7,false);service.retry(2,id,"restricted archive storage restored");worker();service.process(2,id);service.process(2,id);control(7,false);assertEquals("COMPLETE",service.status(2,id).get("state"));assertEquals(101L,jdbc.queryForObject("SELECT COUNT(*) FROM support_message",Long.class));}
 @Test void retentionQueuesOnceThenRequiresUnchangedCompleteWholeConversation()throws Exception{
  seed(201);assertNull(service.retentionArchive(2,9,7L,"controlled retention fixture"));assertNull(service.retentionArchive(2,9,7L,"controlled retention fixture"));assertEquals(1L,jdbc.queryForObject("SELECT COUNT(*) FROM control_chat_archive_job",Long.class));String id=jdbc.queryForObject("SELECT id FROM control_chat_archive_job",String.class);worker();for(int i=0;i<4;i++)service.process(2,id);control(7,false);String archive=service.retentionArchive(2,9,7L,"controlled revalidation");assertTrue(archive.startsWith("tenant-2/job-"+id+"/manifest-"));assertEquals(201L,jdbc.queryForObject("SELECT COUNT(*) FROM support_message",Long.class));jdbc.update("UPDATE support_message SET text='changed after archive' WHERE tenant_id=2 AND id=2");assertThrows(RuntimeException.class,()->service.retentionArchive(2,9,7L,"source changed"));jdbc.update("UPDATE support_conversation SET legal_hold=TRUE WHERE tenant_id=2 AND id=9");assertNull(service.retentionArchive(2,9,7L,"held conversation"));assertEquals(201L,jdbc.queryForObject("SELECT COUNT(*) FROM support_message",Long.class));
 }
 @Test void retentionRejectsNewUnarchivedAttachmentAndPreservesEverySourceRow()throws Exception{
  seed(101);String id=start();worker();for(int i=0;i<3;i++)service.process(2,id);control(7,false);assertNotNull(service.retentionArchive(2,9,7L,"complete archive"));jdbc.update("INSERT INTO support_attachment VALUES(1,2,?)",png());assertThrows(RuntimeException.class,()->service.retentionArchive(2,9,7L,"new unarchived attachment"));assertEquals(101L,jdbc.queryForObject("SELECT COUNT(*) FROM support_message",Long.class));assertEquals(2L,jdbc.queryForObject("SELECT COUNT(*) FROM support_attachment",Long.class));
 }
 @Test void automaticRetentionNeverInventsAnApproverOrInheritsRequestIdentity()throws Exception{
  seed(1);assertThrows(RuntimeException.class,()->service.retentionArchive(2,9,null,"SYSTEM fixture"));worker();assertNull(service.retentionArchive(2,9,null,"SYSTEM fixture; policy previously approved"));assertEquals("SYSTEM",jdbc.queryForObject("SELECT owner_key FROM control_chat_archive_job",String.class));assertNull(jdbc.queryForObject("SELECT actor_id FROM control_chat_archive_job",Long.class));assertNull(jdbc.queryForObject("SELECT actor_id FROM control_audit_log WHERE action='CHAT_ARCHIVE_START'",Long.class));assertEquals(1L,jdbc.queryForObject("SELECT COUNT(*) FROM support_message",Long.class));
 }

 @Test void jdbcDatetimeAndTimestampShareUtcMicrosecondCanonicalEncoding(){
  Instant expected=Instant.parse("2024-01-01T00:00:00.123456Z");
  assertEquals(expected.toString(),ChatArchiveService.archiveValue(java.time.LocalDateTime.ofInstant(expected,java.time.ZoneOffset.UTC)));
  assertEquals(expected.toString(),ChatArchiveService.archiveValue(Timestamp.from(expected)));
  assertNull(ChatArchiveService.archiveValue(null));assertEquals(Boolean.TRUE,ChatArchiveService.archiveValue(Boolean.TRUE));
 }
 @Test @org.junit.jupiter.api.condition.EnabledIfSystemProperty(named="manual.control.fixture",matches=".+")
 void actualMysqlDatetimeJdbcTypeKeepsUtcMicrosecondsWithoutDatabaseWrites()throws Exception{
  @SuppressWarnings("unchecked") Map<String,String> config=json.readValue(new java.io.File(System.getProperty("manual.control.fixture")),Map.class);
  assertTrue(config.get("url").matches("jdbc:mysql://127\\.0\\.0\\.1:(64029|33318|33418)/mt705_probe_[a-zA-Z0-9_]+\\?.*"));
  JdbcTemplate nativeDb=new JdbcTemplate(com.gtcfesk.exchange.tenant.DedicatedMysqlFixture.open(config));
  Object value=nativeDb.queryForMap("SELECT CAST('2024-01-01 00:00:00.123456' AS DATETIME(6)) AS created_at").get("created_at");
  assertTrue(value instanceof java.time.LocalDateTime || value instanceof Timestamp);
  assertEquals("2024-01-01T00:00:00.123456Z",ChatArchiveService.archiveValue(value));
 }

}
