package com.gtcfesk.exchange.control;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.test.util.ReflectionTestUtils;
import java.util.*;
import java.nio.file.*;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
class OperationalIssueTest {
 JdbcTemplate jdbc;ControlAuditService audit;OperationalIssueService service;DataSourceTransactionManager transactions;ObjectMapper json=new ObjectMapper();
 @BeforeEach void fixture(){DriverManagerDataSource ds=new DriverManagerDataSource("jdbc:h2:mem:ops_"+UUID.randomUUID()+";MODE=MySQL;DB_CLOSE_DELAY=-1","sa","");jdbc=new JdbcTemplate(ds);transactions=new DataSourceTransactionManager(ds);audit=mock(ControlAuditService.class);service=new OperationalIssueService(jdbc,audit,transactions,json);jdbc.execute("CREATE TABLE control_audit_log(id BIGINT AUTO_INCREMENT PRIMARY KEY,actor_id BIGINT,tenant_id BIGINT,action VARCHAR(128),object_ref VARCHAR(255),created_at TIMESTAMP,detail TEXT)");
  doAnswer(c->{jdbc.update("INSERT INTO control_audit_log(actor_id,tenant_id,action,object_ref,created_at,detail) VALUES(?,?,?,?,CURRENT_TIMESTAMP,?)",c.getArgument(0),c.getArgument(1),c.getArgument(3),c.getArgument(4),c.getArgument(6));return null;}).when(audit).record(any(),any(),any(),any(),any(),any(),any(),any());asControl();}
 void asControl(){UsernamePasswordAuthenticationToken auth=new UsernamePasswordAuthenticationToken("7",null,List.of(new SimpleGrantedAuthority("ROLE_CONTROL")));auth.setDetails(new ControlIdentity(7L,null,null));SecurityContextHolder.getContext().setAuthentication(auth);}
 @AfterEach void clear(){SecurityContextHolder.clearContext();}
 @Test void groupsOnlyRequestedTenantAndKeepsRealReviewActor() {service.failed(1L,"contract-match",new IllegalStateException("SECRET chat body must never be persisted"));service.failed(1L,"contract-match",new IllegalStateException("SECRET account must never be persisted"));service.failed(2L,"contract-match",new IllegalArgumentException("SECRET token"));List<Map<String,Object>> records=service.list(1L,0);assertEquals(1,records.size());assertEquals(2L,((Number)records.get(0).get("attempts")).longValue());long last=((Number)records.get(0).get("latest_failure_id")).longValue();service.review(1L,"contract-match",last,"Verified original engine retry evidence","a".repeat(64),"RECOVERED");assertEquals(7L,jdbc.queryForObject("SELECT actor_id FROM control_audit_log WHERE action='OPERATIONAL_ISSUE_REVIEW'",Long.class));assertFalse(jdbc.queryForList("SELECT detail FROM control_audit_log",String.class).toString().contains("SECRET"));assertThrows(IllegalArgumentException.class,()->service.review(2L,"contract-match",last,"Other tenant cannot ack this failure","a".repeat(64),"RECOVERED"));service.failed(1L,"contract-match",new IllegalArgumentException("late failure"));assertThrows(IllegalArgumentException.class,()->service.review(1L,"contract-match",last,"Stale failure cannot ack later attempts","a".repeat(64),"RECOVERED"));}
 @Test void noTenantRequestOrWrongRoleCanReadOrReview(){SecurityContextHolder.clearContext();assertThrows(org.springframework.security.access.AccessDeniedException.class,()->service.list(1L,0));UsernamePasswordAuthenticationToken auth=new UsernamePasswordAuthenticationToken("-7",null,List.of(new SimpleGrantedAuthority("ROLE_SUPER_ADMIN")));auth.setDetails(new ControlIdentity(7L,1L,"access"));SecurityContextHolder.getContext().setAuthentication(auth);assertThrows(org.springframework.security.access.AccessDeniedException.class,()->service.health());asControl();assertThrows(IllegalArgumentException.class,()->service.list(null,0));assertThrows(IllegalArgumentException.class,()->service.list(1L,-1));}
 @Test void failedAuditPersistsOnlyMetadataAndDoesNotPretendDatabaseRecovery(@org.junit.jupiter.api.io.TempDir Path directory)throws Exception {ReflectionTestUtils.setField(service,"failureDirectory",directory.toString());doThrow(new IllegalStateException("SECRET sql values")).when(audit).record(any(),any(),any(),any(),any(),any(),any(),any());service.failed(1L,"financial-yield",new RuntimeException("SECRET password"));assertEquals("LOCAL_JOURNAL_REQUIRES_IMPORT",service.health().get("failureDelivery"));try(java.util.stream.Stream<Path> files=Files.list(directory)){Path file=files.findFirst().orElseThrow();String text=Files.readString(file);assertFalse(text.contains("SECRET"));assertTrue(text.contains("RuntimeException"));}reset(audit);service.failed(1L,"financial-yield",new IllegalArgumentException());assertEquals("LOCAL_JOURNAL_REQUIRES_IMPORT",service.health().get("failureDelivery"));}
 @Test void cursorAfterOneHundredPreservedCandidatesFindsTheLastThenWraps(){jdbc.execute("CREATE TABLE support_conversation(id BIGINT PRIMARY KEY,tenant_id BIGINT,status VARCHAR(16),closed_at TIMESTAMP,legal_hold BOOLEAN)");for(int i=1;i<=101;i++)jdbc.update("INSERT INTO support_conversation VALUES(?,1,'CLOSED',TIMESTAMP '2020-01-01 00:00:00',FALSE)",i);jdbc.update("INSERT INTO support_conversation VALUES(102,2,'CLOSED',TIMESTAMP '2020-01-01 00:00:00',FALSE)");TenantPolicyRepository policies=mock(TenantPolicyRepository.class);TenantPolicy cursor=new TenantPolicy();cursor.setValue("100");when(policies.findByTenantIdAndKey(1L,"retention.scan_cursor")).thenReturn(Optional.of(cursor));ChatRetentionService retention=new ChatRetentionService(jdbc,mock(TenantRepository.class),policies,audit,json);List<?> ids=ReflectionTestUtils.invokeMethod(retention,"candidates",1L);assertEquals(List.of(101L),ids);cursor.setValue("101");List<?> wrapped=ReflectionTestUtils.invokeMethod(retention,"candidates",1L);assertEquals(100,wrapped.size());assertEquals(1L,wrapped.get(0));assertFalse(wrapped.contains(102L));}
 @Test void handWrittenLegacyRestoreMarkerCannotEnableDeletion(@org.junit.jupiter.api.io.TempDir Path directory)throws Exception{Files.writeString(directory.resolve(".retention-restore-verified"),"retention-json-v1");ChatRetentionService retention=new ChatRetentionService(jdbc,mock(TenantRepository.class),mock(TenantPolicyRepository.class),audit,json);ReflectionTestUtils.setField(retention,"archiveDirectory",directory.toString());assertThrows(IllegalStateException.class,()->ReflectionTestUtils.invokeMethod(retention,"verifyArchiveDirectory"));}
}
