// Focused real-browser stage3 acceptance. No mocked HTTP/application responses.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'C:/Users/徐乾妖/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'../..'),run=path.join(root,'reports/stage3-20261002-232106'),read=p=>JSON.parse(fs.readFileSync(path.join(run,p),'utf8'));
const state=read('private/stage3-state.json'),identity=read('private/identities.json'),attempt=Date.now(),dir=path.join(run,'browser',String(attempt));fs.mkdirSync(dir,{recursive:true});
const cert=new crypto.X509Certificate(fs.readFileSync(path.join(run,'private/server.crt'))),pin=crypto.createHash('sha256').update(cert.publicKey.export({type:'spki',format:'der'})).digest('base64');
const results=[],observations=[];
function totp(secret){const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567',bits=[...secret.toUpperCase().replace(/=+$/,'')].map(c=>alphabet.indexOf(c).toString(2).padStart(5,'0')).join(''),key=Buffer.from(bits.match(/.{8}/g).map(x=>parseInt(x,2))),counter=Buffer.alloc(8);counter.writeBigUInt64BE(BigInt(Math.floor(Date.now()/30000)));const h=crypto.createHmac('sha1',key).update(counter).digest(),offset=h[h.length-1]&15;return String((h.readUInt32BE(offset)&0x7fffffff)%1000000).padStart(6,'0');}
async function check(name,fn){try{const detail=await fn();results.push({name,status:'PASS_FRESH',detail});console.log('PASS '+name);}catch(e){results.push({name,status:'FAIL',error:e.message});throw e;}}
async function pageFor(context,name){const p=await context.newPage(),o={name,pageErrors:[],failedRequests:[],console:[]};observations.push(o);p.on('pageerror',e=>o.pageErrors.push(e.message));p.on('requestfailed',r=>o.failedRequests.push({path:new URL(r.url()).pathname,error:r.failure()?.errorText}));p.on('console',m=>{if(['warning','error'].includes(m.type()))o.console.push(m.text());});return p;}
async function screenshot(p,name){assert.ok(await p.title());assert.ok((await p.locator('body').innerText()).trim().length>20);assert.equal(await p.locator('vite-error-overlay').count(),0);await p.waitForFunction(()=>[...document.querySelectorAll('.el-overlay')].filter(el=>el.getBoundingClientRect().width>0&&getComputedStyle(el).display!=='none').every(el=>getComputedStyle(el).opacity==='1'&&[...el.querySelectorAll('.el-dialog')].every(d=>getComputedStyle(d).opacity==='1')));await p.screenshot({path:path.join(dir,name+'.png'),animations:'disabled',mask:[p.locator('input'),p.locator('.control-shell header span')]});}
async function socket(p,url,deny=false){return p.evaluate(({url,deny})=>new Promise((resolve,reject)=>{const ws=new WebSocket(url),timer=setTimeout(()=>{ws.close();reject(Error('Socket frame deadline'));},12000);const done=v=>{clearTimeout(timer);ws.close();resolve(v)};ws.onopen=()=>{if(deny){clearTimeout(timer);ws.close();reject(Error('Cross-origin socket accepted'));}else ws.send(JSON.stringify({action:'subscribe',symbols:['BTCUSDT']}));};ws.onerror=()=>deny?done({rejected:true}):reject(Error('Socket handshake failed'));ws.onmessage=e=>{const v=JSON.parse(e.data);if(v.type==='price'){if(!v.data.BTCUSDT){reject(Error('Expected symbol missing'));return;}done({type:v.type,symbols:Object.keys(v.data),quoteFields:Object.keys(v.data.BTCUSDT)});}};}),{url,deny});}
(async()=>{const browser=await chromium.launch({headless:true,chromiumSandbox:process.platform==='linux',...(process.platform==='linux'?{channel:'chromium'}:{}),...(process.platform==='win32'?{executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}:{}),args:process.env.STAGE3_HOST_IP?['--host-resolver-rules='+['default','a','a2','b','admin','control'].map(h=>'MAP '+h+'.localhost '+process.env.STAGE3_HOST_IP).join(', ')]:[]});try{
 for(const [label,t]of Object.entries(state.tenants))for(const mobile of [false,true]){const name=label+'-'+(mobile?'mobile':'pc');if(process.argv[2]==='remaining'){if(name==='default-pc')continue;}else if(process.argv[2]&&process.argv[2]!==name&&process.argv[2]!=='users')continue;
  const context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1440,height:1000}}),p=await pageFor(context,name),base='https://'+t.host+':8543';
  await check('inbox-'+name,async()=>{const response=p.waitForResponse(r=>r.url().endsWith('/api/auth/login')&&r.request().method()==='POST');response.catch(()=>{});await p.goto(base+(mobile?'/mobile/login':'/?login=1'));const form=p.locator(mobile?'.auth-card':'#pc-login-form');await form.locator('input[type=email]').fill(t.user.email);await form.locator('input[type=password]').fill(t.user.password);await (mobile?form.locator('.primary-btn'):p.locator('button[form=pc-login-form]')).click();const r=await response;assert.equal(r.status(),200);assert.equal((await r.json()).user.tenantId,t.id);if(mobile)await p.waitForURL('**/mobile/home');else await form.waitFor({state:'hidden'});
   await p.goto(base+(mobile?'/mobile/inbox':'/inbox'));const letter=p.locator('.letter').filter({hasText:t.letterTitle});await letter.waitFor();await letter.click();await p.locator('article h2').filter({hasText:t.letterTitle}).waitFor();assert.equal(await p.locator('.inbox-error').count(),0);await screenshot(p,name);if(mobile){await p.locator('.detail-back:visible').click();await p.locator('article h2').waitFor({state:'hidden'});await letter.waitFor({state:'visible'});}return{tenantId:t.id,actualLogin:true,letterTitle:t.letterTitle,detailVisible:true,mobileBackVerified:mobile};});
  if(!mobile)await check('websocket-'+label,async()=>({real:await socket(p,'wss://'+t.host+':8543/api/ws/market'),demo:await socket(p,'wss://'+t.host+':8543/demo-api/ws/market'),crossOrigin:await socket(p,'wss://'+(t.host==='b.localhost'?'a.localhost':'b.localhost')+':8543/api/ws/market',true)}));await context.close();
 }
 if(!process.argv[2]||['admin','remaining'].includes(process.argv[2])){const c=await browser.newContext({viewport:{width:1440,height:1000}}),p=await pageFor(c,'admin'),t=state.tenants.A;
  await check('admin-support',async()=>{await p.goto('https://admin.localhost:8543/login');await p.getByPlaceholder('输入后台账号').fill(t.owner.account);await p.getByPlaceholder('输入密码').fill(t.owner.password);await p.getByRole('button',{name:'登 录',exact:true}).click();await p.locator('.layout-container').waitFor();await p.goto('https://admin.localhost:8543/support');await p.locator('.scope-tabs').waitFor();await p.getByPlaceholder('用户邮箱').fill(t.user.email);await p.getByRole('button',{name:'搜索',exact:true}).click();await p.locator('.session-card').first().waitFor();await p.locator('.session-card .session-main').first().click();await p.locator('.chat-heading').waitFor();await screenshot(p,'admin-support');return{tenantId:t.id,actualOwner:true,visibleDetail:true};});await c.close();}
 if(!process.argv[2]||['control','remaining'].includes(process.argv[2])){const c=await browser.newContext({viewport:{width:1440,height:1000}}),p=await pageFor(c,'control'),t=state.tenants.A;
  await check('control-readonly-retention',async()=>{await p.goto('https://control.localhost:8543/');const inputs=p.locator('.control-login input');await inputs.nth(0).fill(identity.account);await inputs.nth(1).fill(identity.password);await inputs.nth(2).fill(totp(identity.totpSecret));const tenantsResponse=p.waitForResponse(r=>new URL(r.url()).pathname==='/api/control/tenants'&&r.status()===200);await p.getByRole('button',{name:'登录总控',exact:true}).click();const response=await tenantsResponse,v=await response.json(),rows=v.data?.content||v.data||v.content||v.list;assert.ok(Array.isArray(rows));const tenant=rows.find(x=>x.id===t.id);assert.ok(tenant);await p.getByRole('button',{name:'客服监管与留存',exact:true}).click();await p.locator('.el-select').click();await p.locator('.el-select-dropdown:visible').getByText(tenant.name,{exact:true}).click();await p.getByPlaceholder('用户邮箱',{exact:true}).fill(t.user.email);await p.getByRole('button',{name:'查询',exact:true}).click();const row=p.locator('.el-table__row').filter({has:p.locator('td').first().getByText(String(t.conversationId),{exact:true})});await row.getByRole('button',{name:'查看',exact:true}).click();const dialog=p.getByRole('dialog').filter({hasText:'会话 '+t.conversationId+' · 只读'});await dialog.waitFor();await dialog.getByText('Stage3 private support message',{exact:true}).waitFor();const download=p.waitForEvent('download');await dialog.getByRole('button',{name:'下载完整证据 JSON（含附件与校验）',exact:true}).click();const d=await download;const file=path.join(run,'private','browser-control-export-'+attempt+'.json');await d.saveAs(file);const exported=JSON.parse(fs.readFileSync(file));assert.equal(exported.chainValid,true);await screenshot(p,'control-supervision');await dialog.getByRole('button',{name:'Close this dialog',exact:true}).click();await dialog.waitFor({state:'hidden'});await p.getByRole('button',{name:'留存预览与策略',exact:true}).click();const preview=p.getByRole('dialog',{name:'历史会话留存'});await preview.getByText('365',{exact:true}).waitFor();await preview.getByText('关闭',{exact:true}).waitFor();await screenshot(p,'control-retention');return{tenantId:t.id,chainValid:true,actualMfa:true,retentionDays:365,disabled:true,exportSha256:crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex')};});await c.close();}
 if(process.argv[2]==='ws-default'){const c=await browser.newContext(),p=await pageFor(c,'ws-default');await p.goto('https://default.localhost:8543/');await check('websocket-default',async()=>({real:await socket(p,'wss://default.localhost:8543/api/ws/market'),demo:await socket(p,'wss://default.localhost:8543/demo-api/ws/market'),crossOrigin:await socket(p,'wss://b.localhost:8543/api/ws/market',true)}));await c.close();}assert.equal(observations.flatMap(o=>o.pageErrors).length,0);
}finally{fs.writeFileSync(path.join(dir,'result.json'),JSON.stringify({tool:'Playwright Chrome',fallbackReason:'Named Browser plugin/skill unavailable; installed Playwright fallback',tls:process.platform==='linux'?'Strict TLS, exact CA verified and installed only inside disposable stage3 browser container':'Normal TLS; Windows antivirus blocked initial attempts',results,observations},null,2));await browser.close();}})().catch(e=>{console.error(e.message);process.exitCode=1;});
