-- Install through Migrate-Cache.ps1. Each statement is independently restartable; never DROP existing triggers.
CREATE TABLE IF NOT EXISTS asset_history_revision (
 user_id BIGINT NOT NULL, basis_version VARCHAR(32) NOT NULL, level TINYINT NOT NULL,
 revision BIGINT NOT NULL, PRIMARY KEY(user_id,basis_version,level)
) ENGINE=InnoDB;
CREATE TRIGGER ahc_1_insert AFTER INSERT ON asset_history_1h FOR EACH ROW INSERT INTO asset_history_revision(user_id,basis_version,level,revision) SELECT NEW.user_id,NEW.basis_version,1,1 ON DUPLICATE KEY UPDATE revision=revision+1;

CREATE TRIGGER ahc_1_update AFTER UPDATE ON asset_history_1h FOR EACH ROW INSERT INTO asset_history_revision(user_id,basis_version,level,revision) SELECT NEW.user_id,NEW.basis_version,1,1 FROM DUAL WHERE NOT (OLD.user_id <=> NEW.user_id) OR NOT (OLD.basis_version <=> NEW.basis_version) OR NOT (OLD.bucket_start <=> NEW.bucket_start) OR NOT (OLD.bucket_end <=> NEW.bucket_end) OR NOT (OLD.open_value <=> NEW.open_value) OR NOT (OLD.high_value <=> NEW.high_value) OR NOT (OLD.low_value <=> NEW.low_value) OR NOT (OLD.close_value <=> NEW.close_value) OR NOT (OLD.open_at <=> NEW.open_at) OR NOT (OLD.high_at <=> NEW.high_at) OR NOT (OLD.low_at <=> NEW.low_at) OR NOT (OLD.close_at <=> NEW.close_at) OR NOT (OLD.source_count <=> NEW.source_count) OR NOT (OLD.valid_sample_count <=> NEW.valid_sample_count) OR NOT (OLD.invalid_sample_count <=> NEW.invalid_sample_count) OR NOT (OLD.expected_sample_count <=> NEW.expected_sample_count) OR NOT (OLD.finalized <=> NEW.finalized) OR NOT (OLD.quality <=> NEW.quality) OR NOT (OLD.source_through <=> NEW.source_through) UNION ALL SELECT OLD.user_id,OLD.basis_version,1,1 FROM DUAL WHERE NOT (OLD.user_id <=> NEW.user_id) OR NOT (OLD.basis_version <=> NEW.basis_version) ON DUPLICATE KEY UPDATE revision=revision+1;

CREATE TRIGGER ahc_1_delete AFTER DELETE ON asset_history_1h FOR EACH ROW INSERT INTO asset_history_revision(user_id,basis_version,level,revision) SELECT OLD.user_id,OLD.basis_version,1,1 ON DUPLICATE KEY UPDATE revision=revision+1;

CREATE TRIGGER ahc_2_insert AFTER INSERT ON asset_history_4h FOR EACH ROW INSERT INTO asset_history_revision(user_id,basis_version,level,revision) SELECT NEW.user_id,NEW.basis_version,2,1 ON DUPLICATE KEY UPDATE revision=revision+1;

CREATE TRIGGER ahc_2_update AFTER UPDATE ON asset_history_4h FOR EACH ROW INSERT INTO asset_history_revision(user_id,basis_version,level,revision) SELECT NEW.user_id,NEW.basis_version,2,1 FROM DUAL WHERE NOT (OLD.user_id <=> NEW.user_id) OR NOT (OLD.basis_version <=> NEW.basis_version) OR NOT (OLD.bucket_start <=> NEW.bucket_start) OR NOT (OLD.bucket_end <=> NEW.bucket_end) OR NOT (OLD.open_value <=> NEW.open_value) OR NOT (OLD.high_value <=> NEW.high_value) OR NOT (OLD.low_value <=> NEW.low_value) OR NOT (OLD.close_value <=> NEW.close_value) OR NOT (OLD.open_at <=> NEW.open_at) OR NOT (OLD.high_at <=> NEW.high_at) OR NOT (OLD.low_at <=> NEW.low_at) OR NOT (OLD.close_at <=> NEW.close_at) OR NOT (OLD.source_count <=> NEW.source_count) OR NOT (OLD.valid_sample_count <=> NEW.valid_sample_count) OR NOT (OLD.invalid_sample_count <=> NEW.invalid_sample_count) OR NOT (OLD.expected_sample_count <=> NEW.expected_sample_count) OR NOT (OLD.finalized <=> NEW.finalized) OR NOT (OLD.quality <=> NEW.quality) OR NOT (OLD.source_through <=> NEW.source_through) UNION ALL SELECT OLD.user_id,OLD.basis_version,2,1 FROM DUAL WHERE NOT (OLD.user_id <=> NEW.user_id) OR NOT (OLD.basis_version <=> NEW.basis_version) ON DUPLICATE KEY UPDATE revision=revision+1;

CREATE TRIGGER ahc_2_delete AFTER DELETE ON asset_history_4h FOR EACH ROW INSERT INTO asset_history_revision(user_id,basis_version,level,revision) SELECT OLD.user_id,OLD.basis_version,2,1 ON DUPLICATE KEY UPDATE revision=revision+1;

CREATE TRIGGER ahc_3_insert AFTER INSERT ON asset_history_1d FOR EACH ROW INSERT INTO asset_history_revision(user_id,basis_version,level,revision) SELECT NEW.user_id,NEW.basis_version,3,1 ON DUPLICATE KEY UPDATE revision=revision+1;

CREATE TRIGGER ahc_3_update AFTER UPDATE ON asset_history_1d FOR EACH ROW INSERT INTO asset_history_revision(user_id,basis_version,level,revision) SELECT NEW.user_id,NEW.basis_version,3,1 FROM DUAL WHERE NOT (OLD.user_id <=> NEW.user_id) OR NOT (OLD.basis_version <=> NEW.basis_version) OR NOT (OLD.bucket_start <=> NEW.bucket_start) OR NOT (OLD.bucket_end <=> NEW.bucket_end) OR NOT (OLD.open_value <=> NEW.open_value) OR NOT (OLD.high_value <=> NEW.high_value) OR NOT (OLD.low_value <=> NEW.low_value) OR NOT (OLD.close_value <=> NEW.close_value) OR NOT (OLD.open_at <=> NEW.open_at) OR NOT (OLD.high_at <=> NEW.high_at) OR NOT (OLD.low_at <=> NEW.low_at) OR NOT (OLD.close_at <=> NEW.close_at) OR NOT (OLD.source_count <=> NEW.source_count) OR NOT (OLD.valid_sample_count <=> NEW.valid_sample_count) OR NOT (OLD.invalid_sample_count <=> NEW.invalid_sample_count) OR NOT (OLD.expected_sample_count <=> NEW.expected_sample_count) OR NOT (OLD.finalized <=> NEW.finalized) OR NOT (OLD.quality <=> NEW.quality) OR NOT (OLD.source_through <=> NEW.source_through) UNION ALL SELECT OLD.user_id,OLD.basis_version,3,1 FROM DUAL WHERE NOT (OLD.user_id <=> NEW.user_id) OR NOT (OLD.basis_version <=> NEW.basis_version) ON DUPLICATE KEY UPDATE revision=revision+1;

CREATE TRIGGER ahc_3_delete AFTER DELETE ON asset_history_1d FOR EACH ROW INSERT INTO asset_history_revision(user_id,basis_version,level,revision) SELECT OLD.user_id,OLD.basis_version,3,1 ON DUPLICATE KEY UPDATE revision=revision+1;
