import type { Component } from 'vue'

export const businessPageLoaders: Record<string, () => Promise<{ default: Component }>> = {
  '/assets': () => import('./views/Assets.vue'),
  '/wallet': () => import('./views/Wallet.vue'),
  '/deposit': () => import('./views/Deposit.vue'),
  '/withdraw': () => import('./views/Withdraw.vue'),
  '/transfer': () => import('./views/Transfer.vue'),
  '/deposit/records': () => import('./views/DepositRecords.vue'),
  '/wallet/bind-bank-card': () => import('./views/BindBankCard.vue'),
  '/wallet/bind-digital-currency': () => import('./views/BindDigitalCurrency.vue'),
  '/credit-loan': () => import('./views/CreditLoan.vue'),
  '/loan/personal-info': () => import('./views/LoanPersonalInfo.vue'),
  '/loan/apply-info': () => import('./views/LoanApplyInfo.vue'),
  '/loan/contract': () => import('./views/LoanContract.vue'),
  '/loan/sign': () => import('./views/LoanSign.vue'),
  '/loan/records': () => import('./views/LoanRecords.vue'),
  '/financial-management': () => import('./views/FinancialManagement.vue'),
  '/financial/purchase': () => import('./views/FinancialPurchase.vue'),
  '/financial/orders': () => import('./views/FinancialOrders.vue'),
  '/financial/yield-list': () => import('./views/FinancialYieldList.vue'),
  '/verification': () => import('./views/Verification.vue'),
  '/inbox': () => import('./views/Inbox.vue'),
  '/announcements': () => import('./views/Announcements.vue'),
  '/customer-service': () => import('./views/CustomerService.vue'),
  '/complaint': () => import('./views/Complaint.vue'),
  '/change-password': () => import('./views/ChangePassword.vue'),
  '/invite': () => import('./views/Invite.vue'),
  '/register': () => import('./views/Register.vue'),
  '/search': () => import('./views/Search.vue'),
}
