export type DesignNode = { type: 'box'|'text'|'image'|'button'|'amount'; text?: string; src?: string; backgroundSrc?: string; action?: string; target?: string; style?: Record<string,string>; children?: DesignNode[] }
export type DesignPage = { id: string; name: string; nodes: DesignNode[] }
export type ActivityDesign = { version: 1; dialog?: {width:number; radius:number; backdrop:string; blur:number}; locales: Record<string, { pages: DesignPage[] }> }
export const styleProperties = ['display','flex-direction','flex-wrap','justify-content','align-items','align-self','flex-grow','flex-shrink','flex-basis','gap','width','height','min-height','max-height','min-width','max-width','padding','padding-top','padding-right','padding-bottom','padding-left','margin','margin-top','margin-right','margin-bottom','margin-left','background-color','background-image','background-size','background-position','background-repeat','color','font-family','font-size','font-weight','font-style','line-height','letter-spacing','text-align','text-decoration','border','border-width','border-style','border-color','border-radius','box-shadow','opacity','object-fit','object-position','overflow','position','top','right','bottom','left','transform']
export function safeStyle(style: Record<string,string> = {}) { return Object.fromEntries(Object.entries(style).filter(([key,value]) => styleProperties.includes(key) && typeof value==='string' && value.length<=300 && !/[;{}<>@\\]|url\s*\(|expression\s*\(/i.test(value) && !(key==='position'&&value==='fixed'))) }
export function parseDesign(value?: string): ActivityDesign | null { try { const d=JSON.parse(value||'null');return d?.version===1&&d.locales ? d : null } catch { return null } }
export function designText(text: string|undefined, amount: string|number, days: number) { return String(text||'').split('{amount}').join(String(Number(amount))).split('{days}').join(String(days)) }
export function defaultPages(copy: Record<string,string>, locale='zh-CN'): DesignPage[] {
 const zh=locale.startsWith('zh'), text=(value:string,size='16px'):DesignNode=>({type:'text',text:value,style:{'font-size':size,'line-height':'1.7','margin':'0','color':'#43533b'}})
 const button=(value:string,action:string,target=''):DesignNode=>({type:'button',text:value,action,target,style:{'background-color':'#85bd00','color':'#ffffff','border':'0','border-radius':'12px','padding':'16px','width':'100%','font-size':'16px','font-weight':'600'}})
 const hero:DesignNode={type:'box',style:{'background-image':'linear-gradient(135deg, #f1f8e8, #deedcd)','padding':'32px','text-align':'center','display':'flex','flex-direction':'column','gap':'12px'},children:[text(zh?'专属礼遇':'EXCLUSIVE REWARD','12px'),text('🎁','76px'),{type:'amount',text:'{amount} U',style:{'font-size':'56px','font-weight':'700','color':'#344c25'}},text(zh?'一份心意，开启更多可能':'A gift for your next opportunity','13px')]}
 const page=(id:string,name:string,content:DesignNode[]):DesignPage=>({id,name,nodes:[{type:'box',style:{'background-color':'#ffffff','border-radius':'20px','overflow':'hidden','font-family':'system-ui','width':'100%'},children:[JSON.parse(JSON.stringify(hero)),{type:'box',style:{'padding':'28px','display':'flex','flex-direction':'column','gap':'18px'},children:content}]}]})
 return [page('gift',zh?'首屏':'Cover',[text(copy.title||'', '26px'),text(zh?'打开查看活动详情':'Open to see the details'),button(copy.open||(zh?'打开礼遇':'Open gift'),'page','detail'),button(copy.close||(zh?'关闭':'Close'),'close')]),page('detail',zh?'详情页':'Details',[text(copy.title||'','26px'),text(copy.body||''),text(copy.terms||'','13px'),button(copy.claim||(zh?'领取 {amount} U':'Claim {amount} U'),'claim')]),page('success',zh?'领取成功页':'Success',[text(copy.success||(zh?'领取成功':'Claim successful'),'26px'),text(copy.terms||'','13px'),button(zh?'去交易':'Trade now','link','/trade')])]
}
