package com.gtcfesk.exchange.admin;
import com.gtcfesk.exchange.insights.news.*;import com.gtcfesk.exchange.config.AdminPermission;import lombok.RequiredArgsConstructor;import org.springframework.web.bind.annotation.*;import org.springframework.format.annotation.DateTimeFormat;import java.time.*;import java.util.*;
@RestController @RequestMapping("/api/admin/insights/news") @RequiredArgsConstructor
public class AdminNewsController {
    private final NewsService service;private final NewsSync sync;
    @GetMapping @AdminPermission(menu="news") public Map<String,Object> list(@RequestParam(required=false) String category,@RequestParam(required=false) String sourceId,@RequestParam(required=false) String language,@RequestParam(required=false) @DateTimeFormat(iso=DateTimeFormat.ISO.DATE_TIME) Instant from,@RequestParam(required=false) @DateTimeFormat(iso=DateTimeFormat.ISO.DATE_TIME) Instant to,@RequestParam(defaultValue="0") int page,@RequestParam(defaultValue="20") int size,@RequestParam(required=false) Boolean hidden){return service.list(category,sourceId,language,from,to,page,size,hidden,true);}
    @GetMapping("/sources") @AdminPermission(menu="news") public List<Map<String,Object>> sources(){return service.sources(true);}
    @GetMapping("/audit") @AdminPermission(menu="news") public List<NewsAudit> audits(@RequestParam(defaultValue="0") int page){return service.audits(page);}
    @PutMapping("/sources/{id}") @AdminPermission(menu="news",action="source") public Map<String,Object> source(@PathVariable String id,@RequestBody NewsService.SourceEdit input){return service.sourceEdit(id,input);}
    @PostMapping("/sources/{id}/sync") @AdminPermission(menu="news",action="sync") public Map<String,Object> sync(@PathVariable String id){com.gtcfesk.exchange.insights.CalendarService.actor();NewsCatalog.check(id);if(!service.enabledSourceIds().contains(id))throw NewsCatalog.bad("来源关闭或未完成后端配置");Map<String,Object> out=sync.sync(id);out.put("changed",service.importCached(id));out.put("sources",service.sources(true));return out;}
    @GetMapping("/{id}") @AdminPermission(menu="news") public Map<String,Object> detail(@PathVariable String id){return service.detail(id,true);}
    @PutMapping("/{id}") @AdminPermission(menu="news",action="edit") public Map<String,Object> edit(@PathVariable String id,@RequestBody NewsService.Edit input){return service.edit(id,input);}
    public static class Import {public String sourceId,format,content,material;public boolean verified;}
    @PostMapping("/import") @AdminPermission(menu="news",action="import") public Map<String,Object> importMaterial(@RequestBody Import input){com.gtcfesk.exchange.insights.CalendarService.actor();if(input==null||!input.verified||!Arrays.asList("RSS","ATOM").contains(input.format)||input.content==null||input.content.length()>2000000)throw NewsCatalog.bad("须核验合法RSS/Atom材料并限制大小");try{NewsParser.Batch b=NewsParser.xml(NewsCatalog.check(input.sourceId),input.content,Instant.now());Map<String,Object> out=new LinkedHashMap<>();out.put("changed",service.importBatch(input.sourceId,b,true,input.material));out.put("skipped",b.skipped);out.put("publication","NEW_MANUAL_ENTRIES_HIDDEN_UNTIL_REVIEW");return out;}catch(org.springframework.web.server.ResponseStatusException e){throw e;}catch(Exception e){throw NewsCatalog.bad("RSS/Atom格式无效或含禁用的XML结构");}}
}
