package com.gtcfesk.exchange.insights.traders;

import com.fasterxml.jackson.databind.*;
import com.gtcfesk.exchange.insights.CalendarService;
import com.gtcfesk.exchange.simulation.SimulationEnvironment;
import com.gtcfesk.exchange.tenant.TenantContext;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;
import javax.persistence.*;
import java.math.BigDecimal;
import java.time.*;
import java.util.*;

@Service @RequiredArgsConstructor @Transactional(readOnly=true)
public class TraderService {
    @PersistenceContext private EntityManager em;
    private final ObjectMapper json;
    private final SimulationEnvironment simulation;
    public String environment(){return simulation.enabled()?"DEMO":"REAL";}
    private <T> TypedQuery<T> query(String q,Class<T> type){return em.createQuery(q,type).setParameter("tenant",TenantContext.requireTenantId()).setParameter("env",environment());}
    private static final String SCOPE=" where x.tenantId=:tenant and x.environment=:env";
    private static final String PUBLIC=" and x.status='PUBLISHED' and x.sourceType in :sources";
    private List<String> publicSources(){return environment().equals("DEMO")?Arrays.asList("ADMIN_CURATED","DEMO"):Collections.singletonList("ADMIN_CURATED");}
    public static ResponseStatusException bad(String message){return new ResponseStatusException(HttpStatus.BAD_REQUEST,message);}
    private static ResponseStatusException missing(){return new ResponseStatusException(HttpStatus.NOT_FOUND,"人物不存在、未发布、已下架或无权访问");}
    private static void uuid(String id){if(id==null||!id.matches("[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}"))throw missing();}
    private TraderProfile profile(String id,boolean admin,boolean lock){
        uuid(id);TypedQuery<TraderProfile> q=query("from TraderProfile x"+SCOPE+" and x.traderId=:id"+(admin?"":PUBLIC),TraderProfile.class).setParameter("id",id);
        if(!admin)q.setParameter("sources",publicSources());if(lock)q.setLockMode(LockModeType.PESSIMISTIC_WRITE);
        List<TraderProfile> rows=q.getResultList();if(rows.isEmpty())throw missing();return rows.get(0);
    }
    private String encode(Object data){try{return json.writeValueAsString(data);}catch(Exception e){throw new IllegalStateException(e);}}
    private TraderData decode(TraderProfile p){try{return json.readValue(p.getDataJson(),TraderData.class);}catch(Exception e){throw new IllegalStateException("展示资料不可读",e);}}
    private static String text(String value,int max,boolean required,String field){
        if(value==null||value.trim().isEmpty()){if(required)throw bad(field+"不能为空");return null;}
        value=value.trim();if(value.length()>max||value.indexOf('<')>=0||value.indexOf('>')>=0||value.codePoints().anyMatch(c->c<32&&c!='\n'&&c!='\t'))throw bad(field+"须为纯文本且长度不超过"+max);return value;
    }
    private static BigDecimal decimal(String value,boolean required,int sign,String field){
        if(value==null||value.trim().isEmpty()){if(required)throw bad(field+"不能为空");return null;}
        if(!value.matches("-?[0-9]{1,20}(\\.[0-9]{1,18})?"))throw bad(field+"须为十进制字符串，最多20位整数及18位小数");
        BigDecimal n=new BigDecimal(value);if(sign==1&&n.signum()<=0||sign==0&&n.signum()<0)throw bad(field+(sign==1?"须大于零":"不能为负数"));return n;
    }
    private static String number(BigDecimal n){return n==null?null:n.stripTrailingZeros().toPlainString();}
    private static String percent(String s,boolean bounded,String field){BigDecimal n=decimal(s,false,-1,field);if(bounded&&n!=null&&(n.signum()<0||n.compareTo(new BigDecimal("100"))>0))throw bad(field+"须为0至100");return number(n);}
    private static void currency(String actual,String expected){if(!Objects.equals(actual,expected))throw bad("currency须与人物统计币种一致："+expected);}
    private static Instant instant(String value,String field){try{Instant i=Instant.parse(value);if(i.getNano()%1000!=0)throw bad(field+"最多微秒精度");return i;}catch(ResponseStatusException e){throw e;}catch(Exception e){throw bad(field+"须为含Z或时差的ISO-8601时间");}}
    private static void inPeriod(Instant i,TraderData d,String field){if(i.isBefore(d.statisticStart)||i.isAfter(d.statisticEnd))throw bad(field+"超出人物统计期");}
    private void validate(TraderData d){
        if(d==null)throw bad("缺少资料data");d.name=text(d.name,80,true,"name");d.bio=text(d.bio,2000,false,"bio");
        if(!Arrays.asList("ADMIN_CURATED","DEMO").contains(d.sourceType)||d.sourceType.equals("DEMO")&&!environment().equals("DEMO"))throw bad("仅支持人工资料；DEMO仅限演示环境，VERIFIED_PLATFORM尚无核验链");
        if(d.currency==null||!d.currency.matches("[A-Z0-9]{2,12}"))throw bad("currency须为2至12位大写币种代码");
        if(d.statisticStart==null||d.statisticEnd==null||!d.statisticEnd.isAfter(d.statisticStart)||Duration.between(d.statisticStart,d.statisticEnd).toDays()>3660||d.statisticStart.getNano()%1000!=0||d.statisticEnd.getNano()%1000!=0)throw bad("统计期须为有效UTC时间范围，最多3660日、微秒精度");
        if(d.strategyTags==null||d.strategyTags.size()>10)throw bad("strategyTags最多10个");Set<String> tags=new LinkedHashSet<>();for(String t:d.strategyTags){t=text(t,32,true,"策略标签");if(!tags.add(t))throw bad("策略标签重复");}d.strategyTags=new ArrayList<>(tags);
        d.sourceNote=text(d.sourceNote,1000,false,"来源说明");d.metricBasisNote=text(d.metricBasisNote,1000,false,"指标口径");d.riskNote=text(d.riskNote,1000,false,"风险说明");d.authorizationNote=text(d.authorizationNote,1000,false,"展示授权记录");
        if(d.pointIntervalHours<1||d.pointIntervalHours>720)throw bad("曲线采样间隔须为1至720小时");
        d.manualRoi=percent(d.manualRoi,false,"人工ROI");d.manualWinRate=percent(d.manualWinRate,true,"人工胜率");d.manualMaxDrawdown=percent(d.manualMaxDrawdown,true,"人工回撤");
        d.avatarUrl=text(d.avatarUrl,300,false,"头像");if(d.avatarUrl!=null){String prefix=environment().equals("DEMO")?"/demo-uploads/images/":"/api/uploads/images/";
            if(!d.avatarUrl.matches(java.util.regex.Pattern.quote(prefix+TenantContext.requireTenantId()+"/staff/")+"(?:agent-)?-?[0-9]{1,19}/[a-zA-Z0-9_-]+\\.(?:png|jpg|jpeg|webp|gif)"))throw bad("头像须为当前租户管理员已有图片上传地址，不接受外链或用户私有图片");}
    }
    private void write(TraderProfile p,TraderData d){p.setName(d.name);p.setAvatarUrl(d.avatarUrl);p.setCurrency(d.currency);p.setSourceType(d.sourceType);p.setDataJson(encode(d));}
    private static void version(TraderProfile p,Long expected){if(expected==null||p.getRowVersion()!=expected)throw new ResponseStatusException(HttpStatus.CONFLICT,"人物版本已更新，请刷新后重新预览");}
    private static void reason(String value){text(value,1000,true,"修改依据reason");}
    private void touch(TraderProfile p,boolean toDraft){if(toDraft&&p.getStatus().equals("PUBLISHED"))p.setStatus("DRAFT");p.setUpdatedAt(Instant.now());em.flush();}
    private void audit(TraderProfile p,String object,String action,String reason,Object before,Object after){TraderAudit a=new TraderAudit();a.setEnvironment(environment());a.setTraderId(p.getTraderId());a.setObjectId(object);a.setActor(CalendarService.actor());a.setAction(action);a.setReason(reason.trim());a.setBeforeJson(before==null?null:encode(before));a.setAfterJson(after==null?null:encode(after));em.persist(a);}
    private static void paging(int page,int size){if(page<0||page>10000||size<1||size>100)throw bad("page须0至10000，size须1至100");}
    private static Map<String,Object> page(List<?> content,long total,int page,int size){Map<String,Object> out=new LinkedHashMap<>();out.put("content",content);out.put("number",page);out.put("size",size);out.put("totalElements",total);out.put("totalPages",(total+size-1)/size);return out;}
    private Map<String,Object> periodIdentity(TraderProfile p){TraderData d=decode(p);Map<String,Object> m=new LinkedHashMap<>();m.put("id",p.getTraderId()+":"+d.statisticStart+"/"+d.statisticEnd);m.put("start",d.statisticStart);m.put("end",d.statisticEnd);m.put("timezone","UTC");return m;}
    private Map<String,Object> view(TraderProfile p,boolean admin){
        TraderData d=decode(p);Map<String,Object> out=json.convertValue(d,new com.fasterxml.jackson.core.type.TypeReference<LinkedHashMap<String,Object>>(){});out.remove("authorizationNote");
        out.put("traderId",p.getTraderId());out.put("statisticPeriodId",periodIdentity(p).get("id"));out.put("statisticPeriod",periodIdentity(p));out.put("status",p.getStatus());out.put("sourceType",p.getSourceType());out.put("environment",p.getEnvironment());out.put("demo",p.getSourceType().equals("DEMO")||p.getEnvironment().equals("DEMO"));
        out.put("updatedAt",p.getUpdatedAt());out.put("rowVersion",p.getRowVersion());out.put("recommended",p.isRecommended());out.put("sortOrder",p.getSortOrder());out.put("sortMeaning","RECOMMENDATION_NOT_PERFORMANCE");out.put("performanceRankingAvailable",false);out.put("metricSource","MANUAL");out.put("verificationStatus","UNVERIFIED");out.put("disclosure","平台展示·人工维护；不是已核验业绩榜，历史表现不保证未来收益");out.put("curveDisclosure","净资产曲线·人工维护，非策略收益率；现金流未知时不计算收益");out.put("historyDisclosure","历史记录·人工维护");
        long points=query("select count(x) from TraderEquity x"+SCOPE+" and x.traderId=:id",Long.class).setParameter("id",p.getTraderId()).getSingleResult();out.put("equityPointCount",points);out.put("curveAvailability",points==0?"NONE":points<2?"INSUFFICIENT":"AVAILABLE");out.put("curveGapCheck","EQUITY_ENDPOINT");
        if(admin)out.put("data",d);return out;
    }
    public Map<String,Object> detail(String id,boolean admin){return view(profile(id,admin,false),admin);}
    public Map<String,Object> preview(String id){Map<String,Object> out=view(profile(id,true,false),false);out.put("preview",true);out.put("publiclyVisible",out.get("status").equals("PUBLISHED"));return out;}
    public Map<String,Object> list(String q,String currency,String sourceType,Boolean recommended,String status,String sort,int page,int size,boolean admin){
        paging(page,size);if(!Arrays.asList("RECOMMENDED","UPDATED","NAME").contains(sort))throw bad("仅支持推荐、更新时间和名称排序；未核验人工指标不能构成业绩排行");
        q=text(q,80,false,"q");if(currency!=null&&!currency.matches("[A-Z0-9]{2,12}"))throw bad("币种筛选无效");if(sourceType!=null&&!Arrays.asList("ADMIN_CURATED","DEMO").contains(sourceType))throw bad("来源筛选无效");if(status!=null&&(!admin||!Arrays.asList("DRAFT","PUBLISHED","OFFLINE","DISABLED").contains(status)))throw bad("状态筛选无效");
        String where=SCOPE+(admin?"":PUBLIC)+(q==null?"":" and lower(x.name) like :q escape '!'")+(currency==null?"":" and x.currency=:currency")+(sourceType==null?"":" and x.sourceType=:source")+(recommended==null?"":" and x.recommended=:recommended")+(status==null?"":" and x.status=:status");
        String order=sort.equals("NAME")?"x.name asc,x.traderId asc":sort.equals("UPDATED")?"x.updatedAt desc,x.traderId asc":"x.sortOrder desc,x.updatedAt desc,x.traderId asc";
        TypedQuery<TraderProfile> rows=query("from TraderProfile x"+where+" order by "+order,TraderProfile.class);TypedQuery<Long> count=query("select count(x) from TraderProfile x"+where,Long.class);
        for(TypedQuery<?> x:Arrays.asList(rows,count)){if(!admin)x.setParameter("sources",publicSources());if(q!=null)x.setParameter("q","%"+q.toLowerCase(Locale.ROOT).replace("!","!!").replace("%","!%").replace("_","!_")+"%");if(currency!=null)x.setParameter("currency",currency);if(sourceType!=null)x.setParameter("source",sourceType);if(recommended!=null)x.setParameter("recommended",recommended);if(status!=null)x.setParameter("status",status);}
        List<Map<String,Object>> content=new ArrayList<>();for(TraderProfile p:rows.setFirstResult(page*size).setMaxResults(size).getResultList())content.add(view(p,admin));Map<String,Object> out=page(content,count.getSingleResult(),page,size);out.put("sortMeaning","RECOMMENDATION_NOT_PERFORMANCE");out.put("performanceRankingAvailable",false);out.put("environment",environment());out.put("asOf",Instant.now());out.put("dataStatus",content.isEmpty()?"EMPTY":"AVAILABLE");return out;
    }
    @Transactional public Map<String,Object> create(TraderData.Edit input){CalendarService.actor();if(input==null)throw bad("缺少资料");reason(input.reason);validate(input.data);TraderProfile p=new TraderProfile();p.setEnvironment(environment());p.setTraderId(UUID.randomUUID().toString());p.setStatus("DRAFT");p.setUpdatedAt(Instant.now());write(p,input.data);em.persist(p);em.flush();Map<String,Object> out=view(p,true);audit(p,null,"CREATE",input.reason,null,out);return out;}
    @Transactional public Map<String,Object> edit(String id,TraderData.Edit input){CalendarService.actor();if(input==null)throw bad("缺少资料");reason(input.reason);TraderProfile p=profile(id,true,true);version(p,input.rowVersion);validate(input.data);TraderData old=decode(p);
        if(!old.currency.equals(input.data.currency)||!old.statisticStart.equals(input.data.statisticStart)||!old.statisticEnd.equals(input.data.statisticEnd)){long children=query("select count(x) from TraderEquity x"+SCOPE+" and x.traderId=:id",Long.class).setParameter("id",id).getSingleResult()+query("select count(x) from TraderHistory x"+SCOPE+" and x.traderId=:id",Long.class).setParameter("id",id).getSingleResult();if(children>0)throw bad("已有曲线或历史，不能改变币种/统计期；请另建人物统计档案，避免旧单位错配");}
        Map<String,Object> before=view(p,true);write(p,input.data);touch(p,true);Map<String,Object> out=view(p,true);audit(p,null,"EDIT",input.reason,before,out);return out;
    }
    @Transactional public Map<String,Object> publication(String id,TraderData.Change input){CalendarService.actor();if(input==null||!Arrays.asList("DRAFT","PUBLISHED","OFFLINE").contains(input.status))throw bad("发布状态无效");reason(input.reason);TraderProfile p=profile(id,true,true);version(p,input.rowVersion);if(p.getStatus().equals("DISABLED"))throw bad("禁用人物需先解除禁用，解除后仍为草稿");TraderData d=decode(p);
        if(input.status.equals("PUBLISHED")){validate(d);text(d.sourceNote,1000,true,"来源说明");text(d.metricBasisNote,1000,true,"指标口径");text(d.riskNote,1000,true,"风险说明");text(d.authorizationNote,1000,true,"展示授权记录");if(d.statisticEnd.isAfter(Instant.now()))throw bad("统计期未结束，不能发布为已发生的历史表现");}
        Map<String,Object> before=view(p,true);p.setStatus(input.status);touch(p,false);Map<String,Object> out=view(p,true);audit(p,null,"PUBLICATION",input.reason,before,out);return out;
    }
    @Transactional public Map<String,Object> disable(String id,TraderData.Change input){CalendarService.actor();if(input==null||input.disabled==null)throw bad("缺少disabled布尔值");reason(input.reason);TraderProfile p=profile(id,true,true);version(p,input.rowVersion);Map<String,Object> before=view(p,true);p.setStatus(input.disabled?"DISABLED":"DRAFT");touch(p,false);Map<String,Object> out=view(p,true);audit(p,null,"DISABLE",input.reason,before,out);return out;}
    @Transactional public Map<String,Object> recommendation(String id,TraderData.Change input){CalendarService.actor();if(input==null||input.recommended==null||input.sortOrder==null||Math.abs((long)input.sortOrder)>10000)throw bad("推荐须为布尔值，sortOrder须-10000至10000");reason(input.reason);TraderProfile p=profile(id,true,true);version(p,input.rowVersion);Map<String,Object> before=view(p,true);p.setRecommended(input.recommended);p.setSortOrder(input.sortOrder);touch(p,false);Map<String,Object> out=view(p,true);audit(p,null,"RECOMMENDATION",input.reason,before,out);return out;}
    private Instant[] window(TraderProfile p,String period){TraderData d=decode(p);int days;if(period.equals("ALL"))days=0;else if(period.equals("7D"))days=7;else if(period.equals("30D"))days=30;else if(period.equals("90D"))days=90;else throw bad("period须ALL/7D/30D/90D");Instant from=days==0?d.statisticStart:d.statisticEnd.minusSeconds(days*86400L);if(from.isBefore(d.statisticStart))from=d.statisticStart;return new Instant[]{from,d.statisticEnd};}
    private <T> TypedQuery<T> children(String entity,Class<T> type,String id){return query("from "+entity+" x"+SCOPE+" and x.traderId=:id",type).setParameter("id",id);}
    private Map<String,Object> equityView(TraderEquity e){Map<String,Object> out=new LinkedHashMap<>();out.put("pointId",e.getPointId());out.put("pointAt",e.getPointAt());out.put("netAsset",number(e.getNetAsset()));out.put("cashFlow",number(e.getCashFlow()));out.put("currency",e.getCurrency());out.put("sourceNote",e.getSourceNote());return out;}
    private Map<String,Object> historyView(TraderHistory h,boolean admin){Map<String,Object> out=new LinkedHashMap<>();out.put("recordId",h.getRecordId());out.put("closedAt",h.getClosedAt());out.put("symbol",h.getSymbol());out.put("direction",h.getDirection());out.put("leverage",number(h.getLeverage()));out.put("quantity",number(h.getQuantity()));out.put("quantityUnit",h.getQuantityUnit());out.put("pnl",number(h.getPnl()));out.put("pnlBasis",h.getPnlBasis());out.put("fees",number(h.getFees()));out.put("currency",h.getCurrency());out.put("sourceNote",h.getSourceNote());out.put("verificationStatus","UNVERIFIED");if(admin){out.put("recordKey",h.getRecordKey());out.put("evidenceNote",h.getEvidenceNote());}return out;}
    private void common(Map<String,Object> out,TraderProfile p,Instant[] w,String period){out.put("traderId",p.getTraderId());out.put("statisticPeriodId",periodIdentity(p).get("id"));out.put("statisticPeriod",periodIdentity(p));out.put("period",period);out.put("from",w[0]);out.put("to",w[1]);out.put("currency",p.getCurrency());out.put("sourceType",p.getSourceType());out.put("environment",environment());out.put("updatedAt",p.getUpdatedAt());out.put("rowVersion",p.getRowVersion());out.put("verificationStatus","UNVERIFIED");}
    public Map<String,Object> equity(String id,String period,int page,int size,boolean admin){paging(page,size);TraderProfile p=profile(id,admin,false);Instant[] w=window(p,period);TraderData d=decode(p);
        // ponytail: bounded at 10,000 points/profile; use an SQL gap aggregate if this measured read cost grows.
        List<TraderEquity> all=query("from TraderEquity x"+SCOPE+" and x.traderId=:id and x.pointAt>=:from and x.pointAt<=:to order by x.pointAt,x.pointId",TraderEquity.class).setParameter("id",id).setParameter("from",w[0]).setParameter("to",w[1]).setMaxResults(10000).getResultList();
        int gaps=0;boolean unknown=false;List<Map<String,Object>> content=new ArrayList<>();long interval=d.pointIntervalHours*3600L;for(int i=0;i<all.size();i++){TraderEquity e=all.get(i);unknown|=e.getCashFlow()==null;boolean gap=i+1<all.size()&&Duration.between(e.getPointAt(),all.get(i+1).getPointAt()).getSeconds()>interval;if(gap)gaps++;if(i>=page*size&&i<(page+1)*size){Map<String,Object> v=equityView(e);v.put("gapAfter",gap);content.add(v);}}
        boolean boundary=!all.isEmpty()&&(Duration.between(w[0],all.get(0).getPointAt()).getSeconds()>interval||Duration.between(all.get(all.size()-1).getPointAt(),w[1]).getSeconds()>interval);String state=all.isEmpty()?"NONE":all.size()<2?"INSUFFICIENT":all.get(0).getNetAsset().signum()==0?"ZERO_BASE":gaps>0||boundary?"GAPPED":"AVAILABLE";
        Map<String,Object> out=page(content,all.size(),page,size);common(out,p,w,period);out.put("curveStatus",state);out.put("gapCount",gaps);out.put("missingBoundary",boundary);out.put("coverageStart",all.isEmpty()?null:all.get(0).getPointAt());out.put("coverageEnd",all.isEmpty()?null:all.get(all.size()-1).getPointAt());out.put("unknownCashFlows",unknown);out.put("pointIntervalHours",d.pointIntervalHours);out.put("curveKind","MANUAL_NET_ASSET");out.put("strategyReturn",null);out.put("disclosure","净资产曲线·人工维护，非策略收益率；不补缺点，不推断入出金或收益");return out;
    }
    public Map<String,Object> history(String id,String period,int page,int size,boolean admin){paging(page,size);TraderProfile p=profile(id,admin,false);Instant[] w=window(p,period);String where=SCOPE+" and x.traderId=:id and x.closedAt>=:from and x.closedAt<=:to";TypedQuery<TraderHistory> rows=query("from TraderHistory x"+where+" order by x.closedAt desc,x.recordId",TraderHistory.class);TypedQuery<Long> count=query("select count(x) from TraderHistory x"+where,Long.class);for(TypedQuery<?> q:Arrays.asList(rows,count)){q.setParameter("id",id);q.setParameter("from",w[0]);q.setParameter("to",w[1]);}List<Map<String,Object>> content=new ArrayList<>();for(TraderHistory h:rows.setFirstResult(page*size).setMaxResults(size).getResultList())content.add(historyView(h,admin));Map<String,Object> out=page(content,count.getSingleResult(),page,size);common(out,p,w,period);out.put("disclosure","历史记录·人工维护；仅按平仓时间排序，未提供的盈亏、数量和费用保持未知");return out;}
    private TraderEquity point(TraderProfile p,String pointId){uuid(pointId);List<TraderEquity> rows=query("from TraderEquity x"+SCOPE+" and x.traderId=:id and x.pointId=:point",TraderEquity.class).setParameter("id",p.getTraderId()).setParameter("point",pointId).getResultList();if(rows.isEmpty())throw missing();return rows.get(0);}
    private TraderHistory record(TraderProfile p,String recordId){uuid(recordId);List<TraderHistory> rows=query("from TraderHistory x"+SCOPE+" and x.traderId=:id and x.recordId=:record",TraderHistory.class).setParameter("id",p.getTraderId()).setParameter("record",recordId).getResultList();if(rows.isEmpty())throw missing();return rows.get(0);}
    private TraderEquity equityRow(TraderProfile p,TraderData.EquityInput d){if(d==null)throw bad("缺少曲线data");currency(d.currency,p.getCurrency());TraderEquity e=new TraderEquity();e.setPointAt(instant(d.pointAt,"pointAt"));inPeriod(e.getPointAt(),decode(p),"pointAt");e.setNetAsset(decimal(d.netAsset,true,0,"netAsset"));e.setCashFlow(decimal(d.cashFlow,false,-1,"cashFlow"));e.setCurrency(d.currency);e.setSourceNote(text(d.sourceNote,1000,false,"来源说明"));return e;}
    private TraderHistory historyRow(TraderProfile p,TraderData.HistoryInput d){if(d==null)throw bad("缺少历史data");currency(d.currency,p.getCurrency());TraderHistory h=new TraderHistory();h.setRecordKey(text(d.recordKey,80,true,"人工条目编号recordKey"));h.setClosedAt(instant(d.closedAt,"closedAt"));inPeriod(h.getClosedAt(),decode(p),"closedAt");h.setSymbol(text(d.symbol,40,true,"symbol"));if(!h.getSymbol().matches("[A-Z0-9][A-Z0-9./_-]{0,39}"))throw bad("symbol须大写品种代码");if(!Arrays.asList("LONG","SHORT").contains(d.direction))throw bad("direction须LONG/SHORT");h.setDirection(d.direction);h.setLeverage(decimal(d.leverage,false,1,"leverage"));h.setQuantity(decimal(d.quantity,false,1,"quantity"));h.setQuantityUnit(text(d.quantityUnit,16,h.getQuantity()!=null,"quantityUnit"));h.setPnl(decimal(d.pnl,false,-1,"pnl"));h.setFees(decimal(d.fees,false,0,"fees"));if(!Arrays.asList("BEFORE_FEES","AFTER_FEES","NOT_PROVIDED").contains(d.pnlBasis)||h.getPnl()!=null&&d.pnlBasis.equals("NOT_PROVIDED")||h.getPnl()==null&&!d.pnlBasis.equals("NOT_PROVIDED"))throw bad("盈亏提供时须明确税费口径，未提供时pnlBasis=NOT_PROVIDED");h.setPnlBasis(d.pnlBasis);h.setCurrency(d.currency);h.setSourceNote(text(d.sourceNote,1000,false,"来源说明"));h.setEvidenceNote(text(d.evidenceNote,1000,false,"内部证据记录"));return h;}
    private void duplicatePoint(TraderProfile p,TraderEquity e,String except){List<TraderEquity> rows=query("from TraderEquity x"+SCOPE+" and x.traderId=:id and x.pointAt=:time",TraderEquity.class).setParameter("id",p.getTraderId()).setParameter("time",e.getPointAt()).getResultList();if(rows.stream().anyMatch(x->!x.getPointId().equals(except)))throw bad("pointAt重复；请编辑原曲线点，不会覆盖现有值");}
    private void duplicateRecord(TraderProfile p,TraderHistory h,String except){List<TraderHistory> rows=query("from TraderHistory x"+SCOPE+" and x.traderId=:id and x.recordKey=:key",TraderHistory.class).setParameter("id",p.getTraderId()).setParameter("key",h.getRecordKey()).getResultList();if(rows.stream().anyMatch(x->!x.getRecordId().equals(except)))throw bad("recordKey重复；请编辑原历史记录，不会覆盖现有值");}
    private void limit(String entity,TraderProfile p,int added){long n=query("select count(x) from "+entity+" x"+SCOPE+" and x.traderId=:id",Long.class).setParameter("id",p.getTraderId()).getSingleResult();if(n+added>10000)throw bad("每个人物每类记录最多10000条");}
    private void persist(TraderProfile p,TraderEquity e){e.setEnvironment(environment());e.setTraderId(p.getTraderId());e.setPointId(UUID.randomUUID().toString());em.persist(e);}
    private void persist(TraderProfile p,TraderHistory h){h.setEnvironment(environment());h.setTraderId(p.getTraderId());h.setRecordId(UUID.randomUUID().toString());em.persist(h);}
    @Transactional public Map<String,Object> saveEquity(String id,String pointId,TraderData.EquityEdit input){CalendarService.actor();if(input==null)throw bad("缺少曲线输入");reason(input.reason);TraderProfile p=profile(id,true,true);version(p,input.rowVersion);TraderEquity validated=equityRow(p,input.data);duplicatePoint(p,validated,pointId);Map<String,Object> before=null;TraderEquity e;if(pointId==null){limit("TraderEquity",p,1);e=validated;persist(p,e);}else{e=point(p,pointId);before=equityView(e);e.setPointAt(validated.getPointAt());e.setNetAsset(validated.getNetAsset());e.setCashFlow(validated.getCashFlow());e.setCurrency(validated.getCurrency());e.setSourceNote(validated.getSourceNote());}touch(p,true);Map<String,Object> out=equityView(e);audit(p,e.getPointId(),pointId==null?"EQUITY_CREATE":"EQUITY_EDIT",input.reason,before,out);out.put("profile",view(p,true));return out;}
    @Transactional public Map<String,Object> saveHistory(String id,String recordId,TraderData.HistoryEdit input){CalendarService.actor();if(input==null)throw bad("缺少历史输入");reason(input.reason);TraderProfile p=profile(id,true,true);version(p,input.rowVersion);TraderHistory v=historyRow(p,input.data);duplicateRecord(p,v,recordId);Map<String,Object> before=null;TraderHistory h;if(recordId==null){limit("TraderHistory",p,1);h=v;persist(p,h);}else{h=record(p,recordId);before=historyView(h,true);h.setRecordKey(v.getRecordKey());h.setClosedAt(v.getClosedAt());h.setSymbol(v.getSymbol());h.setDirection(v.getDirection());h.setLeverage(v.getLeverage());h.setQuantity(v.getQuantity());h.setQuantityUnit(v.getQuantityUnit());h.setPnl(v.getPnl());h.setPnlBasis(v.getPnlBasis());h.setFees(v.getFees());h.setCurrency(v.getCurrency());h.setSourceNote(v.getSourceNote());h.setEvidenceNote(v.getEvidenceNote());}touch(p,true);Map<String,Object> out=historyView(h,true);audit(p,h.getRecordId(),recordId==null?"HISTORY_CREATE":"HISTORY_EDIT",input.reason,before,out);out.put("profile",view(p,true));return out;}
    @Transactional public Map<String,Object> remove(String id,String child,boolean equity,TraderData.Change input){CalendarService.actor();if(input==null)throw bad("缺少删除依据");reason(input.reason);TraderProfile p=profile(id,true,true);version(p,input.rowVersion);Object before;if(equity){TraderEquity e=point(p,child);before=equityView(e);em.remove(e);}else{TraderHistory h=record(p,child);before=historyView(h,true);em.remove(h);}touch(p,true);audit(p,child,equity?"EQUITY_DELETE":"HISTORY_DELETE",input.reason,before,null);return view(p,true);}
    public static class ImportFailure extends RuntimeException {public final List<Map<String,Object>> errors;ImportFailure(List<Map<String,Object>> errors){super("导入校验失败，整批未写入，现有数据未改变");this.errors=errors;}}
    @Transactional public Map<String,Object> importRows(String id,boolean equity,TraderData.Import input){CalendarService.actor();if(input==null||input.rows==null||input.rows.isEmpty()||input.rows.size()>500)throw bad("rows须1至500条");reason(input.reason);TraderProfile p=profile(id,true,true);version(p,input.rowVersion);limit(equity?"TraderEquity":"TraderHistory",p,input.rows.size());List<TraderEquity> points=new ArrayList<>();List<TraderHistory> history=new ArrayList<>();Set<String> keys=new HashSet<>();List<Map<String,Object>> errors=new ArrayList<>();
        for(int i=0;i<input.rows.size();i++){try{JsonNode row=input.rows.get(i);if(row==null||!row.isObject())throw bad("行须为JSON对象");Set<String> allowed=new HashSet<>(equity?Arrays.asList("pointAt","netAsset","cashFlow","currency","sourceNote"):Arrays.asList("recordKey","closedAt","symbol","direction","leverage","quantity","quantityUnit","pnl","pnlBasis","fees","currency","sourceNote","evidenceNote"));Iterator<String> fields=row.fieldNames();while(fields.hasNext()){String f=fields.next();if(!allowed.contains(f))throw bad("不支持字段："+f+"；不能导入私有订单或伪造核验标识");}
                if(equity){TraderEquity e=equityRow(p,json.treeToValue(row,TraderData.EquityInput.class));if(!keys.add(e.getPointAt().toString()))throw bad("批内pointAt重复");duplicatePoint(p,e,null);points.add(e);}else{TraderHistory h=historyRow(p,json.treeToValue(row,TraderData.HistoryInput.class));if(!keys.add(h.getRecordKey()))throw bad("批内recordKey重复");duplicateRecord(p,h,null);history.add(h);}
            }catch(Exception e){Map<String,Object> error=new LinkedHashMap<>();error.put("row",i+1);error.put("message",e instanceof ResponseStatusException?((ResponseStatusException)e).getReason():"日期或字段类型无效，数字须为十进制字符串");errors.add(error);}}
        if(!errors.isEmpty())throw new ImportFailure(errors);Map<String,Object> before=new LinkedHashMap<>();before.put("status",p.getStatus());before.put("rowVersion",p.getRowVersion());List<Map<String,Object>> inserted=new ArrayList<>();if(equity)for(TraderEquity e:points){persist(p,e);inserted.add(equityView(e));}else for(TraderHistory h:history){persist(p,h);inserted.add(historyView(h,true));}touch(p,true);Map<String,Object> out=new LinkedHashMap<>();out.put("inserted",inserted.size());out.put("rows",inserted);out.put("profile",view(p,true));audit(p,null,equity?"EQUITY_IMPORT":"HISTORY_IMPORT",input.reason,before,out);return out;
    }
    public Map<String,Object> template(String id,String kind){TraderProfile p=profile(id,true,false);if(!Arrays.asList("equity","history").contains(kind))throw bad("kind须equity/history");Map<String,Object> example=new LinkedHashMap<>();if(kind.equals("equity")){example.put("pointAt",decode(p).statisticStart.toString());example.put("netAsset",null);example.put("cashFlow",null);}else{example.put("recordKey",null);example.put("closedAt",decode(p).statisticEnd.toString());example.put("symbol",null);example.put("direction",null);example.put("leverage",null);example.put("quantity",null);example.put("quantityUnit",null);example.put("pnl",null);example.put("pnlBasis","NOT_PROVIDED");example.put("fees",null);example.put("evidenceNote",null);}example.put("currency",p.getCurrency());example.put("sourceNote",null);Map<String,Object> out=new LinkedHashMap<>();out.put("kind",kind);out.put("rowVersion",p.getRowVersion());out.put("reason","");out.put("rows",Collections.singletonList(example));out.put("instructions","填写真实获授权的人工展示记录，替换null必填项；日期用UTC，数字用字符串，单位与人物一致。recordKey为人工编号而非私有订单号。最多500条，重复或任何错误整批不写。导入会使已发布人物回草稿。");return out;}
    public List<TraderAudit> audits(String id,int page){paging(page,50);if(id!=null)profile(id,true,false);String where=SCOPE+(id==null?"":" and x.traderId=:id");TypedQuery<TraderAudit> q=query("from TraderAudit x"+where+" order by x.id desc",TraderAudit.class);if(id!=null)q.setParameter("id",id);return q.setFirstResult(page*50).setMaxResults(50).getResultList();}
}
