package com.gtcfesk.exchange.control;

import com.fasterxml.jackson.databind.*;
import com.gtcfesk.exchange.support.SupportService;
import com.gtcfesk.exchange.tenant.TenantContext;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;
import org.springframework.security.access.AccessDeniedException;
import java.nio.file.*;
import java.nio.channels.FileChannel;
import java.nio.ByteBuffer;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.*;
import java.io.*;
import java.security.*;

/** Restartable fixed-size exports. Only metadata lives in the control plane; private bytes never enter public uploads. */
@Service @RequiredArgsConstructor
public class ChatArchiveService {
    private final JdbcTemplate jdbc;
    private final PlatformTransactionManager manager;
    private final ControlAuditService audit;
    private final ObjectMapper json;
    private final OperationalIssueService issues;
    @org.springframework.beans.factory.annotation.Value("${control.retention.archive-directory:}") private String archiveDirectory;
    @org.springframework.beans.factory.annotation.Value("${control.retention.archive-max-bytes:2147483648}") private long maxBytes=2147483648L;
    private static final int CHUNK_ROWS=100,MAX_CHUNKS=10000;
    private static final long MAX_IMAGE_BYTES=10L*1024*1024,MAX_JSON_BYTES=16L*1024*1024;
    private static final String TABLE="control_chat_archive_job";
    private <T> T tx(java.util.function.Supplier<T> work){return new TransactionTemplate(manager).execute(s->work.get());}
    private static long number(Map<String,Object> row,String key){return ((Number)row.get(key)).longValue();}
    private static Map<String,Object> lower(Map<String,Object> input){Map<String,Object> result=new LinkedHashMap<>();input.forEach((key,value)->result.put(key.toLowerCase(Locale.ROOT),value));return result;}
    private static boolean flag(Object value){return Boolean.TRUE.equals(value)||value instanceof Number&&((Number)value).intValue()==1;}
    private static void id(String id){if(id==null||!id.matches("[a-f0-9-]{36}")||!UUID.fromString(id).toString().equals(id))throw new IllegalArgumentException("归档任务编号无效");}
    private Map<String,Object> job(long tenant,String id,boolean lock){id(id);List<Map<String,Object>> rows=jdbc.queryForList("SELECT * FROM "+TABLE+" WHERE tenant_id=? AND id=?"+(lock?" FOR UPDATE":""),tenant,id);if(rows.size()!=1)throw new IllegalArgumentException("归档任务不存在");return lower(rows.get(0));}
    private void owner(Map<String,Object> job){Long actor=issues.actor();if(job.get("actor_id")!=null&&!actor.equals(((Number)job.get("actor_id")).longValue()))throw new AccessDeniedException("归档任务不属于当前审核人");}
    private Path root(){if(archiveDirectory==null||archiveDirectory.codePoints().allMatch(Character::isWhitespace)||maxBytes<MAX_IMAGE_BYTES)throw new IllegalStateException("未配置受限归档目录或容量预算");Path root=Paths.get(archiveDirectory).toAbsolutePath().normalize();try{if(!Files.isDirectory(root,LinkOption.NOFOLLOW_LINKS)||Files.isSymbolicLink(root)||!root.toRealPath().equals(root))throw new IllegalStateException("归档根目录必须预先创建且不能含符号链接");return root;}catch(IOException e){throw new IllegalStateException("归档目录不可用",e);}}
    private Path directory(long tenant,String id){id(id);Path base=root(),parent=base.resolve("tenant-"+tenant),directory=parent.resolve("job-"+id);try{Files.createDirectories(parent);if(Files.isSymbolicLink(parent)||!parent.toRealPath().startsWith(base))throw new IllegalStateException("归档租户目录越界");Files.createDirectories(directory);if(Files.isSymbolicLink(directory)||!directory.toRealPath().startsWith(parent.toRealPath()))throw new IllegalStateException("归档任务目录越界");return directory;}catch(IOException e){throw new IllegalStateException("归档目录不可用",e);}}
    private byte[] encode(Object value){try{return json.writeValueAsBytes(value);}catch(IOException e){throw new IllegalStateException("归档序列化失败",e);}}
    static Object archiveValue(Object value){
        // MySQL Connector/J returns LocalDateTime for DATETIME(6); the platform stores these columns in UTC.
        if(value instanceof Timestamp)return ((Timestamp)value).toInstant().toString();
        if(value instanceof java.time.LocalDateTime)return ((java.time.LocalDateTime)value).toInstant(java.time.ZoneOffset.UTC).toString();
        return value;
    }
    private Map<String,Object> archiveRow(Map<String,Object> raw){Map<String,Object> row=lower(raw);row.replaceAll((key,value)->archiveValue(value));return row;}
    private String digest(Path file){try(InputStream input=Files.newInputStream(file)){MessageDigest sha=MessageDigest.getInstance("SHA-256");byte[] buffer=new byte[65536];int n;while((n=input.read(buffer))!=-1)sha.update(buffer,0,n);StringBuilder hex=new StringBuilder();for(byte b:sha.digest())hex.append(String.format("%02x",b));return hex.toString();}catch(IOException|NoSuchAlgorithmException e){throw new IllegalStateException("归档哈希校验失败",e);}}
    private void publish(Path file,byte[] bytes){try{if(Files.exists(file,LinkOption.NOFOLLOW_LINKS)){if(Files.isSymbolicLink(file)||!digest(file).equals(SupportService.sha256(bytes)))throw new IllegalStateException("已发布归档不可覆盖");return;}if(Files.getFileStore(file.getParent()).getUsableSpace()<bytes.length+16L*1024*1024)throw new IllegalStateException("归档存储余量不足");Path temporary=Files.createTempFile(file.getParent(),".archive-",".tmp");try{try(FileChannel channel=FileChannel.open(temporary,StandardOpenOption.WRITE)){ByteBuffer buffer=ByteBuffer.wrap(bytes);while(buffer.hasRemaining())channel.write(buffer);channel.force(true);}Files.move(temporary,file,StandardCopyOption.ATOMIC_MOVE);}finally{Files.deleteIfExists(temporary);}}catch(IOException e){throw new IllegalStateException("归档发布失败，源会话保留",e);}}
    private JsonNode read(Path file,long limit){try{if(Files.isSymbolicLink(file)||!Files.isRegularFile(file,LinkOption.NOFOLLOW_LINKS)||Files.size(file)>limit)throw new IllegalStateException("归档文件缺失、越界或超限");return json.readTree(Files.readAllBytes(file));}catch(IOException e){throw new IllegalStateException("归档读取失败",e);}}
    public Map<String,Object> start(long tenant,long conversation,String requestKey,String reason){Long actor=issues.actor();TenantManagementService.reason(reason);id(requestKey);if(tenant<=0||conversation<=0||reason.length()>512)throw new IllegalArgumentException("归档参数无效");return tx(()->startInternal(tenant,conversation,requestKey,reason,actor));}
    private Map<String,Object> startInternal(long tenant,long conversation,String requestKey,String reason,Long actor){
        if(jdbc.queryForList("SELECT id FROM tenant WHERE id=? FOR UPDATE",tenant).size()!=1)throw new IllegalArgumentException("租户不存在");
        String owner=actor==null?"SYSTEM":"CONTROL:"+actor,requestHash=SupportService.sha256(encode(Arrays.asList(tenant,conversation,owner,reason)));
        List<Map<String,Object>> prior=jdbc.queryForList("SELECT * FROM "+TABLE+" WHERE tenant_id=? AND conversation_id=? AND owner_key=? AND request_key=?",tenant,conversation,owner,requestKey);
        if(!prior.isEmpty()){Map<String,Object> existing=lower(prior.get(0));if(!requestHash.equals(existing.get("request_hash")))throw new org.springframework.web.server.ResponseStatusException(org.springframework.http.HttpStatus.CONFLICT,"归档重试编号已用于其他原因");return projection(existing);}
        root();if(jdbc.queryForObject("SELECT COUNT(*) FROM "+TABLE+" WHERE tenant_id=? AND state IN ('QUEUED','RUNNING')",Long.class,tenant)>=100)throw new IllegalStateException("归档待处理任务达到100个上限");
        List<Map<String,Object>> chats=jdbc.queryForList("SELECT * FROM support_conversation WHERE tenant_id=? AND id=? FOR UPDATE",tenant,conversation);if(chats.size()!=1)throw new IllegalArgumentException("会话不存在");Map<String,Object> snapshot=archiveRow(chats.get(0));
        Map<String,Object> bounds=lower(jdbc.queryForMap("SELECT COUNT(*) AS total,COALESCE(MAX(id),0) AS last_id FROM support_message WHERE tenant_id=? AND conversation_id=?",tenant,conversation));long total=number(bounds,"total"),last=number(bounds,"last_id");if(total>(long)CHUNK_ROWS*MAX_CHUNKS)throw new IllegalStateException("单任务超过有界100万条预算，源会话保留");
        String id=UUID.randomUUID().toString();byte[] metadata=encode(com.gtcfesk.exchange.common.ImmutableMaps.of("format","retention-chunks-v2","jobId",id,"tenantId",tenant,"conversation",snapshot,"expectedMessages",total,"endId",last));String metadataHash=SupportService.sha256(metadata);publish(directory(tenant,id).resolve("job.json"),metadata);
        jdbc.update("INSERT INTO "+TABLE+"(id,tenant_id,conversation_id,actor_id,owner_key,request_key,request_hash,reason,state,end_id,expected_messages,snapshot_sha256,expected_last_hash,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,'QUEUED',?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)",id,tenant,conversation,actor,owner,requestKey,requestHash,reason,last,total,metadataHash,Objects.toString(snapshot.get("last_hash"),""));
        audit.record(actor,tenant,null,"CHAT_ARCHIVE_START",id,"SUCCESS","conversation="+conversation+";messages="+total,reason);return projection(job(tenant,id,false));
    }
    private Map<String,Object> projection(Map<String,Object> row){Map<String,Object> result=new LinkedHashMap<>();for(String key:Arrays.asList("id","tenant_id","conversation_id","actor_id","state","expected_messages","processed_messages","cursor_id","chunk_sequence","attachment_bytes","final_manifest_sha256","failure_type","created_at","updated_at"))result.put(key,row.get(key));return result;}
    public Map<String,Object> status(long tenant,String id){issues.actor();Map<String,Object> job=job(tenant,id,false);owner(job);return projection(job);}
    public List<Map<String,Object>> list(long tenant,long conversation){Long actor=issues.actor();if(tenant<=0||conversation<=0)throw new IllegalArgumentException("明确租户和会话");List<Map<String,Object>> result=new ArrayList<>();for(Map<String,Object> row:jdbc.queryForList("SELECT * FROM "+TABLE+" WHERE tenant_id=? AND conversation_id=? AND (actor_id=? OR actor_id IS NULL) ORDER BY created_at DESC,id DESC LIMIT 30",tenant,conversation,actor))result.add(projection(lower(row)));return result;}
    public Map<String,Object> retry(long tenant,String id,String reason){issues.actor();TenantManagementService.reason(reason);return tx(()->{Map<String,Object> row=job(tenant,id,true);owner(row);if(!"FAILED".equals(row.get("state")))throw new IllegalArgumentException("仅失败任务可受控重试");jdbc.update("UPDATE "+TABLE+" SET state='QUEUED',failure_type=NULL,updated_at=CURRENT_TIMESTAMP WHERE tenant_id=? AND id=?",tenant,id);audit.record(issues.actor(),tenant,null,"CHAT_ARCHIVE_RETRY",id,"SUCCESS","cursor="+number(row,"cursor_id"),reason);return projection(job(tenant,id,false));});}
    @Scheduled(fixedDelayString="${control.retention.archive-poll-ms:2000}")
    public void run(){if(TenantContext.currentTenantId()!=null||org.springframework.security.core.context.SecurityContextHolder.getContext().getAuthentication()!=null)throw new IllegalStateException("归档工作器不可复用请求身份");for(Map<String,Object> input:jdbc.queryForList("SELECT id,tenant_id FROM "+TABLE+" WHERE state IN ('QUEUED','RUNNING') ORDER BY updated_at,id LIMIT 3")){Map<String,Object> row=lower(input);long tenant=number(row,"tenant_id");String id=row.get("id").toString();try{process(tenant,id);}catch(RuntimeException failure){try{tx(()->{jdbc.update("UPDATE "+TABLE+" SET state='FAILED',failure_type=?,updated_at=CURRENT_TIMESTAMP WHERE tenant_id=? AND id=? AND state<>'COMPLETE'",failure.getClass().getSimpleName(),tenant,id);return null;});}finally{issues.failed(tenant,"chat-archive",failure);}}}}
    /** One bounded chunk per transaction; a restart replays the same content-addressed files before advancing. */
    void process(long tenant,String id){if(TenantContext.currentTenantId()!=null||org.springframework.security.core.context.SecurityContextHolder.getContext().getAuthentication()!=null)throw new IllegalStateException("归档工作器不能继承请求身份");tx(()->{Map<String,Object> job=job(tenant,id,true);if(!Arrays.asList("QUEUED","RUNNING").contains(job.get("state")))return null;Path directory=directory(tenant,id);if(!digest(directory.resolve("job.json")).equals(job.get("snapshot_sha256")))throw new IllegalStateException("任务快照损坏");JsonNode metadata=read(directory.resolve("job.json"),MAX_JSON_BYTES);if(metadata.path("tenantId").asLong()!=tenant||metadata.path("conversation").path("id").asLong()!=number(job,"conversation_id"))throw new IllegalStateException("任务快照归属无效");
        long conversation=number(job,"conversation_id"),cursor=number(job,"cursor_id"),processed=number(job,"processed_messages"),bytes=number(job,"attachment_bytes");String previous=Objects.toString(job.get("chain_hash"),"");int sequence=(int)number(job,"chunk_sequence");
        List<Map<String,Object>> rows=jdbc.queryForList("SELECT * FROM support_message WHERE tenant_id=? AND conversation_id=? AND id>? AND id<=? ORDER BY id LIMIT 100",tenant,conversation,cursor,number(job,"end_id"));
        if(rows.isEmpty()){if(processed!=number(job,"expected_messages")||!previous.equals(job.get("expected_last_hash"))||cursor!=number(job,"end_id"))throw new IllegalStateException("会话计数或lastHash不匹配，源会话保留");seal(job,metadata,directory);return null;}
        List<Map<String,Object>> messages=new ArrayList<>(),attachments=new ArrayList<>();String boundary=previous;long first=0;
        for(Map<String,Object> raw:rows){Map<String,Object> message=archiveRow(raw);long mid=number(message,"id");if(first==0)first=mid;if(number(message,"tenant_id")!=tenant||number(message,"conversation_id")!=conversation||mid<=cursor)throw new IllegalStateException("消息范围无效");String expected=SupportService.sha256(encode(Arrays.asList(conversation,message.get("sender"),number(message,"sender_id"),message.get("sender_name"),message.get("request_id"),message.get("text"),message.get("image_hash"),message.get("created_at"),previous)));if(!previous.equals(message.get("previous_hash"))||!expected.equals(message.get("hash")))throw new IllegalStateException("消息链无效，源会话保留");previous=expected;cursor=mid;messages.add(message);
            if(flag(message.get("image"))){Long size=jdbc.queryForObject("SELECT OCTET_LENGTH(content) FROM support_attachment WHERE tenant_id=? AND message_id=?",Long.class,tenant,mid);if(size==null||size>MAX_IMAGE_BYTES||size<8||Math.addExact(bytes,size)>maxBytes)throw new IllegalStateException("附件缺失或容量超限，源会话保留");Map<String,Object> attachment=lower(jdbc.queryForMap("SELECT * FROM support_attachment WHERE tenant_id=? AND message_id=?",tenant,mid));byte[] binary=(byte[])attachment.remove("content");String hash=SupportService.sha256(binary);if(binary.length!=size||!hash.equals(message.get("image_hash"))||!png(binary))throw new IllegalStateException("附件完整性无效，源会话保留");String name="image-"+mid+"-"+hash+".png";publish(directory.resolve(name),binary);attachments.add(com.gtcfesk.exchange.common.ImmutableMaps.of("row",archiveRow(attachment),"file",name,"sha256",hash,"bytes",size));bytes+=size;}
            else if(jdbc.queryForObject("SELECT COUNT(*) FROM support_attachment WHERE tenant_id=? AND message_id=?",Long.class,tenant,mid)!=0)throw new IllegalStateException("非图片消息包含附件，源会话保留");
        }
        sequence++;Map<String,Object> chunk=new LinkedHashMap<>();chunk.put("format","retention-chunk-v2");chunk.put("jobId",id);chunk.put("tenantId",tenant);chunk.put("conversationId",conversation);chunk.put("sequence",sequence);chunk.put("afterId",number(job,"cursor_id"));chunk.put("firstId",first);chunk.put("lastId",cursor);chunk.put("previousHash",boundary);chunk.put("lastHash",previous);chunk.put("messages",messages);chunk.put("attachments",attachments);byte[] encoded=encode(chunk);if(encoded.length>MAX_JSON_BYTES)throw new IllegalStateException("归档块超过16MB，源会话保留");String hash=SupportService.sha256(encoded),name=String.format(Locale.ROOT,"chunk-%06d-%s.json",sequence,hash);publish(directory.resolve(name),encoded);
        jdbc.update("UPDATE "+TABLE+" SET state='RUNNING',cursor_id=?,processed_messages=?,chunk_sequence=?,attachment_bytes=?,chain_hash=?,updated_at=CURRENT_TIMESTAMP WHERE tenant_id=? AND id=?",cursor,processed+messages.size(),sequence,bytes,previous,tenant,id);audit.record(null,tenant,null,"CHAT_ARCHIVE_CHUNK",id,"SUCCESS","sequence="+sequence+";sha256="+hash+";initiatedBy="+Objects.toString(job.get("actor_id"),"SYSTEM"),"SYSTEM bounded archive worker");return null;});}
    private static boolean png(byte[] b){return b.length>=8&&b[0]==(byte)137&&b[1]==80&&b[2]==78&&b[3]==71&&b[4]==13&&b[5]==10&&b[6]==26&&b[7]==10;}
    private Path chunkFile(Path directory,int sequence){String prefix=String.format(Locale.ROOT,"chunk-%06d-",sequence);try(DirectoryStream<Path> files=Files.newDirectoryStream(directory,prefix+"*.json")){Path found=null;for(Path file:files){if(found!=null)throw new IllegalStateException("块序列存在冲突，不覆盖证据");found=file;}if(found==null)throw new IllegalStateException("归档块缺失");return found;}catch(IOException e){throw new IllegalStateException("归档读取失败",e);}}
    private void seal(Map<String,Object> job,JsonNode metadata,Path directory){List<Map<String,Object>> chunks=new ArrayList<>();String previous="";long after=0,count=0,bytes=0;for(int seq=1;seq<=number(job,"chunk_sequence");seq++){Path file=chunkFile(directory,seq);String hash=digest(file);if(!file.getFileName().toString().endsWith(hash+".json"))throw new IllegalStateException("归档块哈希不匹配");JsonNode chunk=read(file,MAX_JSON_BYTES);if(chunk.path("sequence").asInt()!=seq||chunk.path("tenantId").asLong()!=number(job,"tenant_id")||!job.get("id").equals(chunk.path("jobId").asText())||chunk.path("afterId").asLong()!=after||!previous.equals(chunk.path("previousHash").asText()))throw new IllegalStateException("归档块顺序或边界无效");previous=chunk.path("lastHash").asText();after=chunk.path("lastId").asLong();count+=chunk.path("messages").size();for(JsonNode image:chunk.path("attachments")){Path attachment=directory.resolve(image.path("file").asText());checkFile(attachment,image.path("sha256").asText(),image.path("bytes").asLong(),MAX_IMAGE_BYTES);bytes+=image.path("bytes").asLong();}chunks.add(com.gtcfesk.exchange.common.ImmutableMaps.of("file",file.getFileName().toString(),"sha256",hash,"sequence",seq,"messages",chunk.path("messages").size(),"firstId",chunk.path("firstId").asLong(),"lastId",after,"previousHash",chunk.path("previousHash").asText(),"lastHash",previous));}
        if(count!=number(job,"expected_messages")||bytes!=number(job,"attachment_bytes")||after!=number(job,"end_id")||!previous.equals(job.get("expected_last_hash")))throw new IllegalStateException("归档总量或链末不匹配");Map<String,Object> manifest=new LinkedHashMap<>();manifest.put("format","retention-chunks-v2");manifest.put("jobId",job.get("id"));manifest.put("tenantId",job.get("tenant_id"));manifest.put("conversation",metadata.path("conversation"));manifest.put("snapshotSha256",job.get("snapshot_sha256"));manifest.put("messages",count);manifest.put("attachmentBytes",bytes);manifest.put("lastId",after);manifest.put("lastHash",previous);manifest.put("chunks",chunks);byte[] encoded=encode(manifest);if(encoded.length>MAX_JSON_BYTES)throw new IllegalStateException("manifest超出有界16MB，源会话保留");String hash=SupportService.sha256(encoded);publish(directory.resolve("manifest-"+hash+".json"),encoded);jdbc.update("UPDATE "+TABLE+" SET state='COMPLETE',final_manifest_sha256=?,updated_at=CURRENT_TIMESTAMP WHERE tenant_id=? AND id=?",hash,number(job,"tenant_id"),job.get("id"));audit.record(null,number(job,"tenant_id"),null,"CHAT_ARCHIVE_COMPLETE",job.get("id").toString(),"SUCCESS","manifest="+hash+";messages="+count,"SYSTEM completed archive; no chat deletion");}

    /** Internal retention path: no authority substitution, no cleanup before complete bounded revalidation. */
    String retentionArchive(long tenant,long conversation,Long actor,String reason){
        if(actor==null){if(TenantContext.currentTenantId()!=null||org.springframework.security.core.context.SecurityContextHolder.getContext().getAuthentication()!=null)throw new IllegalStateException("SYSTEM留存任务不能继承请求身份");}
        else if(!actor.equals(issues.actor()))throw new AccessDeniedException("留存审核人不匹配");
        return tx(()->{
            List<Map<String,Object>> current=jdbc.queryForList("SELECT * FROM support_conversation WHERE tenant_id=? AND id=? AND status='CLOSED' AND legal_hold=0 FOR UPDATE",tenant,conversation);
            if(current.size()!=1)return null;
            JsonNode snapshot=tree(archiveRow(current.get(0)));Map<String,Object> selected=null;JsonNode metadata=null;
            for(Map<String,Object> input:jdbc.queryForList("SELECT * FROM "+TABLE+" WHERE tenant_id=? AND conversation_id=? ORDER BY created_at DESC,id DESC LIMIT 30",tenant,conversation)){
                Map<String,Object> candidate=lower(input);Path file=directory(tenant,candidate.get("id").toString()).resolve("job.json");
                if(!digest(file).equals(candidate.get("snapshot_sha256")))throw new IllegalStateException("留存任务快照损坏");JsonNode value=read(file,MAX_JSON_BYTES);
                if(value.path("conversation").equals(snapshot)){selected=candidate;metadata=value;break;}
            }
            if(selected==null){String key=UUID.randomUUID().toString();startInternal(tenant,conversation,key,reason,actor);return null;}
            if(!"COMPLETE".equals(selected.get("state")))return null;
            String id=selected.get("id").toString();Path dir=directory(tenant,id),manifestFile=dir.resolve("manifest-"+selected.get("final_manifest_sha256")+".json");
            if(!digest(manifestFile).equals(selected.get("final_manifest_sha256")))throw new IllegalStateException("留存manifest损坏");JsonNode manifest=read(manifestFile,MAX_JSON_BYTES);
            if(!id.equals(manifest.path("jobId").asText())||manifest.path("tenantId").asLong()!=tenant||!manifest.path("conversation").equals(snapshot)||!manifest.path("conversation").equals(metadata.path("conversation")))throw new IllegalStateException("留存源会话已经变化");
            long cursor=0,total=0,bytes=0,attachmentCount=0;String previous="";int sequence=0;
            for(JsonNode reference:manifest.path("chunks")){
                sequence++;Path file=chunkFile(dir,sequence);if(!file.getFileName().toString().equals(reference.path("file").asText())||!digest(file).equals(reference.path("sha256").asText()))throw new IllegalStateException("留存归档块损坏");JsonNode chunk=read(file,MAX_JSON_BYTES);
                if(!id.equals(chunk.path("jobId").asText())||chunk.path("tenantId").asLong()!=tenant||chunk.path("conversationId").asLong()!=conversation||chunk.path("sequence").asInt()!=sequence||reference.path("sequence").asInt()!=sequence||chunk.path("afterId").asLong()!=cursor||!chunk.path("previousHash").asText().equals(previous)||!reference.path("previousHash").asText().equals(previous)||!chunk.path("messages").isArray()||chunk.path("messages").size()<1||chunk.path("messages").size()>CHUNK_ROWS||reference.path("messages").asInt()!=chunk.path("messages").size())throw new IllegalStateException("留存归档块边界无效");
                Map<Long,JsonNode> images=new HashMap<>();long first=0;
                for(JsonNode m:chunk.path("messages")){
                    long mid=m.path("id").asLong();if(mid<=cursor||m.path("tenant_id").asLong()!=tenant||m.path("conversation_id").asLong()!=conversation)throw new IllegalStateException("留存消息归属无效");if(first==0)first=mid;
                    List<Map<String,Object>> rows=jdbc.queryForList("SELECT * FROM support_message WHERE tenant_id=? AND conversation_id=? AND id=?",tenant,conversation,mid);
                    if(rows.size()!=1||!tree(archiveRow(rows.get(0))).equals(m))throw new IllegalStateException("留存消息在归档后变化");
                    String expected=SupportService.sha256(encode(Arrays.asList(conversation,m.path("sender").asText(),m.path("sender_id").asLong(),m.path("sender_name").asText(),m.path("request_id").asText(),m.path("text").asText(),m.path("image_hash").asText(),m.path("created_at").asText(),previous)));
                    if(!previous.equals(m.path("previous_hash").asText())||!expected.equals(m.path("hash").asText()))throw new IllegalStateException("留存完整消息链无效");previous=expected;cursor=mid;total++;if(m.path("image").asBoolean())images.put(mid,m);
                }
                for(JsonNode image:chunk.path("attachments")){
                    long mid=image.path("row").path("message_id").asLong();JsonNode m=images.remove(mid);String hash=image.path("sha256").asText(),name="image-"+mid+"-"+hash+".png";long size=image.path("bytes").asLong();
                    if(m==null||image.path("row").path("tenant_id").asLong()!=tenant||!hash.matches("[a-f0-9]{64}")||!hash.equals(m.path("image_hash").asText())||!name.equals(image.path("file").asText())||size<8)throw new IllegalStateException("留存附件归属无效");checkFile(dir.resolve(name),hash,size,MAX_IMAGE_BYTES);
                    Long actual=jdbc.queryForObject("SELECT OCTET_LENGTH(content) FROM support_attachment WHERE tenant_id=? AND message_id=?",Long.class,tenant,mid);if(actual==null||actual!=size||actual>MAX_IMAGE_BYTES)throw new IllegalStateException("留存附件源字节变化");Map<String,Object> row=lower(jdbc.queryForMap("SELECT * FROM support_attachment WHERE tenant_id=? AND message_id=?",tenant,mid));byte[] content=(byte[])row.remove("content");
                    if(!hash.equals(SupportService.sha256(content))||!tree(archiveRow(row)).equals(image.path("row")))throw new IllegalStateException("留存附件字段或字节变化");bytes+=size;attachmentCount++;
                }
                if(!images.isEmpty()||first!=reference.path("firstId").asLong()||cursor!=reference.path("lastId").asLong()||cursor!=chunk.path("lastId").asLong()||!previous.equals(reference.path("lastHash").asText())||!previous.equals(chunk.path("lastHash").asText()))throw new IllegalStateException("留存块末或附件完整性无效");
            }
            if(total!=number(selected,"expected_messages")||total!=manifest.path("messages").asLong()||cursor!=number(selected,"end_id")||cursor!=manifest.path("lastId").asLong()||bytes!=number(selected,"attachment_bytes")||bytes!=manifest.path("attachmentBytes").asLong()||!previous.equals(selected.get("expected_last_hash"))||!previous.equals(manifest.path("lastHash").asText())||!previous.equals(snapshot.path("last_hash").asText())||jdbc.queryForObject("SELECT COUNT(*) FROM support_message WHERE tenant_id=? AND conversation_id=?",Long.class,tenant,conversation)!=total||jdbc.queryForObject("SELECT COUNT(*) FROM support_attachment a JOIN support_message m ON m.tenant_id=a.tenant_id AND m.id=a.message_id WHERE m.tenant_id=? AND m.conversation_id=?",Long.class,tenant,conversation)!=attachmentCount)throw new IllegalStateException("留存完整归档范围变化");
            return "tenant-"+tenant+"/job-"+id+"/"+manifestFile.getFileName();
        });
    }
    private JsonNode tree(Object value){try{return json.readTree(encode(value));}catch(IOException e){throw new IllegalStateException("归档字段比对失败",e);}}

    private void checkFile(Path file,String hash,long size,long limit){try{if(file.getFileName().toString().contains("/")||Files.isSymbolicLink(file)||!Files.isRegularFile(file,LinkOption.NOFOLLOW_LINKS)||Files.size(file)!=size||size>limit||!digest(file).equals(hash))throw new IllegalStateException("归档文件大小或哈希不匹配");}catch(IOException e){throw new IllegalStateException("归档文件不可用",e);}}
    public Path download(long tenant,String id,String name){
        issues.actor();Map<String,Object> job=job(tenant,id,false);owner(job);if(!"COMPLETE".equals(job.get("state")))throw new IllegalArgumentException("归档尚未完整完成");
        if(name==null||!name.matches("(?:manifest-[a-f0-9]{64}[.]json|chunk-[0-9]{6}-[a-f0-9]{64}[.]json|image-[1-9][0-9]*-[a-f0-9]{64}[.]png)"))throw new IllegalArgumentException("归档下载文件名无效");
        Path directory=directory(tenant,id),manifestFile=directory.resolve("manifest-"+job.get("final_manifest_sha256")+".json");if(!digest(manifestFile).equals(job.get("final_manifest_sha256")))throw new IllegalStateException("归档manifest哈希不匹配");JsonNode manifest=read(manifestFile,MAX_JSON_BYTES);
        if(manifest.path("tenantId").asLong()!=tenant||!id.equals(manifest.path("jobId").asText()))throw new IllegalStateException("归档manifest归属无效");
        String hash=null;long size=-1,limit=MAX_JSON_BYTES;
        if(name.equals(manifestFile.getFileName().toString())){hash=job.get("final_manifest_sha256").toString();try{size=Files.size(manifestFile);}catch(IOException e){throw new IllegalStateException(e);}}
        else for(JsonNode reference:manifest.path("chunks")){
            if(name.equals(reference.path("file").asText())){hash=reference.path("sha256").asText();try{size=Files.size(directory.resolve(name));}catch(IOException e){throw new IllegalStateException(e);}break;}
            if(name.startsWith("image-")){long message=Long.parseLong(name.split("-")[1]);if(message<reference.path("firstId").asLong()||message>reference.path("lastId").asLong())continue;Path chunkFile=directory.resolve(reference.path("file").asText());if(!digest(chunkFile).equals(reference.path("sha256").asText()))throw new IllegalStateException("归档块损坏");for(JsonNode image:read(chunkFile,MAX_JSON_BYTES).path("attachments"))if(name.equals(image.path("file").asText())){hash=image.path("sha256").asText();size=image.path("bytes").asLong();limit=MAX_IMAGE_BYTES;break;}}
        }
        if(hash==null||size<0)throw new IllegalArgumentException("文件未被最终manifest完整覆盖");Path file=directory.resolve(name);checkFile(file,hash,size,limit);audit.record(issues.actor(),tenant,null,"CHAT_ARCHIVE_DOWNLOAD",id,"SUCCESS","file="+name,null);return file;
    }
}
