package com.gtcfesk.exchange.insights.news;
import com.fasterxml.jackson.databind.ObjectMapper;import com.gtcfesk.exchange.simulation.SimulationEnvironment;
import org.springframework.stereotype.Service;import org.springframework.beans.factory.annotation.Value;
import org.springframework.transaction.*;import org.springframework.transaction.support.TransactionTemplate;
import javax.annotation.PostConstruct;import javax.persistence.*;
import java.net.*;import java.io.*;import java.time.*;import java.time.format.*;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.util.*;
@Service
public class NewsSync {
    @PersistenceContext private EntityManager em;
    private final TransactionTemplate tx;private final ObjectMapper json;private final SimulationEnvironment simulation;
    @Value("${news.sync.enabled:false}") private boolean enabled;
    @Value("${news.gdelt.enabled:false}") private boolean gdelt;
    @Value("${news.newsdata.key:${NEWSDATA_API_KEY:}}") private String key;
    @Value("${news.newsdata.license-approved:false}") private boolean newsdataLicense;
    public NewsSync(PlatformTransactionManager manager,ObjectMapper json,SimulationEnvironment simulation){this.tx=new TransactionTemplate(manager);tx.setPropagationBehavior(TransactionDefinition.PROPAGATION_REQUIRES_NEW);this.json=json;this.simulation=simulation;}
    public String environment(){return simulation.enabled()?"DEMO":"REAL";}
    public boolean enabled(){return enabled;}
    public boolean configured(String source){return NewsCatalog.official(source)||source.equals("GDELT")&&gdelt||source.equals("NEWSDATA")&&key!=null&&!key.trim().isEmpty()&&newsdataLicense;}
    public String id(String source){return environment()+":"+NewsCatalog.check(source);}
    @PostConstruct public void initialize(){tx.execute(s->{for(String source:NewsCatalog.URLS.keySet())if(em.find(NewsFeed.class,id(source))==null){NewsFeed r=new NewsFeed();r.setId(id(source));r.setEnvironment(environment());r.setSourceId(source);em.persist(r);}return null;});}
    public Map<String,Object> status(String source){return tx.execute(s->{NewsFeed r=em.find(NewsFeed.class,id(source));Map<String,Object> m=new LinkedHashMap<>();m.put("sourceId",source);m.put("name",NewsCatalog.NAMES.get(source));m.put("feedUrl",NewsCatalog.URLS.get(source));m.put("licenseUrl",NewsCatalog.LICENSES.get(source));m.put("licenseScope",source.equals("ECB")?"UNSIGNED_OFFICIAL_PRESS_HEADLINE_ONLY; NO_FRAMING; FREE_ORIGIN_NOTICE":NewsCatalog.official(source)?"OFFICIAL_RSS; ATTRIBUTION; THIRD_PARTY_EXCEPTION":"HEADLINE_INDEX_ONLY; PUBLISHER_RIGHTS_RETAINED; ACCOUNT_REVIEW_REQUIRED");m.put("configured",configured(source));m.put("status",configured(source)?r.getStatus():"UNCONFIGURED");m.put("httpStatus",r.getHttpStatus());m.put("lastAttempt",r.getLastAttempt());m.put("lastSuccess",r.getLastSuccess());m.put("contentAsOf",r.getContentAsOf());m.put("nextAttempt",r.getNextAttempt());m.put("itemCount",r.getItemCount());m.put("skippedCount",r.getSkippedCount());m.put("requestsToday",r.getRequestsToday());m.put("budgetDate",r.getBudgetDate());m.put("dailyBudget",NewsCatalog.budget(source));m.put("minimumIntervalSeconds",NewsCatalog.interval(source));m.put("lastError",r.getLastError());m.put("responseHash",r.getResponseHash());m.put("stale",r.getLastSuccess()==null||r.getLastSuccess().plusSeconds(NewsCatalog.interval(source)*2L).isBefore(Instant.now()));m.put("delayHours",source.equals("NEWSDATA")?12:0);m.put("schedulerEnabled",enabled);return m;});}
    private boolean claim(String source,Instant now){return tx.execute(s->{NewsFeed r=em.find(NewsFeed.class,id(source),LockModeType.PESSIMISTIC_WRITE);if(r.getLeaseUntil()!=null&&r.getLeaseUntil().isAfter(now)||r.getNextAttempt()!=null&&r.getNextAttempt().isAfter(now))return false;LocalDate day=now.atZone(ZoneOffset.UTC).toLocalDate();if(!day.equals(r.getBudgetDate())){r.setBudgetDate(day);r.setRequestsToday(0);}if(r.getRequestsToday()>=NewsCatalog.budget(source)){r.setStatus("BUDGET_EXHAUSTED");r.setNextAttempt(day.plusDays(1).atStartOfDay(ZoneOffset.UTC).toInstant());return false;}r.setLeaseUntil(now.plusSeconds(60));r.setLastAttempt(now);r.setRequestsToday(r.getRequestsToday()+1);return true;});}
    public static class HttpResult {public int status;public String body,etag,modified,retryAfter;}
    public HttpResult fetch(String source,NewsFeed state)throws IOException {
        String target=NewsCatalog.URLS.get(NewsCatalog.check(source));if(source.equals("NEWSDATA"))target+="&apikey="+URLEncoder.encode(key,"UTF-8");
        // No arbitrary target, redirects, source body fetch, or request-URL logging.
        HttpURLConnection c=(HttpURLConnection)new URL(target).openConnection();c.setInstanceFollowRedirects(false);c.setConnectTimeout(4000);c.setReadTimeout(8000);c.setRequestProperty("User-Agent","ExchangeNews/1.0");c.setRequestProperty("Accept",NewsCatalog.official(source)?"application/rss+xml,application/xml,text/xml":"application/json");if(state.getEtag()!=null)c.setRequestProperty("If-None-Match",state.getEtag());if(state.getLastModified()!=null)c.setRequestProperty("If-Modified-Since",state.getLastModified());long deadline=System.nanoTime()+12000000000L;
        try{HttpResult r=new HttpResult();r.status=c.getResponseCode();r.retryAfter=c.getHeaderField("Retry-After");r.etag=c.getHeaderField("ETag");r.modified=c.getHeaderField("Last-Modified");if(r.status==200){try(InputStream in=c.getInputStream();ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] bytes=new byte[8192];int n,total=0;while((n=in.read(bytes))!=-1){total+=n;if(total>2000000||System.nanoTime()>deadline)throw new IOException("News response limit");out.write(bytes,0,n);}r.body=new String(out.toByteArray(),StandardCharsets.UTF_8).replaceFirst("^\\uFEFF","");}}return r;}finally{c.disconnect();}
    }
    public NewsParser.Batch parse(String source,String body,Instant now)throws Exception {return NewsCatalog.official(source)?NewsParser.xml(source,body,now):NewsParser.index(source,body,now,json);}
    public Map<String,Object> sync(String source){NewsCatalog.check(source);Instant now=Instant.now();boolean requested=configured(source)&&claim(source,now);if(requested){HttpResult response=null;NewsParser.Batch parsed=null;String error=null;
        try{NewsFeed state=tx.execute(s->em.find(NewsFeed.class,id(source)));response=fetch(source,state);if(response.status==200)parsed=parse(source,response.body,now);else if(response.status!=304)error="HTTP "+response.status;}catch(Exception e){error=e.getClass().getSimpleName();} // Never expose transport messages containing secret query strings.
        final HttpResult r=response;final NewsParser.Batch b=parsed;final String failure=error;
        tx.execute(s->{NewsFeed f=em.find(NewsFeed.class,id(source),LockModeType.PESSIMISTIC_WRITE);f.setLeaseUntil(null);f.setHttpStatus(r==null?null:r.status);
            if(failure==null&&r!=null&&(r.status==200||r.status==304&&f.getParsedJson()!=null)){f.setFailures(0);f.setLastError(null);f.setLastSuccess(now);f.setNextAttempt(now.plusSeconds(NewsCatalog.interval(source)));if(r.status==200){f.setParsedJson(encode(b));f.setContentAsOf(now);f.setItemCount(b.items.size());f.setSkippedCount(b.skipped);f.setResponseHash(digest(r.body));f.setEtag(shorten(r.etag,300));f.setLastModified(shorten(r.modified,300));}f.setStatus(f.getItemCount()==0?"EMPTY":"OK");}
            else{f.setFailures(Math.min(20,f.getFailures()+1));f.setStatus(r!=null&&r.status==429?"RATE_LIMITED":r!=null&&r.status==403?"BLOCKED":"ERROR");f.setLastError(failure==null?"304_WITHOUT_CACHE":shorten(failure,200));long seconds=Math.min(86400L,NewsCatalog.interval(source)*(1L<<Math.min(5,f.getFailures()-1)));if(r!=null&&r.status==403)seconds=Math.max(seconds,43200L);Instant next=now.plusSeconds(seconds),retry=retryAfter(r==null?null:r.retryAfter,now);f.setNextAttempt(retry!=null&&retry.isAfter(next)?retry:next);}return null;});
        }Map<String,Object> out=new LinkedHashMap<>();out.put("requested",requested);out.put("source",status(source));return out;
    }
    public NewsParser.Batch cached(String source){return tx.execute(s->{NewsFeed f=em.find(NewsFeed.class,id(source));try{return f.getParsedJson()==null?new NewsParser.Batch():json.readValue(f.getParsedJson(),NewsParser.Batch.class);}catch(Exception e){throw new IllegalStateException("新闻缓存不可读",e);}});}
    static Instant retryAfter(String v,Instant now){if(v==null)return null;try{return now.plusSeconds(Math.max(0,Math.min(604800,Long.parseLong(v))));}catch(Exception e){try{Instant d=ZonedDateTime.parse(v,DateTimeFormatter.RFC_1123_DATE_TIME).toInstant();return d.isAfter(now.plusSeconds(604800))?now.plusSeconds(604800):d;}catch(Exception ignored){return null;}}}
    static String digest(String v){try{StringBuilder s=new StringBuilder();for(byte b:MessageDigest.getInstance("SHA-256").digest(v.getBytes(StandardCharsets.UTF_8)))s.append(String.format("%02x",b&255));return s.toString();}catch(Exception e){throw new IllegalStateException(e);}}
    private String encode(Object v){try{return json.writeValueAsString(v);}catch(Exception e){throw new IllegalStateException(e);}}
    private static String shorten(String v,int limit){return v==null?null:v.replaceAll("[\\p{Cc}\\p{Cf}]"," ").substring(0,Math.min(v.length(),limit));}
}
