package com.gtcfesk.exchange.insights.news;
import com.fasterxml.jackson.databind.*;import com.gtcfesk.exchange.tenant.TenantContext;
import lombok.RequiredArgsConstructor;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import org.springframework.http.HttpStatus;import org.springframework.web.server.ResponseStatusException;import javax.persistence.*;import java.time.*;import java.util.*;
@Service @RequiredArgsConstructor @Transactional(readOnly=true)
public class NewsService {
    @PersistenceContext private EntityManager em;private final ObjectMapper json;private final NewsSync sync;
    private <T> TypedQuery<T> query(String q,Class<T> type){return em.createQuery(q,type).setParameter("tenant",TenantContext.requireTenantId()).setParameter("env",sync.environment());}
    private List<NewsSourceSetting> settings(){return query("from NewsSourceSetting s where s.tenantId=:tenant and s.environment=:env",NewsSourceSetting.class).getResultList();}
    private NewsSourceSetting setting(String source){return settings().stream().filter(s->s.getSourceId().equals(source)).findFirst().orElse(null);}
    public List<String> enabledSourceIds(){List<String> ids=new ArrayList<>();List<NewsSourceSetting> rows=settings();for(String id:NewsCatalog.URLS.keySet()){NewsSourceSetting s=rows.stream().filter(r->r.getSourceId().equals(id)).findFirst().orElse(null);if((s==null?NewsCatalog.official(id):s.isEnabled())&&sync.configured(id))ids.add(id);}return ids;}
    public List<Map<String,Object>> sources(boolean admin){List<Map<String,Object>> out=new ArrayList<>();for(String id:NewsCatalog.URLS.keySet()){NewsSourceSetting s=setting(id);boolean enabled=s==null?NewsCatalog.official(id):s.isEnabled();if(!admin&&!enabled)continue;Map<String,Object> m=sync.status(id);m.put("enabled",enabled);m.put("effectiveEnabled",enabled&&sync.configured(id));if(admin){m.put("rowVersion",s==null?-1:s.getRowVersion());m.put("licenseReviewed",s==null?NewsCatalog.official(id):s.isLicenseReviewed());m.put("licenseEvidence",s==null?"2026-10-03 official terms; limited RSS headline metadata only":s.getLicenseEvidence());}out.add(m);}return out;}
    private String encode(Object v){try{return json.writeValueAsString(v);}catch(Exception e){throw new IllegalStateException(e);}}
    private NewsItem decode(NewsArticle a){try{return json.readValue(a.getDataJson(),NewsItem.class);}catch(Exception e){throw new IllegalStateException("新闻记录不可读",e);}}
    private Map<String,Object> view(NewsArticle a){Map<String,Object> m=json.convertValue(decode(a),new com.fasterxml.jackson.core.type.TypeReference<LinkedHashMap<String,Object>>(){});m.put("category",a.getCategory());m.put("language",a.getLanguage());m.put("publishedAt",a.getPublishedAt());m.put("timePrecision",a.getPublishedAt()==null?"UNKNOWN":"SECOND");m.put("discoveredAt",a.getDiscoveredAt());m.put("updatedAt",a.getUpdatedAt());m.put("hidden",a.isHidden());m.put("sortOrder",a.getSortOrder());m.put("rowVersion",a.getRowVersion());m.put("environment",a.getEnvironment());m.put("delayed",decode(a).delayHours>0);Map<String,Object> source=sync.status(a.getSourceId());m.put("sourceAsOf",source.get("lastSuccess"));m.put("sourceContentAsOf",source.get("contentAsOf"));m.put("sourceStatus",source.get("status"));m.put("stale",source.get("stale"));return m;}
    private NewsArticle article(String id,boolean admin,boolean lock){if(id==null||!id.matches("[a-f0-9-]{36}"))throw missing();TypedQuery<NewsArticle> q=query("from NewsArticle a where a.tenantId=:tenant and a.environment=:env and a.articleId=:id"+(admin?"":" and a.hidden=false"),NewsArticle.class).setParameter("id",id);if(lock)q.setLockMode(LockModeType.PESSIMISTIC_WRITE);List<NewsArticle> rows=q.setMaxResults(1).getResultList();if(rows.isEmpty()||!admin&&!enabledSourceIds().contains(rows.get(0).getSourceId()))throw missing();return rows.get(0);}
    public Map<String,Object> detail(String id,boolean admin){return view(article(id,admin,false));}
    public Map<String,Object> list(String category,String sourceId,String language,Instant from,Instant to,int page,int size,Boolean hidden,boolean admin){
        if(page<0||page>10000||size<1||size>100)throw NewsCatalog.bad("分页size须1至100，page须0至10000");if(category!=null&&!Arrays.asList("MACRO","CRYPTO","FINANCE").contains(category))throw NewsCatalog.bad("新闻分类无效");if(sourceId!=null)NewsCatalog.check(sourceId);if(language!=null&&(language.length()>16||!language.matches("[A-Za-z]{2,8}(-[A-Za-z0-9]{1,8})*")))throw NewsCatalog.bad("语言代码无效");if(from!=null||to!=null){if(to==null)to=Instant.now();if(from==null)from=to.minusSeconds(2592000);if(to.isBefore(from)||Duration.between(from,to).getSeconds()>31622400)throw NewsCatalog.bad("时间窗口最多366日");}
        List<String> ids=admin?new ArrayList<>(NewsCatalog.URLS.keySet()):enabledSourceIds();String where=" where a.tenantId=:tenant and a.environment=:env and a.sourceId in :ids"+(admin?(hidden==null?"":" and a.hidden=:hidden"):" and a.hidden=false")+(category==null?"":" and a.category=:category")+(sourceId==null?"":" and a.sourceId=:source")+(language==null?"":" and a.language=:lang")+(from==null?"":" and a.publishedAt>=:from and a.publishedAt<=:to");List<Map<String,Object>> content=new ArrayList<>();long total=0;
        if(!ids.isEmpty()){TypedQuery<NewsArticle> q=query("from NewsArticle a"+where+" order by a.sortOrder desc,coalesce(a.publishedAt,a.discoveredAt) desc,a.articleId",NewsArticle.class);TypedQuery<Long> count=query("select count(a) from NewsArticle a"+where,Long.class);for(TypedQuery<?> x:Arrays.asList(q,count)){x.setParameter("ids",ids);if(category!=null)x.setParameter("category",category);if(sourceId!=null)x.setParameter("source",sourceId);if(language!=null)x.setParameter("lang",language.toLowerCase(Locale.ROOT));if(admin&&hidden!=null)x.setParameter("hidden",hidden);if(from!=null){x.setParameter("from",from);x.setParameter("to",to);}}total=count.getSingleResult();for(NewsArticle a:q.setFirstResult(page*size).setMaxResults(size).getResultList())content.add(view(a));}
        List<Map<String,Object>> sources=sources(admin);List<Map<String,Object>> active=new ArrayList<>();for(Map<String,Object> s:sources)if(Boolean.TRUE.equals(s.get("enabled")))active.add(s);boolean failed=active.stream().anyMatch(s->!Arrays.asList("OK","EMPTY").contains(s.get("status"))),stale=active.stream().anyMatch(s->Boolean.TRUE.equals(s.get("stale")));String state=total==0?(active.isEmpty()||failed?"UNAVAILABLE":"EMPTY"):failed?"PARTIAL":stale?"STALE":"FRESH";if(total==0&&category!=null&&!category.equals("MACRO")&&ids.stream().allMatch(NewsCatalog::official))state="EMPTY";
        Map<String,Object> out=new LinkedHashMap<>();out.put("content",content);out.put("number",page);out.put("size",size);out.put("totalElements",total);out.put("totalPages",(total+size-1)/size);out.put("sources",sources);out.put("asOf",Instant.now());out.put("dataStatus",state);out.put("environment",sync.environment());out.put("coverage","Official macroeconomic news; not a comprehensive real-time crypto feed");return out;
    }
    private void lockFeed(String id){em.find(NewsFeed.class,sync.id(id),LockModeType.PESSIMISTIC_WRITE);}
    @Transactional public int importCached(String source){NewsCatalog.check(source);NewsParser.Batch b=sync.cached(source);return importBatch(source,b,false,"官方白名单RSS/索引缓存");}
    @Transactional public int importBatch(String source,NewsParser.Batch batch,boolean manual,String material){NewsCatalog.check(source);if(manual){actor();reason(material);}if(!enabledSourceIds().contains(source)){if(manual)throw NewsCatalog.bad("来源关闭或未完成后端配置");return 0;}if(batch.items.size()>500)throw NewsCatalog.bad("导入超过500条");lockFeed(source);int changed=0;
        // ponytail: one shared source row serializes bounded metadata imports across tenants; shard only if throughput warrants it.
        for(NewsItem n:batch.items){if(!source.equals(n.sourceId))throw NewsCatalog.bad("来源不匹配");List<NewsArticle> rows=query("from NewsArticle a where a.tenantId=:tenant and a.environment=:env and a.articleId=:id",NewsArticle.class).setParameter("id",n.articleId).getResultList();NewsArticle a=rows.isEmpty()?new NewsArticle():rows.get(0);if(!rows.isEmpty())n.discoveredAt=a.getDiscoveredAt();JsonNode fingerprint=json.valueToTree(n);((com.fasterxml.jackson.databind.node.ObjectNode)fingerprint).remove("discoveredAt");String hash=NewsSync.digest(fingerprint.toString());if(!rows.isEmpty()&&hash.equals(a.getUpstreamHash()))continue;
            if(rows.isEmpty()){a.setEnvironment(sync.environment());a.setArticleId(n.articleId);a.setSourceId(source);a.setCategory(n.category);a.setHidden(manual);a.setDiscoveredAt(n.discoveredAt);}a.setLanguage(n.language);a.setPublishedAt(n.publishedAt);a.setDataJson(encode(n));a.setUpstreamHash(hash);a.setUpdatedAt(Instant.now());if(rows.isEmpty())em.persist(a);changed++;
        }if(manual)audit(source,null,"IMPORT",material,null,Collections.singletonMap("changed",changed));em.flush();return changed;
    }
    public static class SourceEdit {public Long rowVersion;public boolean enabled,licenseReviewed;public String licenseEvidence,reason;}
    @Transactional public Map<String,Object> sourceEdit(String id,SourceEdit input){NewsCatalog.check(id);actor();if(input==null)throw NewsCatalog.bad("缺少来源设置");reason(input.reason);reason(input.licenseEvidence);lockFeed(id);NewsSourceSetting s=setting(id);version(s==null?-1:s.getRowVersion(),input.rowVersion);if(input.enabled&&(!sync.configured(id)||!input.licenseReviewed))throw NewsCatalog.bad("须后端配置、账户权益及内容许可核验后启用");String before=encode(sources(true).stream().filter(x->id.equals(x.get("sourceId"))).findFirst().get());if(s==null){s=new NewsSourceSetting();s.setEnvironment(sync.environment());s.setSourceId(id);em.persist(s);}s.setEnabled(input.enabled);s.setLicenseReviewed(input.licenseReviewed);s.setLicenseEvidence(NewsParser.plain(input.licenseEvidence,1000));em.flush();Map<String,Object> after=sources(true).stream().filter(x->id.equals(x.get("sourceId"))).findFirst().get();audit(id,null,"SOURCE_EDIT",input.reason,before,after);return after;}
    public static class Edit {public Long rowVersion;public String category,reason;public boolean hidden;public int sortOrder;}
    @Transactional public Map<String,Object> edit(String id,Edit input){actor();if(input==null)throw NewsCatalog.bad("缺少文章设置");reason(input.reason);NewsArticle a=article(id,true,true);version(a.getRowVersion(),input.rowVersion);if(!Arrays.asList("MACRO","CRYPTO","FINANCE").contains(input.category)||NewsCatalog.official(a.getSourceId())&&!input.category.equals("MACRO")||Math.abs((long)input.sortOrder)>10000)throw NewsCatalog.bad("官方宏观文章只能为MACRO，排序范围-10000至10000");String before=encode(view(a));a.setCategory(input.category);a.setHidden(input.hidden);a.setSortOrder(input.sortOrder);a.setUpdatedAt(Instant.now());em.flush();Map<String,Object> after=view(a);audit(a.getSourceId(),id,"ARTICLE_EDIT",input.reason,before,after);return after;}
    public List<NewsAudit> audits(int page){if(page<0||page>10000)throw NewsCatalog.bad("审计分页无效");return query("from NewsAudit a where a.tenantId=:tenant and a.environment=:env order by a.id desc",NewsAudit.class).setFirstResult(page*50).setMaxResults(50).getResultList();}
    private void audit(String source,String id,String action,String reason,String before,Object after){NewsAudit a=new NewsAudit();a.setEnvironment(sync.environment());a.setSourceId(source);a.setArticleId(id);a.setActor(actor());a.setAction(action);a.setReason(NewsParser.plain(reason,1000));a.setBeforeJson(before);a.setAfterJson(encode(after));em.persist(a);}
    private static String actor(){return com.gtcfesk.exchange.insights.CalendarService.actor();}
    private static void reason(String s){if(s==null||s.trim().isEmpty()||s.length()>1000||NewsParser.plain(s,1000)==null)throw NewsCatalog.bad("须填写核验依据，最多1000字");}
    private static void version(long version,Long expected){if(expected==null||version!=expected)throw new ResponseStatusException(HttpStatus.CONFLICT,"记录已更新，请刷新重试");}
    private static ResponseStatusException missing(){return new ResponseStatusException(HttpStatus.NOT_FOUND,"新闻不存在、来源关闭或文章已隐藏");}
}
