-- Disposable fixture only. Never execute on any existing database.
CREATE TABLE user_account(id BIGINT NOT NULL PRIMARY KEY,email VARCHAR(128) NOT NULL,password_hash VARCHAR(128) NOT NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,row_version BIGINT NOT NULL DEFAULT 0) ENGINE=InnoDB;
CREATE TABLE asset_account(id BIGINT AUTO_INCREMENT PRIMARY KEY,user_id BIGINT NOT NULL,coin VARCHAR(32) NOT NULL,available DECIMAL(32,16) NOT NULL,frozen DECIMAL(32,16) NOT NULL,row_version BIGINT NOT NULL DEFAULT 0,created_at DATETIME,updated_at DATETIME,UNIQUE KEY uk_asset_user_coin(user_id,coin)) ENGINE=InnoDB;
CREATE TABLE deposit_record(id BIGINT AUTO_INCREMENT PRIMARY KEY,row_version BIGINT NOT NULL DEFAULT 0,user_id BIGINT NOT NULL,type VARCHAR(20) NOT NULL,network VARCHAR(50) NOT NULL,amount DECIMAL(32,16) NOT NULL,currency VARCHAR(3),original_amount DECIMAL(32,16),exchange_rate DECIMAL(32,16),address VARCHAR(200) NOT NULL,proof_image VARCHAR(500),status VARCHAR(20) NOT NULL,remark VARCHAR(500),created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL) ENGINE=InnoDB;
CREATE TABLE admin_menu(id BIGINT AUTO_INCREMENT PRIMARY KEY,parent_id BIGINT,menu_name VARCHAR(50) NOT NULL,menu_code VARCHAR(50) NOT NULL UNIQUE,menu_type VARCHAR(20) NOT NULL,path VARCHAR(200),icon VARCHAR(50),sort_order INT NOT NULL,status VARCHAR(20) NOT NULL,created_at DATETIME,updated_at DATETIME) ENGINE=InnoDB;
CREATE TABLE menu_action(id BIGINT AUTO_INCREMENT PRIMARY KEY,menu_id BIGINT NOT NULL,action_code VARCHAR(100) NOT NULL,action_name VARCHAR(100) NOT NULL,sort_order INT NOT NULL,created_at DATETIME,updated_at DATETIME) ENGINE=InnoDB;
INSERT INTO user_account VALUES(1,'legacy@fixture.invalid','not-a-login',NOW(),NOW(),0);
INSERT INTO asset_account(user_id,coin,available,frozen) VALUES(1,'FUND',25,3);
INSERT INTO deposit_record(user_id,type,network,amount,address,status,created_at,updated_at) VALUES(1,'bank','BANK',10,'','COMPLETED',NOW(),NOW()),(1,'bank','BANK',20,'','PENDING',NOW(),NOW()),(1,'bank','BANK',30,'','REJECTED',NOW(),NOW());
