<script setup lang="ts">
import { ref, onMounted, onUnmounted, watch } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { api, apiFile, dataRows } from './api'
import ControlAttachment from './ControlAttachment.vue'
const tenants=ref<any[]>([]),tenant=ref<number|'all'>('all'),rows=ref<any[]>([]),page=ref(1),userId=ref(''),userEmail=ref(''),adminId=ref(''),error=ref(''),busy=ref(false)
const createdFrom=ref(''),createdTo=ref(''),appliedRange=ref('')
let listRequest:AbortController|undefined
const archives=ref<any[]>([]),archiveFiles=ref<any[]>([]),imageFiles=ref<any[]>([]),archivePage=ref(1),archiveError=ref('')
const conversation=ref<any>(null),messages=ref<any[]>([]),more=ref(false),preview=ref<any>(null),previewOpen=ref(false)
let generation=0, detailGeneration=0,disposed=false
const path=(target:number)=>`/control/tenants/${target}`
function rowTenant(row:any):number{const target=row?.tenant_id;if(!Number.isSafeInteger(target)||target<=0||(tenant.value!=='all'&&target!==tenant.value))throw new Error('会话租户范围无效');return target}
const detailMatches=(target:number,id:number,g:number)=>g===detailGeneration&&target===conversation.value?.tenant_id&&id===conversation.value?.id
async function load(reset=false){
 const id=++generation;listRequest?.abort();listRequest=new AbortController();const signal=listRequest.signal
 conversation.value=null;messages.value=[];archives.value=[];archiveFiles.value=[];imageFiles.value=[];archiveError.value='';detailGeneration++;rows.value=[];error.value='';busy.value=false;appliedRange.value='';if(reset)page.value=1;busy.value=true
 try{
  const q=new URLSearchParams({page:String(page.value-1)});for(const [key,value] of [['userId',userId.value],['adminId',adminId.value]]){if(value&&!/^[1-9]\d*$/.test(value))throw new Error('ID 必须为正整数');if(value)q.set(key!,value!)}
  if(userEmail.value.trim())q.set('userEmail',userEmail.value.trim())
  if(!!createdFrom.value!==!!createdTo.value)throw new Error('请同时选择开始和结束时间')
  if(createdFrom.value){const from=new Date(createdFrom.value),to=new Date(createdTo.value);if(!Number.isFinite(from.getTime())||!Number.isFinite(to.getTime())||to.getTime()<=from.getTime()||to.getTime()-from.getTime()>366*86400000)throw new Error('时间须递增且不超过366天');q.set('createdFrom',from.toISOString());q.set('createdTo',to.toISOString())}
  const listPath=tenant.value==='all'?'/control/support/conversations':`${path(tenant.value)}/support/conversations`
  const response=await api(`${listPath}?${q}`,'GET',undefined,signal)
  if(id===generation){rows.value=dataRows(response);appliedRange.value=createdFrom.value?`${q.get('createdFrom')}（含）至 ${q.get('createdTo')}（不含）`:'未限制时间'}
 }catch(e:any){if(id===generation&&!signal.aborted)error.value=e.message}finally{if(id===generation)busy.value=false}
}
async function detail(row:any,append=false){const g=++detailGeneration;error.value='';if(!append){conversation.value=null;messages.value=[];more.value=false;archives.value=[];archiveFiles.value=[];imageFiles.value=[];archiveError.value=''}try{const target=rowTenant(row);conversation.value=row;const after=append?(messages.value[messages.value.length-1]?.id||0):0;const items=dataRows(await api(`${path(target)}/support/conversations/${row.id}?after=${after}`));if(!detailMatches(target,row.id,g))return;messages.value=[...messages.value,...items];more.value=items.length===100;if(!append)await loadArchives()}catch(e:any){if(g===detailGeneration)error.value=e.message}}
async function exportEvidence(){const target=conversation.value?.tenant_id,id=conversation.value?.id,g=detailGeneration;if(!target||!id||busy.value)return;busy.value=true;try{const {blob,chainValid}=await apiFile(`${path(target)}/support/conversations/${id}/evidence`);if(!detailMatches(target,id,g))return;if(!blob.type.startsWith('application/json'))throw new Error('证据响应格式无效');const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`tenant-${target}-conversation-${id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);if(chainValid!=='true')ElMessage.warning('证据已下载，但完整性校验未通过；请保留原始文件并调查，不能作为校验通过的证据。');else ElMessage.success('证据已下载，消息链及附件哈希校验通过')}catch(e:any){ElMessage.error(e.message)}finally{busy.value=false}}

async function loadArchives(){const target=conversation.value?.tenant_id,c=conversation.value?.id,g=detailGeneration;if(!target||!c)return;try{const response=await api(`${path(target)}/support/conversations/${c}/archive-jobs`);if(detailMatches(target,c,g)){archives.value=dataRows(response);archiveError.value=''}}catch(e:any){if(g===detailGeneration)archiveError.value=e.message}}
async function startArchive(){const target=conversation.value?.tenant_id,c=conversation.value?.id,g=detailGeneration;if(!target||!c||busy.value)return;try{const why=await reason('创建有界分块归档（不删除会话）');if(!detailMatches(target,c,g))return;busy.value=true;await api(`${path(target)}/support/conversations/${c}/archive-jobs`,'POST',{requestKey:crypto.randomUUID(),reason:why});if(!detailMatches(target,c,g))return;await loadArchives();ElMessage.success('归档任务已创建；审核人、租户与原因均审计。刷新查看进度。')}catch(e:any){if(e!=='cancel'&&e!=='close')ElMessage.error(e.message)}finally{busy.value=false}}
async function retryArchive(job:any){const target=conversation.value?.tenant_id,c=conversation.value?.id,g=detailGeneration;if(!target||!c||busy.value)return;try{const why=await reason('修复故障后重试原归档任务');if(!detailMatches(target,c,g))return;busy.value=true;await api(`${path(target)}/support/archive-jobs/${job.id}/retry`,'POST',{reason:why});if(detailMatches(target,c,g))await loadArchives()}catch(e:any){if(e!=='cancel'&&e!=='close')ElMessage.error(e.message)}finally{busy.value=false}}
async function archiveDownload(job:any,file:any,manifest=false){const target=conversation.value?.tenant_id,c=conversation.value?.id,g=detailGeneration;if(!target||!c||busy.value)return;busy.value=true;try{const {blob}=await apiFile(`${path(target)}/support/archive-jobs/${job.id}/files/${file.file}`);if(!detailMatches(target,c,g))return;if(blob.size>16*1024*1024)throw new Error('归档下载超出16MB单文件预算');const buffer=await blob.arrayBuffer(),hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',buffer))).map(x=>x.toString(16).padStart(2,'0')).join('');if(hash!==file.sha256)throw new Error('归档文件哈希不匹配，拒绝保存');if(file.file.endsWith('.json')){const parsed=JSON.parse(new TextDecoder().decode(buffer));if(parsed.tenantId!==target||parsed.jobId!==job.id)throw new Error('归档文件租户或任务不匹配');if(!detailMatches(target,c,g))return;if(manifest){archivePage.value=1;archiveFiles.value=(parsed.chunks||[]).map((item:any)=>({...item,job}));imageFiles.value=[]}else imageFiles.value=(parsed.attachments||[]).map((item:any)=>({...item,job}))}if(!detailMatches(target,c,g))return;const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=file.file;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);ElMessage.success('当前身份和完整性校验通过；完整恢复须保留manifest、全部块和附件。')}catch(e:any){ElMessage.error(e.message)}finally{busy.value=false}}

async function retention(){if(tenant.value==='all')return;preview.value=null;previewOpen.value=true;const target=tenant.value,g=generation;try{const result=await api(`${path(target)}/retention`);if(target===tenant.value&&g===generation&&previewOpen.value)preview.value=result.data||result}catch(e:any){if(target===tenant.value&&g===generation)ElMessage.error(e.message)}}
async function reason(title:string){const result=await ElMessageBox.prompt('操作原因必须保留审计',title,{inputValidator:value=>!!value?.trim()||'请填写原因',inputPlaceholder:'操作原因'});return result.value.trim()}
async function hold(row:any){if(busy.value)return;const g=generation;try{const target=rowTenant(row),why=await reason(`租户 ${row.tenant_name||target} · 会话 ${row.id}：${row.legal_hold?'取消法律/争议保留':'设置法律/争议保留'}`);if(g!==generation)return;busy.value=true;await api(`${path(target)}/retention/hold/${row.id}`,'POST',{enabled:!row.legal_hold,reason:why});if(g!==generation)return;await load();ElMessage.success('保留状态已更新')}catch(e:any){if(e!=='cancel'&&e!=='close')ElMessage.error(e.message)}finally{busy.value=false}}
async function retentionAction(clean:boolean){if(busy.value||!preview.value||tenant.value==='all')return;const target=tenant.value,p={...preview.value};try{const why=await reason(clean?'清理历史会话':p.autoDeleteEnabled?'关闭清理策略':'开启清理策略');const tenantName=tenants.value.find(t=>t.id===target)?.name||target;await ElMessageBox.confirm(clean?`租户 ${tenantName}：永久删除本次预览中的 ${p.candidateIds.length} 个完整会话及附件，先归档，失败则不删。已保留或未结束会话不在范围。确认继续？`:`租户 ${tenantName}：${p.autoDeleteEnabled?'关闭':'开启'}清理策略；开启后定时执行，未来满足条件的完整已结束、超过 ${p.retentionDays} 天且未保留会话将持续被归档后永久删除。`, '确认高风险操作',{type:'warning',confirmButtonText:'确认执行'});if(target!==tenant.value)return;busy.value=true;await api(`${path(target)}/retention${clean?'/clean':''}`,clean?'POST':'PUT',clean?{confirm:true,reason:why,policyVersion:p.policyVersion,previewHash:p.previewHash}:{enabled:!p.autoDeleteEnabled,reason:why,...(!p.autoDeleteEnabled?{confirm:true,policyVersion:p.policyVersion,previewHash:p.previewHash}:{})});await retention();await load();ElMessage.success('操作已完成')}catch(e:any){if(e!=='cancel'&&e!=='close')ElMessage.error(e.message)}finally{busy.value=false}}
watch(tenant,()=>{previewOpen.value=false;preview.value=null;load(true)},{flush:'sync'});onUnmounted(()=>{disposed=true;generation++;detailGeneration++;listRequest?.abort()});onMounted(async()=>{const g=generation;try{const response=await api('/control/tenants');if(disposed)return;tenants.value=dataRows(response);if(g===generation)await load(true)}catch(e:any){if(!disposed&&g===generation)error.value=e.message}})
</script>
<template>
 <div class="toolbar"><div><h2>客服监管与留存</h2><p>仅查看会话和消息，不代发消息、不改变已读状态。留存操作须原因、确认及服务端审计。</p></div><el-button :disabled="tenant==='all'" title="留存预览与策略需选择单个租户" @click="retention">留存预览与策略</el-button></div>
 <el-form inline @submit.prevent="load(true)"><el-form-item label="租户"><el-select v-model="tenant" style="width:220px"><el-option value="all" label="全部"/><el-option v-for="t in tenants" :key="t.id" :value="t.id" :label="t.name"/></el-select></el-form-item><el-form-item label="用户 ID"><el-input v-model="userId"/></el-form-item><el-form-item label="用户邮箱"><el-input v-model="userEmail" clearable maxlength="254" placeholder="用户邮箱"/></el-form-item><el-form-item label="客服 ID"><el-input v-model="adminId"/></el-form-item><el-form-item label="开始时间（本机时区）"><input v-model="createdFrom" type="datetime-local" aria-label="开始时间"/></el-form-item><el-form-item label="结束时间（不含）"><input v-model="createdTo" type="datetime-local" aria-label="结束时间"/></el-form-item><el-button native-type="submit" :loading="busy">查询</el-button></el-form>
 <p>查询时间按本机时区选择，发送含UTC偏移的范围；服务器按UTC过滤。{{appliedRange}}。留存预览与策略需选择单个租户。</p>
 <el-alert v-if="error" :title="error" type="error" :closable="false"/>
 <admin-table table-key="control.chat.conversations" :data="rows" border><el-table-column prop="tenant_name" label="租户" min-width="180"/><el-table-column prop="id" label="会话 ID"/><el-table-column prop="user_id" label="用户 ID"/><el-table-column prop="user_email" label="用户邮箱" min-width="200" show-overflow-tooltip/><el-table-column prop="user_remark" label="用户备注" min-width="150" show-overflow-tooltip/><el-table-column prop="admin_id" label="客服"/><el-table-column prop="status" label="状态"/><el-table-column prop="created_at" label="开始时间" min-width="150"/><el-table-column prop="closed_at" label="结束时间" min-width="150"/><el-table-column column-key="retention" label="保留"><template #default="s">{{ s.row.legal_hold?'法律/争议保留':'普通' }}</template></el-table-column><el-table-column column-key="actions" label="操作" min-width="150"><template #default="s"><el-button link @click="detail(s.row)">查看</el-button><el-button link :disabled="busy" @click="hold(s.row)">{{ s.row.legal_hold?'取消保留':'设置保留' }}</el-button></template></el-table-column></admin-table>
 <div class="toolbar" style="margin-top:16px"><el-button :disabled="page===1||busy" @click="page--;load()">上一页</el-button><span>第 {{ page }} 页</span><el-button :disabled="rows.length<30||busy" @click="page++;load()">下一页</el-button></div>
 <el-dialog :model-value="!!conversation" @update:model-value="(v:boolean)=>{if(!v){conversation=null;detailGeneration++}}" :title="`租户 ${conversation?.tenant_name||conversation?.tenant_id||''} · 会话 ${conversation?.id||''} · 只读`" width="min(1050px,95vw)" destroy-on-close><el-button :loading="busy" @click="exportEvidence">下载完整证据 JSON（含附件与校验）</el-button><el-button :disabled="busy" @click="startArchive">创建大会话分块归档</el-button><el-button :disabled="busy" @click="loadArchives">刷新归档进度</el-button><el-alert v-if="archiveError" :title="archiveError" type="error" :closable="false"/><admin-table table-key="control.chat.archive.jobs" :data="archives" border><el-table-column prop="id" label="任务 ID" min-width="180"/><el-table-column prop="state" label="状态"/><el-table-column prop="processed_messages" label="已归档条数"/><el-table-column prop="expected_messages" label="快照总条数"/><el-table-column prop="attachment_bytes" label="附件字节"/><el-table-column prop="failure_type" label="失败类型"/><el-table-column column-key="archiveActions" label="归档操作" min-width="180"><template #default="s"><el-button v-if="s.row.state==='FAILED'" link :disabled="busy" @click="retryArchive(s.row)">修复后重试</el-button><el-button v-if="s.row.state==='COMPLETE'" link :disabled="busy" @click="archiveDownload(s.row,{file:`manifest-${s.row.final_manifest_sha256}.json`,sha256:s.row.final_manifest_sha256},true)">下载manifest</el-button></template></el-table-column></admin-table><p v-if="archiveFiles.length">归档块：第 {{archivePage}} 页；下载每个块后列出对应PNG附件。</p><div v-for="file in archiveFiles.slice((archivePage-1)*30,archivePage*30)" :key="file.file"><el-button link :disabled="busy" @click="archiveDownload(file.job,file)">{{file.file}} · {{file.messages}} 条</el-button></div><div v-if="archiveFiles.length>30"><el-button :disabled="archivePage===1" @click="archivePage--">上一页归档块</el-button><el-button :disabled="archivePage*30>=archiveFiles.length" @click="archivePage++">下一页归档块</el-button></div><div v-for="file in imageFiles" :key="file.file"><el-button link :disabled="busy" @click="archiveDownload(file.job,file)">{{file.file}} · {{file.bytes}} 字节</el-button></div><admin-table table-key="control.chat.messages" :data="messages" border><el-table-column prop="id" label="ID" width="80"/><el-table-column prop="sender_name" label="发送者"/><el-table-column prop="sender" label="类型"/><el-table-column prop="text" label="内容" min-width="270"/><el-table-column prop="created_at" label="时间" min-width="170"/><el-table-column column-key="attachments" label="附件" min-width="260"><template #default="s"><ControlAttachment v-if="s.row.image&&conversation" :key="`${conversation.tenant_id}:${conversation.id}:${s.row.id}`" :path="`${path(conversation.tenant_id)}/support/conversations/${conversation.id}/images/${s.row.id}`"/><span v-else>无</span></template></el-table-column><el-table-column prop="hash" label="消息校验哈希" show-overflow-tooltip/></admin-table><el-button v-if="more" @click="detail(conversation,true)">加载后续 100 条</el-button></el-dialog>
 <el-dialog v-model="previewOpen" title="历史会话留存" width="min(700px,95vw)"><template v-if="preview"><el-alert title="默认仅保留。开启后将定时归档并永久删除达标会话；启用前必须配置受限归档目录并完成恢复演练。清理不可撤销；归档恢复为独立流程。" type="warning" :closable="false"/><el-descriptions :column="1" border><el-descriptions-item label="清理策略">{{ preview.autoDeleteEnabled?'已启用':'关闭' }}</el-descriptions-item><el-descriptions-item label="保留天数">{{ preview.retentionDays }}</el-descriptions-item><el-descriptions-item label="全部候选会话">{{ preview.candidateCount }}</el-descriptions-item><el-descriptions-item label="候选附件字节">{{ preview.attachmentBytes }}</el-descriptions-item><el-descriptions-item label="本次最多 100 个会话 ID">{{ preview.candidateIds.join(', ')||'无' }}</el-descriptions-item><el-descriptions-item label="策略版本">{{ preview.policyVersion }}</el-descriptions-item></el-descriptions><div class="toolbar" style="margin-top:20px"><el-button :loading="busy" @click="retentionAction(false)">{{ preview.autoDeleteEnabled?'关闭':'开启' }}清理策略</el-button><el-button type="danger" :loading="busy" :disabled="!preview.autoDeleteEnabled||!preview.candidateIds.length" @click="retentionAction(true)">确认清理本次候选</el-button></div></template><p v-else>预览未加载；不可执行清理。</p></el-dialog>
</template>
