<script setup lang="ts">
import { ref, reactive, onMounted } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { api, dataRows, controlSession, clearSession } from './api'
const rows=ref<any[]>([]),page=ref(1),total=ref(0),error=ref(''),open=ref(false),busy=ref(false)
const form=reactive({id:0,account:'',enabled:true,newPassword:'',newSecret:'',newTotp:'',password:'',totp:'',reason:''})
const clear=()=>Object.assign(form,{id:0,account:'',enabled:true,newPassword:'',newSecret:'',newTotp:'',password:'',totp:'',reason:''})
async function load(){try{const response=await api(`/control/accounts?page=${page.value-1}`);rows.value=dataRows(response);total.value=response.data?.totalElements||rows.value.length;error.value=''}catch(e:any){error.value=e.message}}
function edit(row?:any){clear();if(row)Object.assign(form,{id:row.id,account:row.account,enabled:row.enabled});open.value=true}
async function save(){if(busy.value)return;busy.value=true;try{await ElMessageBox.confirm(`确认${form.id?'变更':'创建'}总控账号 ${form.account}？总控可管理所有租户；变更凭据会撤销该账号旧会话。`,'确认总控账号操作',{type:'warning'});const self=form.id===controlSession.value?.user.id;const body={...form,newPassword:form.newPassword||undefined,...form.id?{}:{enabled:undefined}};await api(form.id?`/control/accounts/${form.id}`:'/control/accounts',form.id?'PUT':'POST',body);open.value=false;clear();if(self){clearSession();ElMessage.success('账号已更新，请重新登录')}else{await load();ElMessage.success('总控账号已保存')}}catch(e:any){if(e!=='cancel'&&e!=='close')ElMessage.error(e.message)}finally{busy.value=false}}
onMounted(load)
</script>
<template><div class="toolbar"><div><h3>总控账号管理</h3><p>独立身份域。创建与重置都需当前操作者密码和 MFA 二次验证。</p></div><el-button @click="edit()">新增总控</el-button></div><el-alert v-if="error" :title="error" type="error" :closable="false"/><admin-table table-key="control.accounts" :data="rows" border><el-table-column prop="id" label="ID"/><el-table-column prop="account" label="账号"/><el-table-column prop="enabled" label="启用"/><el-table-column prop="mfaEnabled" label="MFA"/><el-table-column label="操作"><template #default="s"><el-button link @click="edit(s.row)">状态 / 密码</el-button></template></el-table-column></admin-table><el-pagination v-model:current-page="page" :total="total" :page-size="50" layout="prev,pager,next" @current-change="load"/><el-dialog v-model="open" :title="form.id?'变更总控账号':'创建总控账号'" width="min(600px,95vw)" @closed="clear"><el-form label-width="140px" :disabled="busy"><el-form-item label="账号" required><el-input v-model="form.account" :disabled="!!form.id" autocomplete="off"/></el-form-item><el-form-item v-if="form.id" label="启用"><el-switch v-model="form.enabled" :disabled="form.id===controlSession?.user.id"/></el-form-item><el-form-item :label="form.id?'新密码（空不改）':'初始密码'" :required="!form.id"><el-input v-model="form.newPassword" type="password" autocomplete="new-password" placeholder="16 至 128 位"/></el-form-item><template v-if="!form.id"><el-form-item label="新账号 TOTP 密钥" required><el-input v-model="form.newSecret" type="password" autocomplete="off" placeholder="32 至 64 位 Base32"/></el-form-item><el-form-item label="新账号动态码" required><el-input v-model="form.newTotp" inputmode="numeric" maxlength="6"/></el-form-item></template><el-form-item label="当前操作者密码" required><el-input v-model="form.password" type="password" autocomplete="current-password"/></el-form-item><el-form-item label="当前操作者动态码" required><el-input v-model="form.totp" inputmode="numeric" maxlength="6"/></el-form-item><el-form-item label="原因" required><el-input v-model="form.reason" type="textarea" maxlength="500"/></el-form-item></el-form><template #footer><el-button type="danger" :loading="busy" @click="save">二次验证并保存</el-button></template></el-dialog></template>
