<script setup lang="ts">
import { ref,onMounted,onUnmounted,watch } from 'vue'
import { ElMessage,ElMessageBox } from 'element-plus'
import { api,dataRows } from './api'
const tenants=ref<any[]>([]),tenant=ref<number>(),rows=ref<any[]>([]),page=ref(0),error=ref(''),health=ref<any>(),busy=ref(false)
let generation=0,request:AbortController|undefined
async function load(reset=false){const id=++generation;request?.abort();request=new AbortController();const signal=request.signal;if(reset)page.value=0;rows.value=[];error.value='';if(!tenant.value)return;busy.value=true;try{const [result,h]=await Promise.all([api(`/control/operations/tenants/${tenant.value}?page=${page.value}`,'GET',undefined,signal),api('/control/operations/health','GET',undefined,signal)]);if(id===generation){rows.value=dataRows(result);health.value=h.data}}catch(e:any){if(id===generation&&!signal.aborted)error.value=e.message}finally{if(id===generation)busy.value=false}}
async function review(row:any){const target=tenant.value;try{const why=(await ElMessageBox.prompt('填写处理原因；此动作仅复核，不改余额，不触发业务修复','异常复核',{inputPattern:/^.{5,500}$/,inputErrorMessage:'原因5至500字'})).value;const hash=(await ElMessageBox.prompt('已实际复核报告的SHA256（64位小写十六进制）','绑定复核证据',{inputPattern:/^[a-f0-9]{64}$/,inputErrorMessage:'需要实际报告SHA256'})).value;await ElMessageBox.confirm('确认记录为已复核、继续保留。原幂等任务按下一调度重试；此页面不执行清理或余额修正。','确认复核');if(target!==tenant.value)return;await api(`/control/operations/tenants/${target}/review`,'POST',{job:row.job,expectedFailureId:row.latest_failure_id,reason:why,evidenceSha256:hash,result:'PRESERVED'});await load();ElMessage.success('真实操作者及证据已留审计；未修改业务数据')}catch(e:any){if(e!=='cancel'&&e!=='close')ElMessage.error(e.message)}}
watch(tenant,()=>load(true));onUnmounted(()=>{generation++;request?.abort()});onMounted(async()=>{try{tenants.value=dataRows(await api('/control/tenants'))}catch(e:any){error.value=e.message}})
</script>
<template><h2>运行异常与复核</h2><p>明确选择租户。仅显示任务/运行元数据，不显示聊天、凭据或完整实名。原幂等引擎重试；不直接修改余额。</p><el-select v-model="tenant" placeholder="选择租户"><el-option v-for="t in tenants" :key="t.id" :value="t.id" :label="t.name"/></el-select><el-button :disabled="!tenant" :loading="busy" @click="load()">刷新</el-button><el-alert v-if="error" :title="error" type="error" :closable="false"/><el-alert v-if="health?.failureDelivery!=='DATABASE'&&health" :title="`异常持久化状态：${health.failureDelivery}；${health.failureDeliveryType}。本地日志待导入或落库不可用，不可视为恢复。`" type="warning" :closable="false"/><admin-table table-key="control.operations.issues" :data="rows" border><el-table-column prop="job" label="任务 / 留存会话"/><el-table-column prop="first_seen" label="首次异常"/><el-table-column prop="last_seen" label="最近异常"/><el-table-column prop="attempts" label="失败或跳过次数"/><el-table-column label="复核状态"><template #default="s">{{s.row.last_review_id>s.row.latest_failure_id?'已复核，保留':'待处理 / 重试'}}</template></el-table-column><el-table-column label="动作"><template #default="s"><el-button link @click="review(s.row)">处理与复核留证</el-button></template></el-table-column></admin-table><el-button :disabled="page===0||busy" @click="page--;load()">上一页</el-button><el-button :disabled="rows.length<50||busy" @click="page++;load()">下一页</el-button></template>
