const {chromium}=require(process.env.PLAYWRIGHT_PATH||'C:/Users/徐乾妖/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});try{const page=await browser.newPage(),errors=[],requests=[];
const routes=['users','orders','deposit-review','deposit-orders','withdraw-review','loan-review','loan-personal-info-review','kyc-review','financial-orders','agents','agents/101/performance','statistics','inbox','announcement'];
await page.addInitScript(()=>{localStorage.setItem('admin_token','qa');localStorage.setItem('admin_user',JSON.stringify({id:1,userType:'admin',isSuperAdmin:true}))});page.on('pageerror',e=>{errors.push(page.url()+': '+e.message);console.log('PAGE ERROR',page.url(),e.stack)});
await page.route('**/api/**',async route=>{const req=route.request(),url=new URL(req.url());let p=url.pathname;if(p.endsWith('/menus/current'))return route.fulfill({json:{success:true,superAdmin:true,menus:routes.map((r,i)=>({id:i+1,menuCode:r.replaceAll('-','_'),menuName:r,path:'/'+r})),actions:Object.fromEntries(routes.map(r=>[r.replaceAll('-','_'),['*']])),groups:[]}});
if(p.endsWith('/account-query')){p=req.postDataJSON().path;requests.push(p)}
let json={success:true,list:[],total:0,content:[],totalElements:0,data:{chartData:{dates:[],depositAmounts:[],withdrawAmounts:[]}},count:0,groups:{},stats:{recordCount:0,totalYield:0,paidYield:0,pendingYield:0}};
if(p.includes('table-preferences')||['/api/admin/support/inbox','/api/admin/announcement/list','/api/admin/withdraw/list'].includes(p))json=[];
if(p.endsWith('/deposit/orders/permissions'))json={view_deposit_orders:true,export_deposit_orders:true,manual_deposit:true};
return route.fulfill({json});});
for(const route of routes){await page.goto('http://127.0.0.1:18089/'+route);if(route==='announcement')await page.getByText('活动公告 · 体验金',{exact:true}).click();const filter=page.locator('.account-type-filter').first();await filter.waitFor();assert.equal(await filter.getByRole('checkbox',{name:'真实账户',exact:true}).isChecked(),true,route);assert.equal(await filter.getByRole('checkbox',{name:'模拟账户',exact:true}).isChecked(),false,route);let before=requests.length;await filter.getByText('模拟账户',{exact:true}).click();for(let i=0;i<30&&requests.length===before;i++)await page.waitForTimeout(100);assert.ok(requests.length>before,route+' must query demo');console.log('PASS',route)}assert.deepEqual(errors,[]);console.log('PASS 14 routes, default REAL and DEMO request wiring, no page errors');}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
