// Run with node --test exchange-admin/tests/accountTable.test.cjs
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const ts=require('../node_modules/typescript'),vue=require('../node_modules/vue');
function load(name,deps={}) {const file=path.join(__dirname,'../src/utils',name+'.ts'),exports={};const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;new Function('require','exports',code)(name=>deps[name]||require(name),exports);return exports}
const data=load('accountTableData');
function setup(){const calls=[];let handler=async()=>({list:[],total:0});const request={get:async(p,c)=>{calls.push(['REAL',p,c?.params]);return handler('REAL',p,c?.params)},post:async(p,b)=>{const mode=p==='/admin/account-query'?'DEMO':'REAL';calls.push([mode,mode==='DEMO'?b.path:p,mode==='DEMO'?b.body||b.params:b]);return handler(mode,mode==='DEMO'?b.path:p,mode==='DEMO'?b.body||b.params:b)}};const {useAccountTable}=load('useAccountTable',{'vue':vue,'./request':{default:request},'./accountTableData':data});return {table:useAccountTable(),calls,handler:f=>handler=f,request}}
test('record realms do not contaminate monetary dictionaries',()=>{const r=data.tagRows({list:[{id:1}],groups:{USD:'0.10'},data:{depositGroupsUsd:{USD:'0.20'}}},'DEMO');assert.equal(r.list[0].accountMode,'DEMO');assert.deepEqual(r.groups,{USD:'0.10'});assert.equal(data.addDecimal('-0.10','0.20'),'0.10');assert.equal(data.addDecimal('9007199254740993.01','0.09'),'9007199254740993.10');assert.equal(data.mergeDepositSummary([r,r]).groups.USD,'0.20')});
test('same IDs remain two rows; stable union pagination',()=>{const a=data.tagRows({list:[{id:1,createdAt:'2026-01-01'}],total:1},'REAL'),b=data.tagRows({list:[{id:1,createdAt:'2026-01-01'}],total:1},'DEMO');assert.equal(data.mergeAccountLists([a,b]).list.length,2);assert.equal(data.mergeAccountLists([a,b],1,1).total,2);assert.equal(data.mergeAccountLists([a,b],1,1).list[0].accountMode,'REAL')});
test('CSV labels logical multiline records, one header',()=>{const csv='\uFEFFid,note\r\n1,"a\nb"\r\n2,"c""d"\r\n';assert.equal(data.realmCsv(csv,'REAL',true),'账户类型,id,note\r\n真实账户,1,"a\nb"\r\n真实账户,2,"c""d"\r\n');assert.ok(!data.realmCsv(csv,'DEMO',false).includes('账户类型'))});
test('default REAL, neither no network, both preserve all filters and merge pages',async()=>{const s=setup();assert.deepEqual(s.table.modes.value,['REAL']);await s.table.query('/admin/users/query',{keyword:'x',page:0,size:10},'POST');assert.equal(s.calls[0][0],'REAL');s.table.modes.value=[];assert.equal((await s.table.query('/admin/users/query')).total,0);assert.equal(s.calls.length,1);s.table.modes.value=['REAL','DEMO'];s.handler(async(mode,p,q)=>({list:Array.from({length:25},(_,i)=>({id:25-i,createdAt:'2026-01-01'})).slice(q.page*q.size,(q.page+1)*q.size),total:25}));const r=await s.table.query('/admin/users/query',{keyword:'x',page:1,size:10},'POST');assert.equal(r.total,50);assert.equal(r.list.length,10);assert.deepEqual(r.list.map(r=>r.id),[20,20,19,19,18,18,17,17,16,16]);assert.ok(s.calls.slice(1).every(c=>c[2].keyword==='x'))});
test('stale realm responses discarded; no fallback on demo failure',async()=>{const s=setup();let resolve;s.handler(()=>new Promise(r=>resolve=r));const old=s.table.query('/admin/users');s.table.modes.value=['DEMO'];resolve({list:[{id:1}],total:1});await assert.rejects(old,/账户筛选/);s.handler(async()=>{throw Error('offline')});await assert.rejects(s.table.query('/admin/users'),/offline/);assert.equal(s.calls.at(-1)[0],'DEMO')});
test('detail captures clicked realm and demo/mixed writes blocked',async()=>{const s=setup();s.table.selectRow({accountMode:'DEMO'});await s.table.detail('/admin/users/1');assert.equal(s.calls.at(-1)[0],'DEMO');const {accountTableRequest}=load('accountTableRequest',{'./request':{default:s.request},'./accountTableData':data});const client=accountTableRequest(s.table);await assert.rejects(client.post('/admin/users/1/status',{}),/仅供查看/);s.table.selectRow({accountMode:'REAL'});s.table.modes.value=['REAL','DEMO'];await assert.rejects(client.put('/admin/users/1',{}),/仅供查看/)});
