// Run against an isolated local admin Vite server with ADMIN_URL and EVIDENCE_DIR set.
const { chromium } = require(process.env.PLAYWRIGHT_PATH || 'playwright')
const assert = require('node:assert/strict'), fs = require('node:fs'), path = require('node:path')
const base = process.env.ADMIN_URL, out = process.env.EVIDENCE_DIR
if (!base || !out || !['127.0.0.1','localhost'].includes(new URL(base).hostname) || ['17050','17051','17052'].includes(new URL(base).port)) throw Error('Use an isolated local admin server and evidence directory')
fs.mkdirSync(out,{recursive:true})
const keys = ['registration','option','contract','financial','loan','activity','simulation','deposit','withdraw','support','external_support','inbox','agent']
const policy = (id, version, open, status = 'ACTIVE') => ({tenantId:id,tenantName:'QA '+id,status,policyVersion:version,features:Object.fromEntries(keys.map(key=>[key,open.includes(key)])),configs:[{key:'mail.password',locked:true,denied:false,version:2},{key:'share.templates',locked:true,denied:true,version:3}],supportChannel:id===2?'internal':null})
;(async () => {
 const browser = await chromium.launch({headless:true,...(process.env.CHROME_PATH ? {executablePath:process.env.CHROME_PATH} : {})})
 const page = await browser.newPage({viewport:{width:1500,height:1100}}), errors = [], requests = [], checks = []
 let first = policy(1,6,['option','contract','deposit','withdraw']), mode = 'normal', release
 page.on('pageerror',error=>errors.push(error.message))
 try {
  await page.addInitScript(()=>sessionStorage.setItem('exchange.admin.session.v2',JSON.stringify({mode:'admin',token:'QA1',user:{id:1,tenantId:1,userType:'admin',role:'admin'}})))
  await page.route('**/__qa',route=>route.fulfill({contentType:'text/html',body:'<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"></head><body><div id="app" style="padding:20px"></div></body></html>'}))
  await page.route('**/api/**',async route=>{
   const url=new URL(route.request().url()), method=route.request().method(), token=route.request().headers().authorization
   requests.push({method,path:url.pathname,tenant:token==='Bearer QA2'?2:1});assert.equal(method,'GET','feature information must never mutate business data')
   if(url.pathname==='/api/admin/menus/current')return route.fulfill({json:{success:true,menus:[{menuCode:'dashboard',path:'/dashboard'}],groups:[],actions:{dashboard:[]}}})
   if(url.pathname==='/api/admin/dashboard/stats')return route.fulfill({json:{success:true,data:{totalUsers:80,todayTransactions:12,todayAmount:2000,activeUsers:25}}})
   if(url.pathname==='/api/admin/dashboard/chart-data')return route.fulfill({json:{success:true,data:{dates:['2026-10-05','2026-10-06'],depositAmounts:[100,200],withdrawAmounts:[20,30]}}})
   assert.equal(url.pathname,'/api/admin/tenant-policies/dashboard','dashboard must not require settings access')
   if(token==='Bearer QA2')return route.fulfill({json:policy(2,12,['support','inbox'],'STOP_NEW')})
   if(mode==='failure')return route.fulfill({status:503,json:{message:'授权服务暂不可用'}})
   if(mode==='mismatch')return route.fulfill({json:{...first,tenantId:999}})
   const response=first
   if(mode==='slow')await new Promise(resolve=>{release=resolve})
   return route.fulfill({json:response})
  })
  await page.goto(base+'/__qa')
  await page.evaluate(async()=>{
   const overviewSource=await(await fetch('/src/components/TenantFeatureOverview.vue')).text(),source=await(await fetch('/src/views/Dashboard.vue')).text(),authSource=await(await fetch('/src/store/auth.ts')).text()
   const dep=(s,n)=>s.match(new RegExp('from ["\']([^"\']*'+n+'\\.js[^"\']*)["\']'))[1]
   const mainSource=await(await fetch('/src/main.ts')).text()
   const {createApp,h,ref}=await import(dep(source,'vue')),element=await import(dep(mainSource,'element-plus')),{createPinia,setActivePinia}=await import(dep(authSource,'pinia'))
   const icons=await import(dep(overviewSource,'@element-plus_icons-vue')),pinia=createPinia();setActivePinia(pinia)
   const {loadAccess,permissionDirective}=await import('/src/utils/access.ts');await loadAccess()
   const {useAuthStore}=await import('/src/store/auth.ts'),{default:Dashboard}=await import('/src/views/Dashboard.vue'),{default:Notice}=await import('/src/components/TenantPolicyNotice.vue')
   await import('/node_modules/element-plus/dist/index.css');await import('/src/styles/global.scss')
   const screen=ref('dashboard'),notice=ref({snapshot:{tenantId:1,features:{contract:true},configs:[],status:'ACTIVE',tenantName:'QA'},error:''})
   const app=createApp({render:()=>screen.value==='dashboard'?h(Dashboard):h(Notice,notice.value)}).use(pinia).use(element.default)
   for(const [name,component] of Object.entries(icons))app.component(name,component)
   app.directive('permission',permissionDirective);app.mount('#app')
   window.__qa={auth:useAuthStore(),screen,notice}
  })
  const cards=page.locator('.feature-card'), filters=page.locator('.feature-filters button')
  await cards.last().waitFor();assert.equal(await cards.count(),13);assert.equal(await page.locator('.feature-card.is-open').count(),4)
  assert.equal(await page.getByText('总控授权与逐项锁定',{exact:false}).count(),0);assert.equal(await page.getByText('80',{exact:true}).count(),1)
  checks.push('Dashboard shows all 13 functions, 4 open and 9 closed; original statistics retained')
  await filters.nth(1).click();assert.equal(await cards.count(),4);assert.equal(await page.locator('.feature-card.is-open').count(),4)
  await filters.nth(2).click();assert.equal(await cards.count(),9);assert.equal(await page.locator('.feature-card.is-open').count(),0)
  await filters.first().click()
  for(const key of keys){
   await page.locator(`[data-feature="${key}"]`).click();const dialog=page.getByRole('dialog');await dialog.waitFor()
   assert.ok((await dialog.locator('.feature-detail li').count())>=2,'each function has real feature detail')
   await dialog.getByText(key==='option'||key==='contract'||key==='deposit'||key==='withdraw'?'已开放':'未开放',{exact:true}).waitFor({state:'visible',timeout:5000});await page.waitForTimeout(350)
   if(key==='contract')await page.screenshot({path:path.join(out,'open-feature-detail.png')})
   if(key==='registration')await page.screenshot({path:path.join(out,'closed-feature-detail.png')})
   await dialog.getByRole('button',{name:'知道了',exact:true}).click();await dialog.waitFor({state:'hidden'})
  }
  checks.push('Open and unopened cards all show correct status and descriptions; modal close works')
  await page.locator('.config-scope summary').click();assert.equal(await page.locator('.config-list li').count(),2)
  assert.ok(await page.locator('.config-list').getByText('禁止修改',{exact:true}).isVisible());assert.ok(await page.locator('.config-list').getByText('统一锁定',{exact:true}).isVisible())
  await page.locator('.config-scope summary').click()
  await page.screenshot({path:path.join(out,'dashboard-desktop.png'),fullPage:true})
  first=policy(1,7,['option','contract','deposit','withdraw','loan']);await page.getByRole('button',{name:'刷新',exact:true}).click();await page.getByText('授权版本 7',{exact:true}).waitFor();assert.equal(await page.locator('.feature-card.is-open').count(),5)
  first=policy(1,8,[]);await page.getByRole('button',{name:'刷新',exact:true}).click();await page.getByText('授权版本 8',{exact:true}).waitFor();assert.equal(await page.locator('.feature-card.is-open').count(),0)
  await filters.nth(1).click();assert.equal(await cards.count(),0);await page.getByText('当前没有已开放的功能。',{exact:true}).waitFor();await filters.first().click()
  first=policy(1,9,keys);await page.getByRole('button',{name:'刷新',exact:true}).click();await page.getByText('授权版本 9',{exact:true}).waitFor();assert.equal(await page.locator('.feature-card.is-open').count(),13)
  await filters.nth(2).click();assert.equal(await cards.count(),0);await page.getByText('所有功能均已开放。',{exact:true}).waitFor();await filters.first().click()
  checks.push('All-open and all-unopened tenants retain complete lists, correct counts and empty-filter feedback')
  mode='failure';await page.getByRole('button',{name:'刷新',exact:true}).click();await page.getByText('授权服务暂不可用',{exact:true}).waitFor();assert.equal(await cards.count(),0)
  mode='mismatch';await page.getByRole('button',{name:'刷新',exact:true}).click();await page.getByText('租户策略响应无效',{exact:true}).waitFor();assert.equal(await cards.count(),0)
  mode='normal';await page.getByRole('button',{name:'刷新',exact:true}).click();await cards.last().waitFor()
  checks.push('Refresh updates status/version; errors and tenant mismatch show unknown, not fake unopened states; retry recovers')
  mode='slow';await page.getByRole('button',{name:'刷新',exact:true}).click();await page.locator('.el-skeleton').waitFor();assert.equal(await cards.count(),0)
  await page.evaluate(async()=>{window.__qa.auth.setAuth('QA2',{id:2,tenantId:2,userType:'admin',role:'admin'});await(await import('/src/utils/access.ts')).loadAccess()})
  await page.getByText('授权版本 12',{exact:true}).waitFor();assert.equal(await page.locator('.feature-card.is-open').count(),2)
  assert.ok(await page.locator('.business-status').getByText('当前状态：停止新增业务。',{exact:false}).isVisible());assert.ok(await page.getByText('客服渠道统一设置为：站内客服',{exact:true}).isVisible())
  release();await page.waitForTimeout(150);assert.equal(await page.locator('.feature-card.is-open').count(),2);assert.ok(await page.getByText('授权版本 12',{exact:true}).isVisible())
  checks.push('Session/tenant changes reload own snapshot; delayed old response cannot overwrite current tenant; status restriction remains explicit')
  await page.setViewportSize({width:390,height:844});await page.locator('.feature-overview').scrollIntoViewIfNeeded();await page.waitForTimeout(100)
  assert.ok(await page.locator('.feature-overview').evaluate(el=>el.scrollWidth<=el.clientWidth+1),'phone card has no horizontal overflow')
  assert.equal(await page.locator('.feature-grid').evaluate(el=>getComputedStyle(el).gridTemplateColumns.split(' ').length),1)
  await page.screenshot({path:path.join(out,'dashboard-mobile.png'),fullPage:true})
  await page.locator('[data-feature="registration"]').click();const mobileDialog=page.getByRole('dialog');await mobileDialog.waitFor();await mobileDialog.locator('.feature-detail').waitFor();await page.waitForTimeout(350)
  assert.ok(await mobileDialog.evaluate(el=>el.getBoundingClientRect().right<=innerWidth&&el.getBoundingClientRect().left>=0),'phone modal fits viewport')
  await page.screenshot({path:path.join(out,'mobile-feature-detail.png')});await mobileDialog.getByRole('button',{name:'知道了'}).click()
  checks.push('Mobile one-column cards and feature detail modal fit viewport')
  await page.evaluate(()=>window.__qa.screen.value='notice');await page.waitForTimeout(100);assert.equal(await page.locator('#app').innerText(),'','successful policy notice is removed from all shared callers')
  await page.evaluate(()=>window.__qa.notice.value={snapshot:null,error:''});await page.getByText('正在确认编辑权限，暂不可编辑',{exact:true}).waitFor()
  await page.evaluate(()=>window.__qa.notice.value={snapshot:null,error:'QA错误'});await page.getByText('权限信息加载失败，编辑已禁用：QA错误',{exact:true}).waitFor()
  checks.push('Other page notices render no normal policy panel but preserve loading/error warnings and fail-closed edit behavior')
  assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'result.json'),JSON.stringify({checks,errors,requests},null,2));console.log('PASS '+checks.join('; '))
 } catch(error){await page.screenshot({path:path.join(out,'failure.png')}).catch(()=>{});throw error}
 finally {if(release)release();await browser.close()}
})().catch(error=>{console.error(error);process.exitCode=1})
