// Isolated real Vue/Element Plus component; APIs mocked, never creates an order or changes funds.
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path')
const base=process.env.ADMIN_URL,out=process.env.EVIDENCE_DIR
if(!base||!out||!['127.0.0.1','localhost'].includes(new URL(base).hostname))throw Error('Use an isolated local server and evidence directory')
fs.mkdirSync(out,{recursive:true})
;(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})}),page=await browser.newPage({viewport:{width:1360,height:900}})
 const errors=[],requests=[],chartRequests=[],checks=[];let pending=false,blocked=false,release,block=false
 const amountOf=(quantity,numerator,denominator=100n)=>{const [whole,fraction='']=String(quantity).split('.'),product=BigInt(whole+fraction.padEnd(16,'0'))*numerator,rounded=((product<0n?-product:product)+denominator/2n)/denominator,digits=rounded.toString().padStart(17,'0'),decimals=digits.slice(-16).replace(/0+$/,'');return(product<0n?'-':'')+digits.slice(0,-16)+(decimals?'.'+decimals:'')}
 page.on('pageerror',e=>errors.push(e.message))
 const generate=()=>page.getByRole('button',{name:'一键生成',exact:true}),target=()=>page.getByRole('textbox',{name:'净收益',exact:true}),confirm=()=>page.getByRole('button',{name:'确认创建',exact:true})
 const choose=async()=>{await page.getByRole('combobox',{name:'品种',exact:true}).click();await page.getByRole('option',{name:'FIXTUREUSD · local fixture',exact:true}).click()}
 try{
  await page.addInitScript(()=>sessionStorage.setItem('exchange.admin.session.v2',JSON.stringify({mode:'admin',token:'QA',user:{id:1,tenantId:1,userType:'admin',role:'super_admin',account:'QA'}})))
  await page.route('**/__qa',r=>r.fulfill({contentType:'text/html',body:'<!doctype html><html lang="zh-CN"><meta charset="utf-8"><div id="app"></div></html>'}))
  await page.route('**/api/**',async route=>{
   const request=route.request(),url=new URL(request.url())
   if(url.pathname==='/api/admin/menus/current'){assert.equal(request.method(),'GET');return route.fulfill({json:{success:true,superAdmin:true,menus:[{menuCode:'orders',path:'/orders'}],groups:[],actions:{orders:['manual_order']}}})}
   if(url.pathname.endsWith('/manual/context')){assert.equal(request.method(),'GET');return route.fulfill({json:{users:[],symbols:[{symbol:'FIXTUREUSD',name:'local fixture',quantity_unit_type:'LOT',spec_version:1,quantity_step:'0.01',min_order_quantity:'0.01',max_leverage:'100'},{symbol:'OTHERUSD',name:'another instrument',quantity_unit_type:'LOT',spec_version:1,quantity_step:'0.01',min_order_quantity:'0.01',max_leverage:'100'}],timezone:'UTC'}})}
   if(url.pathname.endsWith('/manual/chart')){
    assert.equal(request.method(),'GET');assert.equal(url.searchParams.get('symbol'),'FIXTUREUSD');assert.equal(url.searchParams.get('limit'),'200');chartRequests.push(Object.fromEntries(url.searchParams))
    const to=Math.floor(Date.now()/60000)*60000,from=to-200*60000,candles=Array.from({length:200},(_,i)=>{const timestamp=from+i*60000;return {timestamp,local:new Date(timestamp).toISOString().slice(0,16),offset:'Z',price:String((99500+i)/1000),low:'99',high:'101',close:'100'}})
    return route.fulfill({json:{candles,from,to,hasMore:false,status:'available',pending:false,source:'local fixture'}})
   }
   assert.equal(url.pathname,'/api/admin/orders/contract/manual/simple/generate','No create, binding, wallet or market write request is allowed');assert.equal(request.method(),'POST')
   const payload=request.postDataJSON();requests.push(payload);assert.equal(payload.walletEnabled,false);assert.equal(payload.historyEnabled,false)
   if(pending){pending=false;return route.fulfill({status:425,json:{code:425,message:'所需分钟行情或换算率尚未就绪'}})}
   if(payload.openPrice===payload.closePrice&&Number(payload.targetNet)>0)return route.fulfill({status:400,json:{code:400,message:'固定开平仓价格和方向无法产生正净收益；增加手数不能解决；未创建订单或修改资金'}})
   if(!payload.allowNetAdjustment)return route.fulfill({status:400,json:{code:422,message:'严格净收益须精确相等，当前合法步长没有匹配解'}})
   if(block){blocked=true;await new Promise(resolve=>release=resolve);blocked=false;release=undefined}else await new Promise(resolve=>setTimeout(resolve,250))
   const quantity=payload.quantity??'112697.96',side=payload.side??'BUY',net=amountOf(quantity,side==='SELL'?-51n:49n)
   const response={request:{...payload,leverage:'100',side,driver:'QUANTITY',input:quantity,simpleMode:true},quotes:{openPrice:'99.5',closePrice:'100',openRate:'1',closeRate:'1',marginRate:'99.5',openLow:'99',openHigh:'101',closeLow:'99',closeHigh:'101',source:'local fixture'},lotSize:'1',feePerLot:'0.01',quantityStep:'0.01',minOrderQuantity:'0.01',minOrderNotional:'0',calculation:{quantity,net,fee:amountOf(quantity,1n),margin:amountOf(quantity,995n,1000n)},previewToken:'isolated-preview',openUtc:'2026-10-05T10:00:00Z',closeUtc:'2026-10-05T10:21:00Z',walletBefore:null,walletAfter:null,generation:{difference:payload.quantity?'0':'0.0004',errorPercent:payload.quantity?'0':'0.0000007243',originalConditions:{targetNet:payload.targetNet}}}
   await route.fulfill({json:response}).catch(()=>{})
  })
  await page.goto(base+'/__qa')
  await page.evaluate(async()=>{
   const source=await(await fetch('/src/components/SimpleManualContractOrder.vue')).text(),authSource=await(await fetch('/src/store/auth.ts')).text(),dep=(s,n)=>s.match(new RegExp('from ["\']([^"\']*'+n+'\\.js[^"\']*)["\']'))[1]
   const {createApp}=await import(dep(source,'vue')),{createPinia,setActivePinia}=await import(dep(authSource,'pinia')),element=await import(dep(source,'element-plus'))
   const pinia=createPinia();setActivePinia(pinia);const {permissionDirective,loadAccess}=await import('/src/utils/access.ts');await loadAccess()
   await import('/node_modules/element-plus/dist/index.css');await import('/src/styles/global.scss')
   window.mountManual=async(name='SimpleManualContractOrder')=>{window.manualApp?.unmount();const {default:Form}=await import('/src/components/'+name+'.vue');window.manualApp=createApp(Form).use(pinia).use(element.default).directive('permission',permissionDirective);window.manual=window.manualApp.mount('#app');await window.manual.open()}
   await window.mountManual()
  })
  const picker=()=>page.getByRole('dialog',{name:'选择图表品种',exact:true}),chartToggle=()=>page.getByRole('button',{name:'图表选择开平仓',exact:true})
  assert.ok(await chartToggle().isEnabled());await chartToggle().click();await picker().waitFor();assert.ok(await picker().getByRole('button',{name:'打开图表',exact:true}).isDisabled());assert.equal(chartRequests.length,0)
  await picker().getByRole('button',{name:'取消',exact:true}).click();await picker().waitFor({state:'hidden'});assert.equal(await page.getByRole('combobox',{name:'品种',exact:true}).inputValue(),'');assert.ok(await page.locator('.simple-order-dialog').isVisible());assert.equal(chartRequests.length,0);checks.push('A blank form allows opening the symbol picker directly; cancellation preserves the form and makes no chart or generation request')
  await chartToggle().click();await picker().waitFor();await page.screenshot({path:path.join(out,'chart-symbol-picker-desktop.png'),animations:'disabled'})
  const symbolSearch=()=>picker().getByRole('combobox',{name:'图表品种',exact:true});await symbolSearch().fill('nothing-matches');assert.equal(await page.getByRole('option').count(),0);await symbolSearch().fill('local fixture');await page.getByRole('option',{name:'FIXTUREUSD · local fixture',exact:true}).click();await picker().getByRole('button',{name:'打开图表',exact:true}).click();await picker().waitFor({state:'hidden'});await page.getByText(/已显示 200 根/).waitFor();assert.equal(chartRequests.length,1);assert.equal(requests.length,0);assert.match(await page.getByRole('combobox',{name:'品种',exact:true}).evaluate(el=>el.closest('.el-select__wrapper').textContent),/FIXTUREUSD · local fixture/);assert.equal(await page.locator('.candles canvas').count(),1);checks.push('Code/name search selects the same configured symbol as the order form and automatically opens one bounded 200-minute chart read')
  await page.locator('.candles').focus();await page.keyboard.press('ArrowLeft');assert.equal(await page.getByRole('textbox',{name:'开仓价格',exact:true}).inputValue(),'99.698');assert.equal(await page.getByRole('textbox',{name:'平仓价格',exact:true}).inputValue(),'99.699');assert.ok(await confirm().isDisabled());assert.equal(requests.length,0);checks.push('The directly opened chart retains keyboard time/price selection without creating an order or changing funds')
  await page.getByRole('button',{name:'收起图表',exact:true}).click();await chartToggle().click();await page.getByText(/已显示 200 根/).waitFor();assert.equal(await picker().count(),0);assert.equal(chartRequests.length,2);await page.getByRole('button',{name:'收起图表',exact:true}).click();checks.push('An already selected symbol opens its chart directly, without another dialog')
  await choose();await page.getByRole('textbox',{name:'开仓价格',exact:true}).fill('100');await page.getByRole('textbox',{name:'平仓价格',exact:true}).fill('100');await target().fill('55222')
  let start=Date.now();await generate().click();await page.getByText(/增加手数不能解决/).waitFor();assert.ok(Date.now()-start<1500);assert.ok(await confirm().isDisabled());checks.push('Impossible flat prices show an immediate actionable failure and never enable creation')
  await page.getByRole('textbox',{name:'开仓价格',exact:true}).fill('99.5');pending=true;const count=requests.length;await generate().click();await page.getByText(/已有输入保留/).waitFor();await page.waitForTimeout(1700);assert.equal(requests.length,count+1);assert.equal(await target().inputValue(),'55222');assert.ok(await confirm().isDisabled());checks.push('Missing historical data returns control immediately, preserves inputs and does not issue twenty full-search retries')
  start=Date.now();await generate().click();await page.getByText(/目标 55222，实际 55222.0004/).waitFor();const previewMs=Date.now()-start
  assert.ok(previewMs<1500);assert.equal(await target().inputValue(),'55222.0004');assert.equal(await page.getByRole('textbox',{name:'手数',exact:true}).inputValue(),'112697.96');assert.ok(await confirm().isEnabled());assert.equal(requests.at(-1).targetNet,'55222');checks.push('Nearest valid lots and actual net replace displayed values, while the original target and tolerance remain fixed')
  await generate().click();await page.getByText(/目标 55222，实际 55222.0004/).waitFor();assert.equal(requests.at(-1).targetNet,'55222');checks.push('Generating again retains the original target instead of repeatedly shifting its tolerance range')
  await page.getByText('允许调整',{exact:true}).click();await generate().click();await page.getByText(/严格净收益须精确相等/).waitFor();assert.ok(await confirm().isDisabled());assert.equal(requests.at(-1).netTolerance,'0');checks.push('Strict mode still rejects a rounded approximate result and keeps creation disabled')
  await page.getByText('允许调整',{exact:true}).click();block=true;await generate().click();while(!blocked)await page.waitForTimeout(20)
  await page.locator('.simple-order-dialog .el-dialog__headerbtn').click();await page.locator('.simple-order-dialog').waitFor({state:'hidden'});release();block=false;await page.evaluate(()=>window.manual.open());await choose()
  assert.equal(await page.locator('.simple-result:visible').count(),0);assert.ok(await confirm().isDisabled());checks.push('Closing the dialog cancels the in-flight generation and rejects its stale preview after reopening')
  const lots=()=>page.getByRole('textbox',{name:'手数',exact:true})
  await lots().fill('2');assert.equal(await target().inputValue(),'');await lots().fill('');checks.push('A reopened form does not reuse another trade’s stale prices or exchange rates for quantity estimates')
  await page.getByRole('textbox',{name:'开仓价格',exact:true}).fill('99.5');await page.getByRole('textbox',{name:'平仓价格',exact:true}).fill('100');await target().fill('55222');await generate().click();await page.getByText(/目标 55222，实际 55222.0004/).waitFor()
  const beforeEdit=requests.length;await lots().fill('2');assert.equal(await target().inputValue(),'0.98');assert.ok(await confirm().isDisabled());assert.equal(requests.length,beforeEdit);await page.getByText(/已按当前价格、方向、手续费和汇率同步估算/).waitFor();checks.push('Typing lots synchronizes fee-inclusive net immediately and invalidates the old signed preview without any request')
  await lots().fill('3');await page.locator('.simple-order-form .el-slider [role="slider"]').press('ArrowRight');assert.equal(await lots().inputValue(),'3.01');assert.equal(await target().inputValue(),'1.4749');assert.equal(requests.length,beforeEdit);checks.push('The quantity slider uses the same exact net synchronization as typed lots')
  for(const value of ['1.001','0','']){await lots().fill(value);assert.equal(await target().inputValue(),'');assert.ok(await confirm().isDisabled())}checks.push('Invalid, off-step and cleared quantities cannot leave a stale positive net or enable confirmation')
  await lots().fill('150');assert.equal(await target().inputValue(),'73.5');await page.locator('.simple-order-form .el-select__wrapper').filter({has:page.getByRole('combobox',{name:'方向',exact:true})}).click();await page.getByText('做空',{exact:true}).click();assert.equal(await target().inputValue(),'-76.5');await page.locator('.simple-order-form .el-select__wrapper').filter({has:page.getByRole('combobox',{name:'方向',exact:true})}).click();await page.getByText('做多',{exact:true}).click();assert.equal(await target().inputValue(),'73.5');checks.push('Quantities above 100 remain unchanged and switching side recalculates real signed profit including fees')
  await generate().click();await page.getByText(/目标 73.5，实际 73.5/).waitFor();assert.equal(requests.at(-1).quantity,'150');assert.equal(requests.at(-1).targetNet,'73.5');assert.equal(requests.at(-1).openPrice,'99.5');assert.equal(requests.at(-1).closePrice,'100');assert.equal(requests.at(-1).openTime,Date.parse('2026-10-05T10:00:00Z'));assert.equal(requests.at(-1).closeTime,Date.parse('2026-10-05T10:21:00Z'));assert.ok(await confirm().isEnabled());assert.equal(await page.getByText(/已按当前价格、方向、手续费和汇率同步估算/).count(),0);checks.push('Regeneration validates the updated lots/net against the original exact minutes and prices before enabling creation')
  await page.locator('.el-message').first().waitFor({state:'hidden'});await page.screenshot({path:path.join(out,'simple-speed-desktop.png')})
  await page.setViewportSize({width:390,height:844});await page.waitForTimeout(200);assert.ok(await page.locator('.simple-order-dialog').evaluate(el=>el.scrollWidth<=el.clientWidth+1));await page.screenshot({path:path.join(out,'simple-speed-mobile.png')});checks.push('Desktop and mobile preserve all controls and adjusted-result detail')
  await page.locator('.simple-order-dialog .el-dialog__headerbtn').click();await page.locator('.simple-order-dialog').waitFor({state:'hidden'});await page.evaluate(()=>window.manual.open());await chartToggle().click();await picker().waitFor();assert.ok(await picker().evaluate(el=>el.scrollWidth<=el.clientWidth+1&&el.getBoundingClientRect().right<=innerWidth&&el.getBoundingClientRect().left>=0));await page.screenshot({path:path.join(out,'chart-symbol-picker-mobile.png'),animations:'disabled'});await page.keyboard.press('Escape');await picker().waitFor({state:'hidden'});assert.ok(await page.locator('.simple-order-dialog').isVisible());assert.equal(await page.getByRole('combobox',{name:'品种',exact:true}).inputValue(),'');checks.push('The mobile symbol dialog fits the viewport and Escape closes only the picker, preserving the parent order form')
  await page.setViewportSize({width:1360,height:900});await page.evaluate(()=>window.mountManual('ManualContractOrder'));await chartToggle().click();await picker().waitFor();await symbolSearch().fill('FIXTUREUSD');await page.getByRole('option',{name:'FIXTUREUSD · local fixture',exact:true}).click();const advancedCount=chartRequests.length;await picker().getByRole('button',{name:'打开图表',exact:true}).click();await picker().waitFor({state:'hidden'});await page.getByText(/已显示 200 根/).waitFor();assert.equal(chartRequests.length,advancedCount+1);assert.equal(await page.locator('.candles canvas').count(),1);checks.push('The advanced order form shares the same symbol-first chart flow, without changing its numeric-target driver rules')
  assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'browser-result.json'),JSON.stringify({checks,previewMs,requests,chartRequests,errors,mockedApis:true},null,2));console.log('PASS '+checks.join('; '))
 }catch(e){await page.screenshot({path:path.join(out,'browser-failure.png')}).catch(()=>{});throw e}finally{if(release)release();await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1})
