package com.gtcfesk.exchange.insights;

import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.gtcfesk.exchange.insights.traders.*;
import com.gtcfesk.exchange.insights.news.*;
import com.gtcfesk.exchange.common.JwtUtil;
import com.gtcfesk.exchange.admin.*;
import com.gtcfesk.exchange.entity.*;
import com.gtcfesk.exchange.repository.*;
import com.gtcfesk.exchange.tenant.*;
import com.gtcfesk.exchange.simulation.SimulationEnvironment;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.*;
import org.springframework.boot.web.server.LocalServerPort;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.web.servlet.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.mock.web.MockMultipartFile;
import java.time.*;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.*;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;

/** Real MVC/JWT/menu/SQL on an isolated database; TEST_ONLY manual inputs are not real performance evidence. */
@org.springframework.context.annotation.Import(BootTenantFixture.class)
@org.junit.jupiter.api.extension.ExtendWith(TenantOneFixture.class)
@TestPropertySource(properties={"file.storage=local","spring.sql.init.mode=always","spring.sql.init.schema-locations=classpath:multitenant-market-test.sql","spring.redis.host=127.0.0.1","spring.redis.port=1","spring.redis.password=","platform.base-domain=mt705.test","platform.admin-origin=https://admin.mt705.test","platform.control-origin=https://control.mt705.test","security.trusted-proxies=127.0.0.1","market.exchange.stream-enabled=false","market.depth.enabled=false","calendar.sync.enabled=false","calendar.reminders.enabled=false","news.sync.enabled=false","news.gdelt.enabled=false","news.newsdata.key=","news.newsdata.license-approved=false","simulation.enabled=false","file.upload-dir=../reports/traders-20261003/test-uploads"})
@SpringBootTest(classes=CalendarIntegrationTest.App.class,webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT,properties={"spring.datasource.url=jdbc:h2:mem:traders_stage4_demo;MODE=MySQL;DB_CLOSE_DELAY=-1","spring.datasource.driver-class-name=org.h2.Driver","spring.datasource.username=sa","spring.datasource.password=","spring.jpa.hibernate.ddl-auto=update","spring.jpa.show-sql=false","spring.jpa.open-in-view=false","logging.level.root=ERROR","jwt.secret=dHJhZGVyLXRlc3Qtb25seS1ub3QtcHJvZHVjdGlvbi1zZWNyZXQ="})
@AutoConfigureMockMvc(print=org.springframework.boot.test.autoconfigure.web.servlet.MockMvcPrint.NONE)
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class TraderIntegrationTest {
    @MockBean com.gtcfesk.exchange.market.ForexQuoteMarketService quotes;
    @MockBean com.gtcfesk.exchange.market.MarketInstrumentCatalog catalog;
    @MockBean com.gtcfesk.exchange.market.MarketOrderProcessor processor;
    @MockBean com.gtcfesk.exchange.market.RedisMarketService redis;
    @MockBean com.gtcfesk.exchange.service.EmailService email;
    @MockBean com.gtcfesk.exchange.security.RegistrationSecurity registration;
    @SpyBean SimulationEnvironment simulation;
    @Autowired TraderService service; @Autowired MockMvc mvc; @Autowired ObjectMapper json; @Autowired JdbcTemplate db;
    @Autowired AdminUserRepository admins; @Autowired AdminRoleRepository roles; @Autowired AdminRoleMenuRepository grants; @Autowired AdminMenuRepository menus; @Autowired JwtUtil jwt;
    @Autowired com.gtcfesk.exchange.control.BackendLoginRegistry names; @LocalServerPort int port;
    String writer,reader,denied,editor,tenantTwo; static final String API="/api/admin/insights/traders",PUBLIC="/api/insights/traders";
    static final Path REPORTS=Paths.get("../reports/traders-20261003");
    String admin(String role){AdminUser a=new AdminUser();a.setAccount("trader_qa_"+UUID.randomUUID());a.setEmail(a.getAccount()+"@example.invalid");a.setRole(role);a.setEnabled(true);a.setPasswordHash("TEST_ONLY");a.setCurrentToken(UUID.randomUUID().toString());a=admins.saveAndFlush(a);names.register("ADMIN",a.getId(),a.getAccount());Map<String,Object> claims=new HashMap<>();claims.put("userType","admin");claims.put("sid",a.getCurrentToken());claims.put("credential",jwt.credentialKey(a.getPasswordHash()));return jwt.generateToken("admin-"+a.getId(),claims);}
    String limited(String... codes){AdminRole r=new AdminRole();r.setRoleCode("trader_"+UUID.randomUUID().toString().substring(0,8));r.setRoleName(r.getRoleCode());r.setStatus("active");r=roles.saveAndFlush(r);for(String code:codes){AdminRoleMenu g=new AdminRoleMenu();g.setRoleId(r.getId());g.setMenuId(menus.findByMenuCode(code).get().getId());grants.saveAndFlush(g);}return admin(r.getRoleCode());}
    @BeforeEach void initialize()throws Exception {
        try(java.sql.Connection c=db.getDataSource().getConnection()){assertTrue(c.getMetaData().getURL().startsWith("jdbc:h2:mem:traders_stage4_demo"));}
        doReturn(false).when(simulation).enabled();db.update("DELETE FROM trader_equity");db.update("DELETE FROM trader_history");db.update("DELETE FROM trader_profile");db.update("DELETE FROM trader_audit");
        writer=admin("super_admin");reader=limited("traders");denied=limited();editor=limited("traders","traders:edit");TenantContext.clear();try(TenantContext.Scope ignored=TenantContext.open(2L)){tenantTwo=admin("super_admin");}finally{TenantContext.open(1L);}Files.createDirectories(REPORTS);
    }
    MvcResult send(String method,String path,String token,Object body)throws Exception{org.springframework.test.web.servlet.request.MockHttpServletRequestBuilder r=method.equals("GET")?get(path):method.equals("PUT")?put(path):method.equals("DELETE")?delete(path):post(path);if(token!=null)r.header("Authorization","Bearer "+token);if(body!=null)r.contentType("application/json").content(json.writeValueAsString(body));return mvc.perform(r).andReturn();}
    MvcResult sendDemo(String method,String path,String token,Object body)throws Exception{org.springframework.test.web.servlet.request.MockHttpServletRequestBuilder r=method.equals("GET")?get(path):method.equals("PUT")?put(path):method.equals("DELETE")?delete(path):post(path);r.header("X-Account-Mode","DEMO");if(token!=null)r.header("Authorization","Bearer "+token);if(body!=null)r.contentType("application/json").content(json.writeValueAsString(body));return mvc.perform(r).andReturn();}
    JsonNode ok(MvcResult r)throws Exception{assertEquals(200,r.getResponse().getStatus(),r.getResponse().getContentAsString(java.nio.charset.StandardCharsets.UTF_8));return json.readTree(r.getResponse().getContentAsByteArray());}
    ObjectNode data(){ObjectNode d=json.createObjectNode();d.put("name","TEST_ONLY 展示人物，长中文与长英文 Strategy Research");d.put("bio","隔离演示；非真实用户或业绩");d.put("currency","USD");d.put("sourceType","ADMIN_CURATED");d.putArray("strategyTags").add("趋势研究");d.put("statisticStart","2026-09-01T00:00:00Z");d.put("statisticEnd","2026-09-30T00:00:00Z");d.put("sourceNote","TEST_ONLY 合法人工演示材料");d.put("metricBasisNote","人工维护，仅完整统计期，不计算策略收益");d.put("riskNote","历史表现不保证未来收益；此处为演示");d.put("authorizationNote","TEST_ONLY 隔离素材授权；不公开内部记录");d.put("pointIntervalHours",24);return d;}
    Map<String,Object> write(JsonNode p){Map<String,Object> b=new LinkedHashMap<>();b.put("rowVersion",p.path("rowVersion").asLong());b.put("reason","TEST_ONLY 隔离验收依据");return b;}
    JsonNode create()throws Exception{Map<String,Object> b=new HashMap<>();b.put("data",data());b.put("reason","TEST_ONLY 创建演示人物");return ok(send("POST",API,writer,b));}
    JsonNode detail(String id)throws Exception{return ok(send("GET",API+"/"+id,writer,null));}
    JsonNode publish(JsonNode p)throws Exception{Map<String,Object> b=write(p);b.put("status","PUBLISHED");return ok(send("PUT",API+"/"+p.path("traderId").asText()+"/publication",writer,b));}
    Map<String,Object> point(String at,String value){Map<String,Object> d=new LinkedHashMap<>();d.put("pointAt",at);d.put("netAsset",value);d.put("currency","USD");d.put("cashFlow",null);return d;}
    Map<String,Object> record(String key,String at){Map<String,Object> d=new LinkedHashMap<>();d.put("recordKey",key);d.put("closedAt",at);d.put("symbol","BTCUSDT");d.put("direction","LONG");d.put("currency","USD");d.put("pnlBasis","NOT_PROVIDED");d.put("evidenceNote","TEST_ONLY 内部资料不得公开");return d;}
    JsonNode child(JsonNode p,String kind,Object d)throws Exception{Map<String,Object> b=write(p);b.put("data",d);return ok(send("POST",API+"/"+p.path("traderId").asText()+"/"+kind,writer,b));}
    @Test @Order(1) void draftPreviewPublicationOffliningDisableAndNoCache()throws Exception {
        JsonNode p=create();String id=p.path("traderId").asText();assertEquals("DRAFT",p.path("status").asText());assertEquals(404,send("GET",PUBLIC+"/"+id,null,null).getResponse().getStatus());assertEquals(0,ok(send("GET",PUBLIC,null,null)).path("totalElements").asInt());JsonNode v=ok(send("GET",API+"/"+id+"/preview",reader,null));assertTrue(v.path("preview").asBoolean());assertFalse(v.toString().contains("authorizationNote"));p=publish(p);MvcResult publicResult=send("GET",PUBLIC+"/"+id,null,null);assertEquals("no-store",publicResult.getResponse().getHeader("Cache-Control"));JsonNode visible=ok(publicResult);assertEquals("ADMIN_CURATED",visible.path("sourceType").asText());assertEquals("UNVERIFIED",visible.path("verificationStatus").asText());assertNull(visible.get("authorizationNote"));assertNull(visible.get("data"));assertTrue(visible.path("manualRoi").isNull());assertFalse(visible.path("performanceRankingAvailable").asBoolean());json.writeValue(REPORTS.resolve("api-profile.json").toFile(),visible);
        Map<String,Object> b=write(p);b.put("status","OFFLINE");p=ok(send("PUT",API+"/"+id+"/publication",writer,b));assertEquals(404,send("GET",PUBLIC+"/"+id+"/equity",null,null).getResponse().getStatus());b=write(p);b.put("disabled",true);p=ok(send("PUT",API+"/"+id+"/disable",writer,b));assertEquals("DISABLED",p.path("status").asText());b=write(p);b.put("status","PUBLISHED");assertEquals(400,send("PUT",API+"/"+id+"/publication",writer,b).getResponse().getStatus());b=write(p);b.put("disabled",false);assertEquals("DRAFT",ok(send("PUT",API+"/"+id+"/disable",writer,b)).path("status").asText());
    }
    @Test @Order(2) void roleAndActionPermissionsCannotWriteStatusOrReadDrafts()throws Exception {
        JsonNode p=create();String id=p.path("traderId").asText();assertEquals(401,send("GET",API,null,null).getResponse().getStatus());assertEquals(403,send("GET",API+"/"+id,denied,null).getResponse().getStatus());ok(send("GET",API+"/"+id+"/preview",reader,null));Map<String,Object> b=write(p);b.put("status","PUBLISHED");for(String token:Arrays.asList(reader,editor))assertEquals(403,send("PUT",API+"/"+id+"/publication",token,b).getResponse().getStatus());b=write(p);b.put("data",data());assertEquals(403,send("PUT",API+"/"+id,reader,b).getResponse().getStatus());ok(send("PUT",API+"/"+id,editor,b));assertEquals(403,send("POST",API+"/"+id+"/equity",reader,b).getResponse().getStatus());assertEquals(401,send("POST",PUBLIC,null,b).getResponse().getStatus());assertEquals(403,send("GET",API+"/audit",denied,null).getResponse().getStatus());
    }
    @Test @Order(3) void tenantAndRealDemoIsolationCannotBeSelectedByParameters()throws Exception {
        JsonNode p=publish(create());String id=p.path("traderId").asText();assertEquals(404,send("GET",API+"/"+id,tenantTwo,null).getResponse().getStatus());ObjectNode demo=data();demo.put("sourceType","DEMO");Map<String,Object> b=new HashMap<>();b.put("data",demo);b.put("reason","TEST_ONLY");assertEquals(400,send("POST",API,writer,b).getResponse().getStatus());
        doReturn(true).when(simulation).enabled();assertEquals(404,sendDemo("GET",PUBLIC+"/"+id+"?environment=REAL&tenantId=1",null,null).getResponse().getStatus());assertEquals(0,ok(sendDemo("GET",PUBLIC,null,null)).path("totalElements").asInt());assertEquals(409,send("GET",API,writer,null).getResponse().getStatus());
        // Preserve the existing DEMO identity boundary: it intentionally has no local admin HTTP writes.
        // Only a trusted test fixture exercises the DEMO service; this is not an HTTP admin bypass.
        org.springframework.security.core.context.SecurityContextHolder.getContext().setAuthentication(new org.springframework.security.authentication.UsernamePasswordAuthenticationToken("TEST_ONLY",null,Collections.singletonList(new org.springframework.security.core.authority.SimpleGrantedAuthority("ROLE_SUPER_ADMIN"))));
        String demoId;try{TraderData.Edit input=new TraderData.Edit();input.data=json.treeToValue(demo,TraderData.class);input.reason="TEST_ONLY DEMO service fixture";Map<String,Object> created=service.create(input);demoId=(String)created.get("traderId");TraderData.Change publication=new TraderData.Change();publication.rowVersion=((Number)created.get("rowVersion")).longValue();publication.reason="TEST_ONLY DEMO service fixture";publication.status="PUBLISHED";service.publication(demoId,publication);}finally{org.springframework.security.core.context.SecurityContextHolder.clearContext();}
        assertEquals("DEMO",ok(sendDemo("GET",PUBLIC+"/"+demoId,null,null)).path("sourceType").asText());doReturn(false).when(simulation).enabled();assertEquals(404,send("GET",PUBLIC+"/"+demoId,null,null).getResponse().getStatus());assertEquals(1,ok(send("GET",PUBLIC,null,null)).path("totalElements").asInt());
    }
    @Test @Order(4) void metadataValidationRejectsVerifiedPrivateAssetsUnknownUnitsAndFuturePublication()throws Exception {
        for(String invalid:Arrays.asList("VERIFIED_PLATFORM","UNKNOWN")){ObjectNode d=data();d.put("sourceType",invalid);assertEquals(400,send("POST",API,writer,Collections.singletonMap("data",d)).getResponse().getStatus());}
        ObjectNode d=data();d.put("manualWinRate","101");Map<String,Object> b=new HashMap<>();b.put("data",d);b.put("reason","TEST_ONLY");assertEquals(400,send("POST",API,writer,b).getResponse().getStatus());d=data();d.put("avatarUrl","/api/uploads/images/1/user/123/private.png");b.put("data",d);assertEquals(400,send("POST",API,writer,b).getResponse().getStatus());d.put("avatarUrl","https://example.invalid/avatar.jpg");assertEquals(400,send("POST",API,writer,b).getResponse().getStatus());d=data();d.put("name","<script>bad</script>");b.put("data",d);assertEquals(400,send("POST",API,writer,b).getResponse().getStatus());d=data();d.put("statisticEnd","2099-01-01T00:00:00Z");b.put("data",d);assertEquals(400,send("POST",API,writer,b).getResponse().getStatus());
        JsonNode p=create();d=(ObjectNode)p.path("data");d.putNull("authorizationNote");b=write(p);b.put("data",d);p=ok(send("PUT",API+"/"+p.path("traderId").asText(),writer,b));b=write(p);b.put("status","PUBLISHED");assertEquals(400,send("PUT",API+"/"+p.path("traderId").asText()+"/publication",writer,b).getResponse().getStatus());
    }
    @Test @Order(5) void equityCrudGapsZeroBasePreciseDecimalAndNoDerivedStrategyReturn()throws Exception {
        JsonNode p=create();String id=p.path("traderId").asText();assertEquals("NONE",ok(send("GET",API+"/"+id+"/equity",reader,null)).path("curveStatus").asText());JsonNode c=child(p,"equity",point("2026-09-01T00:00:00Z","0"));p=c.path("profile");assertEquals("INSUFFICIENT",ok(send("GET",API+"/"+id+"/equity",reader,null)).path("curveStatus").asText());c=child(p,"equity",point("2026-09-02T00:00:00Z","1000"));p=c.path("profile");c=child(p,"equity",point("2026-09-05T00:00:00Z","2000"));p=publish(c.path("profile"));JsonNode curve=ok(send("GET",PUBLIC+"/"+id+"/equity?size=2",null,null));assertEquals("ZERO_BASE",curve.path("curveStatus").asText());assertTrue(curve.path("unknownCashFlows").asBoolean());assertTrue(curve.path("strategyReturn").isNull());assertEquals(1,curve.path("gapCount").asInt());assertEquals(3,curve.path("totalElements").asInt());assertTrue(curve.path("content").get(1).path("gapAfter").asBoolean());assertEquals(p.path("statisticPeriodId"),curve.path("statisticPeriodId"));
        String first=curve.path("content").get(0).path("pointId").asText();Map<String,Object> b=write(p);b.put("data",point("2026-09-01T00:00:00Z","0.000000000000000001"));JsonNode changed=ok(send("PUT",API+"/"+id+"/equity/"+first,writer,b));p=changed.path("profile");assertEquals("DRAFT",p.path("status").asText());assertEquals("0.000000000000000001",changed.path("netAsset").asText());assertEquals(404,send("GET",PUBLIC+"/"+id,null,null).getResponse().getStatus());assertEquals("GAPPED",ok(send("GET",API+"/"+id+"/equity",reader,null)).path("curveStatus").asText());json.writeValue(REPORTS.resolve("api-equity.json").toFile(),ok(send("GET",API+"/"+id+"/equity",reader,null)));b=write(p);p=ok(send("DELETE",API+"/"+id+"/equity/"+first,writer,b));assertEquals(2,p.path("equityPointCount").asInt());
    }
    @Test @Order(6) void historyCrudOnlyClosedTimeExplicitFeesMissingMetricsAndPrivateEvidence()throws Exception {
        JsonNode p=create();String id=p.path("traderId").asText();JsonNode c=child(p,"history",record("DEMO-OLD","2026-09-02T00:00:00Z"));p=c.path("profile");Map<String,Object> h=record("DEMO-NEW","2026-09-20T00:00:00Z");h.put("pnl","-1.23");h.put("pnlBasis","AFTER_FEES");h.put("fees","0.01");h.put("quantity","0.000000000000000001");h.put("quantityUnit","BTC");c=child(p,"history",h);p=publish(c.path("profile"));JsonNode history=ok(send("GET",PUBLIC+"/"+id+"/history?size=1",null,null));JsonNode newest=history.path("content").get(0);assertEquals("2026-09-20T00:00:00Z",newest.path("closedAt").asText());assertEquals("-1.23",newest.path("pnl").asText());assertFalse(newest.has("openedAt"));assertFalse(newest.has("evidenceNote"));assertFalse(newest.has("recordKey"));assertTrue(newest.path("leverage").isNull());assertEquals("UNVERIFIED",newest.path("verificationStatus").asText());assertEquals(p.path("statisticPeriodId"),history.path("statisticPeriodId"));json.writeValue(REPORTS.resolve("api-history.json").toFile(),history);
        String recordId=newest.path("recordId").asText();Map<String,Object> b=write(p);h.put("pnl","3.14");b.put("data",h);c=ok(send("PUT",API+"/"+id+"/history/"+recordId,writer,b));p=c.path("profile");assertEquals("DRAFT",p.path("status").asText());b=write(p);ok(send("DELETE",API+"/"+id+"/history/"+recordId,writer,b));assertEquals(1,ok(send("GET",API+"/"+id+"/history",reader,null)).path("totalElements").asInt());assertEquals(0,ok(send("GET",API+"/"+id+"/history?period=7D",reader,null)).path("totalElements").asInt());
    }
    @Test @Order(7) void importIsAtomicReportsRowsAndDoesNotOverwriteOnDuplicatesUnitsDates()throws Exception {
        JsonNode p=publish(create());String id=p.path("traderId").asText();Map<String,Object> b=write(p);Map<String,Object> invalid=point("2026-09-02T00:00:00Z","2");invalid.put("currency","USDT");b.put("rows",Arrays.asList(point("2026-09-01T00:00:00Z","1"),invalid));MvcResult error=send("POST",API+"/"+id+"/equity/import",writer,b);assertEquals(400,error.getResponse().getStatus());JsonNode result=json.readTree(error.getResponse().getContentAsByteArray());assertEquals(2,result.path("errors").get(0).path("row").asInt());assertEquals(0,db.queryForObject("SELECT COUNT(*) FROM trader_equity",Integer.class));assertEquals("PUBLISHED",detail(id).path("status").asText());json.writeValue(REPORTS.resolve("api-import-error.json").toFile(),result);
        b.put("rows",Arrays.asList(point("2026-09-01T00:00:00Z","1"),point("2026-09-01T00:00:00Z","2")));assertEquals(400,send("POST",API+"/"+id+"/equity/import",writer,b).getResponse().getStatus());b.put("rows",Arrays.asList(point("2026-09-01T00:00:00Z","1"),point("2026-09-02T00:00:00Z","2")));result=ok(send("POST",API+"/"+id+"/equity/import",writer,b));assertEquals(2,result.path("inserted").asInt());p=result.path("profile");assertEquals("DRAFT",p.path("status").asText());b=write(p);b.put("rows",Collections.singletonList(point("2026-09-01T00:00:00Z","999")));assertEquals(400,send("POST",API+"/"+id+"/equity/import",writer,b).getResponse().getStatus());assertEquals("1",ok(send("GET",API+"/"+id+"/equity",reader,null)).path("content").get(0).path("netAsset").asText());
        b=write(p);Map<String,Object> forged=record("DEMO-FORGED","2026-09-02T00:00:00Z");forged.put("verificationStatus","VERIFIED");b.put("rows",Collections.singletonList(forged));assertEquals(400,send("POST",API+"/"+id+"/history/import",writer,b).getResponse().getStatus());b.put("rows",Arrays.asList(record("DEMO-1","2026-09-02T00:00:00Z"),record("DEMO-1","2026-09-03T00:00:00Z")));assertEquals(400,send("POST",API+"/"+id+"/history/import",writer,b).getResponse().getStatus());assertEquals(0,db.queryForObject("SELECT COUNT(*) FROM trader_history",Integer.class));b.put("rows",Arrays.asList(record("DEMO-1","2026-09-02T00:00:00Z"),record("DEMO-2","2026-09-03T00:00:00Z")));assertEquals(2,ok(send("POST",API+"/"+id+"/history/import",writer,b)).path("inserted").asInt());
    }
    @Test @Order(8) void versionConflictProfileUnitProtectionAndConcurrentEdits()throws Exception {
        JsonNode p=create();String id=p.path("traderId").asText();JsonNode updated=child(p,"equity",point("2026-09-01T00:00:00Z","1")).path("profile");Map<String,Object> old=write(p);old.put("status","PUBLISHED");assertEquals(409,send("PUT",API+"/"+id+"/publication",writer,old).getResponse().getStatus());ObjectNode d=(ObjectNode)updated.path("data");d.put("currency","USDT");Map<String,Object> b=write(updated);b.put("data",d);assertEquals(400,send("PUT",API+"/"+id,writer,b).getResponse().getStatus());
        ExecutorService pool=Executors.newFixedThreadPool(2);try{TraderData.Change c=new TraderData.Change();c.rowVersion=updated.path("rowVersion").asLong();c.reason="TEST_ONLY 并发版本";c.recommended=true;c.sortOrder=1;Callable<Integer> call=()->{try(TenantContext.Scope ignored=TenantContext.open(1L)){org.springframework.security.core.context.SecurityContextHolder.getContext().setAuthentication(new org.springframework.security.authentication.UsernamePasswordAuthenticationToken("TEST_ONLY",null,Collections.singletonList(new org.springframework.security.core.authority.SimpleGrantedAuthority("ROLE_SUPER_ADMIN"))));try{service.recommendation(id,c);return 200;}catch(org.springframework.web.server.ResponseStatusException e){return e.getRawStatusCode();}finally{org.springframework.security.core.context.SecurityContextHolder.clearContext();}}};Future<Integer> a=pool.submit(call),f=pool.submit(call);List<Integer> states=Arrays.asList(a.get(),f.get());assertTrue(states.contains(200));assertTrue(states.contains(409));}finally{pool.shutdownNow();}
    }
    @Test @Order(9) void filteringStablePaginationRecommendationAndRejectUnverifiedPerformanceSort()throws Exception {
        JsonNode a=publish(create()),b=publish(create());Map<String,Object> rank=write(a);rank.put("recommended",true);rank.put("sortOrder",10);a=ok(send("PUT",API+"/"+a.path("traderId").asText()+"/recommendation",writer,rank));JsonNode l=ok(send("GET",PUBLIC+"?recommended=true&currency=USD&q=Strategy&size=1",null,null));assertEquals(a.path("traderId"),l.path("content").get(0).path("traderId"));assertEquals(1,l.path("totalElements").asInt());JsonNode first=ok(send("GET",PUBLIC+"?size=1",null,null)),second=ok(send("GET",PUBLIC+"?size=1&page=1",null,null));assertNotEquals(first.path("content").get(0).path("traderId"),second.path("content").get(0).path("traderId"));assertEquals(b.path("traderId"),second.path("content").get(0).path("traderId"));for(String query:Arrays.asList("sort=ROI","size=101","page=-1","currency=bad!","sourceType=VERIFIED_PLATFORM"))assertEquals(400,send("GET",PUBLIC+"?"+query,null,null).getResponse().getStatus());
    }
    @Test @Order(10) void auditBeforeAfterActorReasonAndTemplatesAreBoundedScoped()throws Exception {
        JsonNode p=create();String id=p.path("traderId").asText();child(p,"equity",point("2026-09-01T00:00:00Z","1"));JsonNode audit=ok(send("GET",API+"/audit?traderId="+id,reader,null));assertEquals(2,audit.size());assertTrue(audit.get(0).path("actor").asText().startsWith("ADMIN:"));assertTrue(audit.get(0).path("afterJson").asText().contains("netAsset"));assertEquals("TEST_ONLY 隔离验收依据",audit.get(0).path("reason").asText());assertEquals(404,send("GET",API+"/audit?traderId="+id,tenantTwo,null).getResponse().getStatus());JsonNode template=ok(send("GET",API+"/"+id+"/import-template?kind=history",reader,null));assertTrue(template.path("rows").get(0).path("pnl").isNull());assertTrue(template.path("rows").get(0).path("recordKey").isNull());assertFalse(template.toString().contains("openedAt"));json.writeValue(REPORTS.resolve("api-template.json").toFile(),template);
    }
    @Test @Order(11) void realSocketHttpSmokeUsesSameTenantAndVersions()throws Exception {
        JsonNode p=publish(create());String id=p.path("traderId").asText();String response;try(java.net.Socket socket=new java.net.Socket("127.0.0.1",port)){socket.setSoTimeout(5000);socket.getOutputStream().write(("GET "+PUBLIC+"/"+id+" HTTP/1.1\r\nHost: a.mt705.test\r\nConnection: close\r\n\r\n").getBytes(java.nio.charset.StandardCharsets.US_ASCII));java.io.ByteArrayOutputStream bytes=new java.io.ByteArrayOutputStream();byte[] chunk=new byte[4096];int n;while((n=socket.getInputStream().read(chunk))!=-1)bytes.write(chunk,0,n);response=new String(bytes.toByteArray(),java.nio.charset.StandardCharsets.UTF_8);}assertTrue(response.startsWith("HTTP/1.1 200"),response);String rawBody=response.substring(response.indexOf("\r\n\r\n")+4);String body=rawBody;if(response.toLowerCase(Locale.ROOT).contains("transfer-encoding: chunked")){StringBuilder decoded=new StringBuilder();int pos=0;while(pos<rawBody.length()){int line=rawBody.indexOf("\r\n",pos);if(line<0)break;int length=Integer.parseInt(rawBody.substring(pos,line).trim(),16);if(length==0)break;pos=line+2;decoded.append(rawBody,pos,Math.min(rawBody.length(),pos+length));pos+=length+2;}body=decoded.toString();}assertTrue(response.toLowerCase(Locale.ROOT).contains("cache-control: no-store"),response);assertTrue(body.contains(id),body);json.writeValue(REPORTS.resolve("http-smoke.json").toFile(),Collections.singletonMap("rawResponse",response));
    }
    @Test @Order(12) void avatarUploadReferenceIsPrivateUntilPublicationAndImmediatelyRevoked()throws Exception {
        // Production DEMO URL is reverse-proxied to the existing image controller; no new media server.
        MockMultipartFile file=new MockMultipartFile("file","avatar.png","image/png",java.util.Base64.getDecoder().decode("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a8n8AAAAASUVORK5CYII="));JsonNode upload=ok(mvc.perform(multipart("/api/upload/image").file(file).header("Host",BootTenantFixture.ADMIN).header("Authorization","Bearer "+writer)).andReturn());assertTrue(upload.path("success").asBoolean());String url=upload.path("url").asText();assertTrue(url.startsWith("/api/uploads/images/1/staff/"));JsonNode p=create();ObjectNode d=(ObjectNode)p.path("data");d.put("avatarUrl",url);Map<String,Object> b=write(p);b.put("data",d);p=ok(send("PUT",API+"/"+p.path("traderId").asText(),writer,b));String path=url.replace("/demo-uploads/","/api/uploads/");assertNotEquals(200,send("GET",path,null,null).getResponse().getStatus());p=publish(p);assertEquals(200,send("GET",path,null,null).getResponse().getStatus());b=write(p);b.put("status","OFFLINE");ok(send("PUT",API+"/"+p.path("traderId").asText()+"/publication",writer,b));assertNotEquals(200,send("GET",path,null,null).getResponse().getStatus());
    }
    @Test @Order(99) @Timeout(55) void publicBudgetDoesNotAmplifyAnyExternalRequest()throws Exception {int result=0;for(int i=0;i<1201;i++){result=send("GET",PUBLIC,null,null).getResponse().getStatus();if(result==429)break;}assertEquals(429,result);}
    @Test @org.junit.jupiter.api.condition.EnabledIfSystemProperty(named="traders.browserHold",matches="true")
    void browserAcceptanceWindow()throws Exception {
        Map<String,Object> info=new LinkedHashMap<>();info.put("port",port);info.put("writer",writer);info.put("reader",reader);info.put("denied",denied);info.put("testOnly",true);info.put("environment","REAL");Path p=REPORTS.resolve("browser-access.tmp.json"),done=REPORTS.resolve("browser.done");Files.deleteIfExists(done);json.writeValue(p.toFile(),info);try{for(int i=0;i<2400&&!Files.exists(done);i++)Thread.sleep(1000);assertTrue(Files.exists(done),"browser acceptance must report completion");assertEquals("passed",new String(Files.readAllBytes(done),java.nio.charset.StandardCharsets.UTF_8));}finally{Files.deleteIfExists(p);}
    }
}
