<script setup lang="ts">
import { ref, computed, onMounted, defineAsyncComponent } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { useAccountTable } from '@/utils/useAccountTable'
import { accountTableRequest } from '@/utils/accountTableRequest'
import AccountTypeFilter from '@/components/AccountTypeFilter.vue'
const ActivityTemplateEditor=defineAsyncComponent(()=>import('./ActivityTemplateEditor.vue'))
import { readActivityTranslations, validateActivityCopy } from '@/utils/activityContent'
import { activitySettings, validateActivitySettings, assertActivitySettingsSaved, activityPositions, activityTriggers } from '@/utils/activitySettings'
import { parseDesign } from '../../../exchange-frontend/src/utils/activityDesign'
const accountTable = useAccountTable(), accountModes = accountTable.modes
const recipientTable = useAccountTable(), recipientModes = recipientTable.modes
const ledgerTable = useAccountTable(), ledgerModes = ledgerTable.modes
const request = accountTableRequest(accountTable)
import { can } from '@/utils/access'
const list=ref<any[]>([]), page=ref(1), total=ref(0), loading=ref(false), saving=ref(false), editor=ref(false), form=ref<any>({}), language=ref('zh-CN'), translations=ref<Record<string,any>>({})
const section=ref('activities'), sourceTemplate=ref(false), autoOpen=ref(false), autoForm=ref<any>({}), autoSaving=ref(false)
const ActivityRecipientPicker=defineAsyncComponent(()=>import('./ActivityRecipientPicker.vue'))
const sendOpen=ref(false), selected=ref<any>(), sending=ref(false)
const reportOpen=ref(false), stats=ref<any>({}), recipients=ref<any[]>([]), recipientPage=ref(1), recipientTotal=ref(0), filter=ref('ALL'), userFilter=ref(''), emailFilter=ref(''), reportBusy=ref(false), ledgerOpen=ref(false), ledger=ref<any[]>([]), account=ref<any>({})
const labels:Record<string,string>={DRAFT:'草稿',ACTIVE:'启用',PAUSED:'暂停',CLOSED:'关闭'}
const defaultCopy=()=>({title:'一份心意，开启更多可能',body:'为回馈新老客户，最近 {days} 天登录的客户可领取 {amount} U 体验金。点击下方按钮领取，体验金将自动存入您的专属账户。',terms:'体验金仅可用于交易，不可提现。交易净收益归入正式交易账户，体验金本金留在体验金账户。',open:'打开礼遇',close:'关闭',claim:'领取 {amount} U 体验金',success:'体验金已到账'})
const english=()=>({title:'A little extra for your next opportunity',body:'Thank you for trading with us. Customers who logged in within the last {days} days can claim {amount} U in trial credit.',terms:'Trial principal is for trading only and cannot be withdrawn. Net profits go to your real trading account.',open:'Open gift',close:'Close',claim:'Claim {amount} U',success:'Your trial credit has arrived'})
const activeCopy=computed(()=>translations.value[language.value] || {})
const serverDate=(value:string)=>value?value.slice(0,19).replace('T',' '):'—'
const date=(value:string)=>value?new Date(/Z$|[+-]\d{2}:\d{2}$/.test(value)?value:value+'Z').toLocaleString():'—'
let loadVersion=0
async function load(){const version=++loadVersion;list.value=[];total.value=0;loading.value=true;try{const r:any=await request.get('/admin/activities',{params:{page:page.value-1,template:section.value==='templates'}});if(version===loadVersion){list.value=r.content;total.value=r.totalElements}}catch(e:any){if(version===loadVersion)ElMessage.error(e.message)}finally{if(version===loadVersion)loading.value=false}}
function edit(row?:any, clone=false){
 if(!can(row&&!clone?'announcement:edit':'announcement:create')||accountModes.value.includes('DEMO')||!accountModes.value.length)return
 accountTable.selectRow(row || {})
 sourceTemplate.value=!!row?.template
 form.value=row?JSON.parse(JSON.stringify(row)):{name:'新老客户 · 300 U 体验金',amount:300,recentLoginDays:3,maxClaims:1000,budget:300000,status:'DRAFT',template:section.value==='templates',claimValidityDays:3,allowRepeatClaim:false,positions:['AUTH_HOME'],triggerConditions:[],autoSendEnabled:false,allowRepeatSend:false,repeatUnread:false,autoPopup:true,animation:'GIFT',defaultLocale:'zh-CN',startsAt:null,endsAt:null}
 if(clone){delete form.value.id;form.value.name+=' · 副本';form.value.status='DRAFT';form.value.template=false;form.value.autoSendEnabled=false;sourceTemplate.value=false;form.value.claimCount=0;form.value.granted=0}
 try{translations.value=readActivityTranslations(row?.translations,{'zh-CN':defaultCopy(),en:english()});validateActivityCopy(translations.value,form.value.defaultLocale);if(form.value.layoutJson&&!parseDesign(form.value.layoutJson))throw new Error('旧设计格式无效，原数据未覆盖')}catch(e:any){ElMessage.error(e.message);return}
 language.value=form.value.defaultLocale;editor.value=true
}
async function saveDesign(value:{layoutJson:string;translations:Record<string,any>;name:string;defaultLocale:string;asTemplate:boolean}){
 if(saving.value)return
 Object.assign(form.value,{layoutJson:value.layoutJson,name:value.name,defaultLocale:value.defaultLocale});translations.value=value.translations
 await save(value.asTemplate)
}
async function save(asTemplate=form.value.template){
 if(saving.value)return
 if(!can(form.value.id?'announcement:edit':'announcement:create')||(asTemplate!==sourceTemplate.value&&!can('announcement:create')))return
 if(!form.value.name?.trim()||!translations.value[form.value.defaultLocale]){ElMessage.warning('请填写名称和默认语言');return}
 saving.value=true
 try{const payload={...form.value,template:asTemplate,translations:JSON.stringify(translations.value)};if(!payload.id)payload.budget=Math.max(Number(payload.budget),Number(payload.amount));if(asTemplate!==sourceTemplate.value && payload.id){delete payload.id;payload.status='DRAFT';payload.autoSendEnabled=false}if(asTemplate){payload.status='DRAFT';payload.autoSendEnabled=false}const r:any=await (payload.id?request.patch(`/admin/activities/${payload.id}/content`,Object.fromEntries(['rowVersion','name','defaultLocale','translations','layoutJson'].map(key=>[key,payload[key]]))):request.post('/admin/activities',payload));form.value=r;editor.value=false;ElMessage.success(asTemplate?'模板已保存':'活动已保存');section.value=asTemplate?'templates':'activities';page.value=1;await load()}catch(e:any){ElMessage.error(e.message)}finally{saving.value=false}
}
async function status(row:any,value:string){
 accountTable.selectRow(row)
 try{await ElMessageBox.confirm(`确定${labels[value]}“${row.name}”？暂停/关闭只停止领取，不追缴已领取本金。`,'活动状态');await request.put(`/admin/activities/${row.id}`,{...row,status:value});await load()}catch(e:any){if(e?.message)ElMessage.error(e.message)}
}
function prepareSend(row:any){if(!can('announcement:edit')||accountModes.value.includes('DEMO')||!accountModes.value.length)return;accountTable.selectRow(row);selected.value=row;sendOpen.value=true}
function configureAuto(row:any){if(!can('announcement:edit')||accountModes.value.includes('DEMO')||!accountModes.value.length)return;accountTable.selectRow(row);autoForm.value=activitySettings(JSON.parse(JSON.stringify(row)));autoOpen.value=true}
async function saveAuto(){
 if(autoSaving.value||!can('announcement:edit'))return
 try{validateActivitySettings(autoForm.value)}catch(e:any){ElMessage.warning(e.message);return}
 autoSaving.value=true
 try{const fields=['status','amount','autoSendEnabled','recentLoginDays','maxClaims','budget','startsAt','endsAt','claimValidityDays','allowRepeatClaim','allowRepeatSend','positions','triggerConditions','autoPopup','repeatUnread','animation'];const payload=Object.fromEntries(fields.map(key=>[key,autoForm.value[key]]));const result=await request.put(`/admin/activities/${autoForm.value.id}/auto-send`,payload);assertActivitySettingsSaved(payload,result);autoOpen.value=false;ElMessage.success('公告发送设置已保存');await load()}catch(e:any){ElMessage.error(e.message)}finally{autoSaving.value=false}
}
async function removeActivity(row:any){accountTable.selectRow(row);try{await ElMessageBox.confirm(`删除“${row.name}”？将停止发送和领取，已发放体验金及历史流水保留。`,'删除活动',{type:'warning',confirmButtonText:'删除',cancelButtonText:'取消'});await request.delete(`/admin/activities/${row.id}`);if(list.value.length===1&&page.value>1)page.value--;await load();ElMessage.success('活动已删除')}catch(e:any){if(e?.message)ElMessage.error(e.message)}}
async function report(row?:any){if(row){recipientModes.value=[row.accountMode||"REAL"];selected.value=row;recipientPage.value=1;filter.value='ALL';userFilter.value='';emailFilter.value='';reportOpen.value=true}recipients.value=[];stats.value={};reportBusy.value=true;try{const [s,r]:any=await Promise.all([recipientTable.counters(`/admin/activities/${selected.value.id}/stats`),recipientTable.fixedQuery(`/admin/activities/${selected.value.id}/recipients`,{page:recipientPage.value-1,state:filter.value,userId:userFilter.value||undefined,userEmail:emailFilter.value.trim()||undefined},50)]);stats.value=s;recipients.value=r.content;recipientTotal.value=r.totalElements}catch(e:any){ElMessage.error(e.message)}finally{reportBusy.value=false}}
async function showLedger(userId:number, mode?:any){if(mode)ledgerModes.value=[mode];ledger.value=[];try{const [a,r]:any=await Promise.all([ledgerTable.counters(`/admin/activities/users/${userId}/account`),ledgerTable.fixedQuery(`/admin/activities/users/${userId}/ledger`,{},50)]);account.value={...a,userId};ledger.value=r.content;ledgerOpen.value=true}catch(e:any){ElMessage.error(e.message)}}
onMounted(load)
</script>
<template>
 <section class="activity-admin">
  <header class="activity-admin-hero"><div><span>CAMPAIGNS & TRIAL CREDIT</span><h2>把一份礼遇，送到合适的人手中。</h2><p>定向投递 · 多语言公告 · 独立本金账户 · 领取与互动追踪</p></div><el-button v-permission="'announcement:create'" v-if="can('announcement:create')" type="primary" size="large" @click="edit()" :disabled="accountModes.includes('DEMO') || !accountModes.length">＋ 新建{{section==='templates'?'模板':'活动'}}</el-button></header>
  <div class="activity-admin-note">体验金与可提现资产隔离。新活动默认草稿，保存不等于发送；默认不允许重复领取；重复领取与重复发送是独立规则。</div>
  <el-tabs v-model="section" class="activity-tabs" @tab-change="page=1;load()"><el-tab-pane label="活动列表" name="activities"/><el-tab-pane label="模板" name="templates"/></el-tabs>
  <AccountTypeFilter v-model="accountModes" @change="page=1;load()" /><admin-table :row-key="(row: any) => `${row.accountMode || 'REAL'}:${row.id ?? row.userId}:${row.type || ''}`" table-key="ActivityManagement.1" :data="list" v-loading="loading" stripe><el-table-column prop="accountModeLabel" label="账户类型" width="110" />
   <el-table-column prop="id" label="ID" width="65"/><el-table-column prop="name" :label="section==='templates'?'模板名称':'活动名称'" min-width="230"><template #default="{row}"><strong>{{row.name}}</strong><el-tag v-if="row.template" size="small" style="margin-left:8px">模板</el-tag><small class="row-meta">{{row.defaultLocale}} · {{row.autoPopup?'自动弹出':'仅站内信'}} · {{row.animation}}</small></template></el-table-column>
   <el-table-column column-key="trialCredit" label="体验金" width="120"><template #default="{row}">{{Number(row.amount).toLocaleString()}} U</template></el-table-column>
   <el-table-column column-key="claims" label="已领取 / 名额" width="145"><template #default="{row}">{{row.claimCount}} / {{row.maxClaims}}</template></el-table-column>
   <el-table-column column-key="deliveryBudget" label="已发 / 预算 (U)" width="165"><template #default="{row}">{{Number(row.granted).toLocaleString()}} / {{Number(row.budget).toLocaleString()}}</template></el-table-column>
   <el-table-column column-key="autoDelivery" v-if="section==='activities'" label="自动发送" width="110"><template #default="{row}"><el-tag :type="row.autoSendEnabled?'success':'info'">{{row.autoSendEnabled?'已开启':'已关闭'}}</el-tag></template></el-table-column>
   <el-table-column column-key="status" v-if="section==='activities'" label="状态" width="90"><template #default="{row}"><el-tag :type="row.status==='ACTIVE'?'success':row.status==='CLOSED'?'info':'warning'">{{labels[row.status]}}</el-tag></template></el-table-column>
   <el-table-column column-key="endsAt" label="截止时间（服务器时间）" width="180"><template #default="{row}">{{serverDate(row.endsAt)}}</template></el-table-column>
   <el-table-column column-key="actions" label="操作" :width="section==='templates'?100:450" fixed="right"><template #default="{row}"><el-button v-permission="'announcement:edit'" v-if="can('announcement:edit')" link type="primary" @click="edit(row)" :disabled="accountModes.includes('DEMO') || !accountModes.length">编辑</el-button><template v-if="!row.template"><el-button v-permission="'announcement:create'" v-if="can('announcement:create')" link type="primary" @click="edit(row,true)" :disabled="accountModes.includes('DEMO') || !accountModes.length">复制</el-button><el-button v-permission="'announcement:edit'" v-if="can('announcement:edit')" link type="primary" :disabled="accountModes.includes('DEMO') || !accountModes.length || (row.template||row.status!=='ACTIVE')" @click="prepareSend(row)">发送</el-button><el-button v-permission="'announcement:detail'" v-if="can('announcement:detail')" link type="primary" @click="report(row)">回执</el-button><el-button v-permission="'announcement:edit'" v-if="can('announcement:edit')" link @click="status(row,row.status==='ACTIVE'?'PAUSED':'ACTIVE')" :disabled="accountModes.includes('DEMO') || !accountModes.length">{{row.status==='ACTIVE'?'暂停':'启用'}}</el-button><el-button v-permission="'announcement:edit'" v-if="can('announcement:edit')" link type="danger" :disabled="accountModes.includes('DEMO') || !accountModes.length || (row.status==='CLOSED')" @click="status(row,'CLOSED')">关闭</el-button><el-button v-permission="'announcement:edit'" v-if="can('announcement:edit')" link type="primary" :disabled="accountModes.includes('DEMO') || !accountModes.length" @click="configureAuto(row)">公告发送设置</el-button><el-button v-permission="'announcement:delete'" v-if="can('announcement:delete')" link type="danger" :disabled="accountModes.includes('DEMO') || !accountModes.length" @click="removeActivity(row)">删除</el-button></template></template></el-table-column>
  </admin-table><el-pagination v-model:current-page="page" :page-size="50" :total="total" layout="total, prev, pager, next" @current-change="load"/>
  <el-dialog v-model="editor" title="活动内容可视化编辑器" append-to-body fullscreen destroy-on-close :show-close="false" :close-on-click-modal="false" :close-on-press-escape="false"><ActivityTemplateEditor v-if="editor" :editing="!!form.id" :value="form.layoutJson" :locale="language" :fallback="form.defaultLocale" :fallback-copy="translations[form.defaultLocale]" :copy="activeCopy" :translations="translations" :name="form.name" :template="!!form.template" :saving="saving" :can-create="can('announcement:create')" @save="saveDesign" @cancel="editor=false"/></el-dialog>
  <el-dialog class="t03-activity-dialog" append-to-body v-model="autoOpen" title="公告发送设置" width="min(780px,96vw)" :close-on-click-modal="false" :close-on-press-escape="!autoSaving" :show-close="!autoSaving">
   <el-alert type="info" :closable="false" title="自动发送只匹配时间窗内真实业务事件，不按分钟广播；读取消息或轮询不制造触发。领取有效期从每次领取时刻计算，与活动结束时间独立。"/>
   <el-form label-position="top" style="margin-top:18px" :disabled="autoSaving||accountModes.includes('DEMO')||!accountModes.length">
    <div class="form-grid"><el-form-item label="活动状态"><el-select v-model="autoForm.status" aria-label="活动状态"><el-option v-for="(label,key) in labels" :key="key" :label="label" :value="key"/></el-select></el-form-item><el-form-item label="每人体验金 (U)" required><el-input-number v-model="autoForm.amount" aria-label="每人体验金" :min="0.01" :max="1000000" :precision="2"/></el-form-item></div>
    <div class="form-grid"><el-form-item label="领取后有效期（天）" :required="autoForm.claimValidityDays!==null"><el-switch v-permission="'announcement:edit'" :model-value="autoForm.claimValidityDays!==null" aria-label="设置领取有效期" @change="(value:any)=>autoForm.claimValidityDays=value?3:null"/><small v-if="autoForm.claimValidityDays===null">不设置到期</small><el-input-number v-model="autoForm.claimValidityDays" aria-label="领取后有效期（天）" :disabled="autoForm.claimValidityDays===null" :min="1" :max="3650" :precision="0"/></el-form-item><el-form-item label="最多领取人数 / 次数"><el-input-number v-model="autoForm.maxClaims" aria-label="最多领取人数" :min="Math.max(1,autoForm.claimCount||0)" :max="1000000" :precision="0"/></el-form-item><el-form-item label="发放总预算 (U)"><el-input-number v-model="autoForm.budget" aria-label="发放总预算" :min="Math.max(Number(autoForm.amount||0),Number(autoForm.granted||0))" :max="1000000000" :precision="2"/></el-form-item><el-form-item label="最近登录天数（0 表示不限）"><el-input-number v-model="autoForm.recentLoginDays" aria-label="最近登录天数" :min="0" :max="365" :precision="0"/></el-form-item></div>
    <el-form-item label="允许重复领取"><el-switch v-permission="'announcement:edit'" v-model="autoForm.allowRepeatClaim" aria-label="允许重复领取"/><small class="setting-help">默认关闭。开启后可主动再次领取；网络重试仍幂等，不清除旧领取记录、不延长旧本金期限。</small></el-form-item>
    <el-form-item label="允许同一用户重复发送"><el-switch v-permission="'announcement:edit'" v-model="autoForm.allowRepeatSend" aria-label="允许同一用户重复发送"/><small class="setting-help">重复发送公告与重复领取无关；只恢复公告未读，不因此重复发放本金。</small></el-form-item>
    <el-form-item label="展现位置" required><el-checkbox-group v-model="autoForm.positions" aria-label="展现位置"><el-checkbox v-for="position in activityPositions" :key="position.value" :value="position.value">{{position.label}}</el-checkbox></el-checkbox-group><small class="setting-help">未登录主页点击后进入登录 / 注册；认证后后端重新校验再领取。</small></el-form-item>
    <div class="form-grid"><el-form-item label="进入页面自动弹出"><el-switch v-permission="'announcement:edit'" v-model="autoForm.autoPopup" aria-label="进入页面自动弹出"/></el-form-item><el-form-item label="动画风格"><el-select v-model="autoForm.animation" aria-label="动画风格"><el-option label="礼盒开启 + 彩带" value="GIFT"/><el-option label="金色礼遇 + 彩带" value="CONFETTI"/><el-option label="静态展示" value="NONE"/></el-select></el-form-item></div>
    <el-form-item label="未读重复弹出"><el-switch v-permission="'announcement:edit'" v-model="autoForm.repeatUnread" aria-label="未读重复弹出"/><small class="setting-help">未打开即关闭可在下次进入适用页面弹出；不重复发放本金。</small></el-form-item>
    <el-divider content-position="left">条件自动发送</el-divider><el-form-item label="开启自动发送"><el-switch v-permission="'announcement:edit'" v-model="autoForm.autoSendEnabled" aria-label="开启自动发送"/></el-form-item>
    <div class="form-grid"><el-form-item label="开始时间（服务器时间）" :required="autoForm.autoSendEnabled"><el-date-picker v-model="autoForm.startsAt" aria-label="活动开始时间" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss" placeholder="自动发送开启时必填"/></el-form-item><el-form-item label="结束时间（服务器时间）" :required="autoForm.autoSendEnabled"><el-date-picker v-model="autoForm.endsAt" aria-label="活动结束时间" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss" placeholder="自动发送开启时必填"/></el-form-item></div>
    <el-form-item label="触发条件（任意一个成功事件）" :required="autoForm.autoSendEnabled"><el-select v-model="autoForm.triggerConditions" multiple aria-label="触发条件" :disabled="!autoForm.autoSendEnabled" placeholder="选择预设，禁止自定义任意 API 或页面"><el-option v-for="trigger in activityTriggers" :key="trigger.value" :value="trigger.value" :label="trigger.label"/></el-select></el-form-item>
   </el-form><template #footer><el-button v-permission="'session:close'" :disabled="autoSaving" @click="autoOpen=false">取消</el-button><el-button v-permission="'announcement:edit'" type="primary" :loading="autoSaving" :disabled="accountModes.includes('DEMO')||!accountModes.length" @click="saveAuto">保存设置</el-button></template>
  </el-dialog>
  <el-dialog class="t03-activity-dialog" append-to-body destroy-on-close v-model="sendOpen" :close-on-click-modal="!sending" :close-on-press-escape="!sending" :show-close="!sending" title="定向批量发送" width="min(920px,96vw)"><ActivityRecipientPicker v-if="sendOpen" :campaign="selected" :request="request" :read-only="!can('announcement:edit')||accountModes.includes('DEMO')||!accountModes.length" @busy="sending=$event" @close="sendOpen=false"/></el-dialog>
  <el-dialog v-model="reportOpen" :title="'投递与领取追踪 · '+(selected?.name||'')" width="min(1200px,96vw)"><div class="activity-stat-grid"><div v-for="(label,key) in {sent:'已发送',received:'已收到',opened:'已打开',closed:'已关闭',closedWithoutOpening:'未打开即关闭',claimed:'已领取'}" :key="key"><strong>{{stats[key]||0}}</strong><span>{{label}}</span></div></div><div class="recipient-filters"><el-select v-model="filter" @change="recipientPage=1;report()"><el-option v-for="(label,key) in {ALL:'全部',SENT:'发送但未收到',RECEIVED:'已收到',OPENED:'已打开',CLOSED:'已关闭',CLOSED_UNOPENED:'收到后未打开即关闭',CLAIMED:'已领取'}" :key="key" :value="key" :label="label"/></el-select><el-input v-model="userFilter" placeholder="用户ID" clearable style="width:180px" @change="recipientPage=1;report()"/><el-input v-model="emailFilter" placeholder="用户邮箱" aria-label="用户邮箱" clearable maxlength="254" style="width:220px" @change="recipientPage=1;report()"/><el-button v-permission="'announcement:detail'" :loading="reportBusy" @click="recipientPage=1;report()">查询 / 刷新</el-button></div><AccountTypeFilter v-model="recipientModes" @change="recipientPage=1;report()" /><admin-table :row-key="(row: any) => `${row.accountMode || 'REAL'}:${row.id ?? row.userId}:${row.type || ''}`" table-key="ActivityManagement.2" :data="recipients" v-loading="reportBusy"><el-table-column prop="accountModeLabel" label="账户类型" width="110" /><el-table-column prop="userId" label="用户ID" width="105"/><el-table-column prop="userEmail" label="用户邮箱" min-width="200" show-overflow-tooltip/><el-table-column prop="userRemark" label="用户备注" min-width="150" show-overflow-tooltip><template #default="{row}">{{row.userRemark||'-'}}</template></el-table-column><el-table-column :column-key="key" v-for="(label,key) in {sentAt:'发送时间',receivedAt:'收到时间',openedAt:'首次打开',closedAt:'最后关闭',claimedAt:'领取时间'}" :key="key" :label="label" min-width="155"><template #default="{row}">{{date(row[key])}}</template></el-table-column><el-table-column column-key="openCloseCount" label="打开/关闭" width="100"><template #default="{row}">{{row.openCount}} / {{row.closeCount}}</template></el-table-column><el-table-column column-key="account" label="账户" width="80"><template #default="{row}"><el-button v-permission="'announcement:detail'" link type="primary" @click="showLedger(row.userId,row.accountMode)">流水</el-button></template></el-table-column></admin-table><el-pagination v-model:current-page="recipientPage" :page-size="50" :total="recipientTotal" layout="total,prev,pager,next" @current-change="report()"/></el-dialog>
  <el-dialog v-model="ledgerOpen" title="体验金账户与最近50笔流水" width="min(900px,95vw)"><p>用户 {{account.userId}} · 可用 {{Number(account.available)}} U · 占用 {{Number(account.frozen)}} U · 累计消耗 {{Number(account.consumed)}} U · 净收益 {{Number(account.profits)}} U</p><AccountTypeFilter v-model="ledgerModes" @change="showLedger(account.userId)" /><admin-table :row-key="(row: any) => `${row.accountMode || 'REAL'}:${row.id ?? row.userId}:${row.type || ''}`" table-key="ActivityManagement.3" :data="ledger"><el-table-column prop="accountModeLabel" label="账户类型" width="110" /><el-table-column prop="reason" label="业务原因" min-width="200"/><el-table-column prop="delta" label="本金变化"/><el-table-column prop="available" label="可用"/><el-table-column prop="frozen" label="冻结"/><el-table-column column-key="time" label="时间" width="180"><template #default="{row}">{{date(row.createdAt)}}</template></el-table-column></admin-table></el-dialog>
 </section>
</template>
<style scoped>
:global(.t03-activity-dialog){margin-top:5vh!important;margin-bottom:5vh!important}
:global(.t03-activity-dialog .el-dialog__body){max-height:calc(90vh - 128px);overflow:auto;overscroll-behavior:contain}

.activity-tabs{padding:0 24px}.setting-help{display:block;width:100%;color:#859076;line-height:1.7}.recipient-results{list-style:none;padding:0;max-height:240px;overflow:auto}.recipient-results li{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:8px;border-bottom:1px solid #eef1ea}.recipient-results li span{overflow-wrap:anywhere;min-width:0}.recipient-selected{max-height:200px;overflow:auto;margin:14px 0}.recipient-selected .el-tag{margin:4px;max-width:100%;height:auto;white-space:normal;overflow-wrap:anywhere}
.activity-admin{--el-color-primary:#73a43b;background:#fff;border:1px solid #e7ece1;border-radius:16px;overflow:hidden}.activity-admin-hero{padding:30px;display:flex;align-items:center;justify-content:space-between;gap:20px;background:linear-gradient(120deg,#f0f5e7,#fafcf6)}.activity-admin-hero span{font-size:10px;letter-spacing:2px;color:#819166}.activity-admin-hero h2{font-size:23px;color:#35442b;margin:12px 0}.activity-admin-hero p{font-size:12px;color:#7e896f;margin:0}.activity-admin-note{font-size:12px;color:#859076;padding:16px 24px;border-bottom:1px solid #eef1ea}.row-meta{display:block;color:#969e8d;font-size:11px;margin-top:6px}.el-pagination{padding:20px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:0 18px}.form-grid :deep(.el-input-number),.form-grid :deep(.el-select),.form-grid :deep(.el-date-editor){width:100%}.activity-stat-grid{display:grid;grid-template-columns:repeat(6,1fr);gap:12px;margin-bottom:20px}.activity-stat-grid>div{background:#f5f8ef;border:1px solid #e7ecdF;padding:16px;border-radius:10px}.activity-stat-grid strong{display:block;font-size:26px;color:#557532}.activity-stat-grid span{font-size:11px;color:#89977a}.recipient-filters{display:flex;gap:12px;margin-bottom:18px}.recipient-filters>.el-select{width:220px}@media(max-width:850px){.form-grid{grid-template-columns:1fr}.activity-stat-grid{grid-template-columns:repeat(3,1fr)}.activity-admin-hero{padding:20px}.activity-admin-hero h2{font-size:18px}}
</style>
