<script setup lang="ts">
import { ref, computed, onMounted, watch, onBeforeUnmount, defineAsyncComponent } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { useAccountTable } from '@/utils/useAccountTable'
import { accountTableRequest } from '@/utils/accountTableRequest'
import AccountTypeFilter from '@/components/AccountTypeFilter.vue'
const ActivityTemplateEditor=defineAsyncComponent(()=>import('./ActivityTemplateEditor.vue'))
const designerOpen=ref(false), previewStage=ref('gift')
const ActivityDesignView=defineAsyncComponent(()=>import('../../../exchange-frontend/src/components/ActivityDesignView.vue'))
const accountTable = useAccountTable(), accountModes = accountTable.modes
const recipientTable = useAccountTable(), recipientModes = recipientTable.modes
const ledgerTable = useAccountTable(), ledgerModes = ledgerTable.modes
const request = accountTableRequest(accountTable)
import { can } from '@/utils/access'
const list=ref<any[]>([]), page=ref(1), total=ref(0), loading=ref(false), saving=ref(false), editor=ref(false), form=ref<any>({}), language=ref('zh-CN'), translations=ref<Record<string,any>>({})
const section=ref('activities'), sourceTemplate=ref(false), autoOpen=ref(false), autoForm=ref<any>({}), autoSaving=ref(false)
const sendOpen=ref(false), selected=ref<any>(), chosen=ref<{id:number,email:string}[]>([]), sending=ref(false), sendResult=ref<any>(null)
const reportOpen=ref(false), stats=ref<any>({}), recipients=ref<any[]>([]), recipientPage=ref(1), recipientTotal=ref(0), filter=ref('ALL'), userFilter=ref(''), reportBusy=ref(false), ledgerOpen=ref(false), ledger=ref<any[]>([]), account=ref<any>({})
const languages=['zh-CN','zh-TW','en','ja','ko','fr','de','ru','es','pt','it','ar','tr','id','my','hi','cs','pl','th','vi']
const labels:Record<string,string>={DRAFT:'草稿',ACTIVE:'启用',PAUSED:'暂停',CLOSED:'关闭'}
const defaultCopy=()=>({title:'一份心意，开启更多可能',body:'为回馈新老客户，最近 {days} 天登录的客户可领取 {amount} U 体验金。点击下方按钮领取，体验金将自动存入您的专属账户。',terms:'体验金仅可用于交易，不可提现。交易净收益归入正式交易账户，体验金本金留在体验金账户。',open:'打开礼遇',close:'关闭',claim:'领取 {amount} U 体验金',success:'体验金已到账'})
const english=()=>({title:'A little extra for your next opportunity',body:'Thank you for trading with us. Customers who logged in within the last {days} days can claim {amount} U in trial credit.',terms:'Trial principal is for trading only and cannot be withdrawn. Net profits go to your real trading account.',open:'Open gift',close:'Close',claim:'Claim {amount} U',success:'Your trial credit has arrived'})
const activeCopy=computed(()=>translations.value[language.value] || {})
const preview=(key:string)=>String(activeCopy.value[key]||'').split('{amount}').join(String(form.value.amount||0)).split('{days}').join(String(form.value.recentLoginDays||0))
const date=(value:string)=>value?new Date(value+'Z').toLocaleString():'—'
let loadVersion=0
async function load(){const version=++loadVersion;list.value=[];total.value=0;loading.value=true;try{const r:any=await request.get('/admin/activities',{params:{page:page.value-1,template:section.value==='templates'}});if(version===loadVersion){list.value=r.content;total.value=r.totalElements}}catch(e:any){if(version===loadVersion)ElMessage.error(e.message)}finally{if(version===loadVersion)loading.value=false}}
function edit(row?:any, clone=false){
 accountTable.selectRow(row || {})
 sourceTemplate.value=!!row?.template
 form.value=row?JSON.parse(JSON.stringify(row)):{name:'新老客户 · 300 U 体验金',amount:300,recentLoginDays:3,maxClaims:1000,budget:300000,status:'DRAFT',template:section.value==='templates',autoSendEnabled:false,repeatUnread:false,autoPopup:true,animation:'GIFT',defaultLocale:'zh-CN',startsAt:null,endsAt:null}
 if(clone){delete form.value.id;form.value.name+=' · 副本';form.value.status='DRAFT';form.value.template=false;form.value.autoSendEnabled=false;sourceTemplate.value=false;form.value.claimCount=0;form.value.granted=0}
 try{translations.value=row?JSON.parse(row.translations):{'zh-CN':defaultCopy(),en:english()}}catch{translations.value={'zh-CN':defaultCopy(),en:english()}}
 language.value=form.value.defaultLocale;editor.value=true
}
function addLanguage(code:string){if(!translations.value[code])translations.value[code]=code==='zh-CN'?defaultCopy():english();language.value=code}
async function save(asTemplate=form.value.template){
 if(!form.value.name?.trim()||!translations.value[form.value.defaultLocale]){ElMessage.warning('请填写名称和默认语言');return}
 saving.value=true
 try{const payload={...form.value,template:asTemplate,translations:JSON.stringify(translations.value)};if(!payload.id)payload.budget=Math.max(Number(payload.budget),Number(payload.amount));if(asTemplate!==sourceTemplate.value && payload.id){delete payload.id;payload.status='DRAFT';payload.autoSendEnabled=false}if(asTemplate){payload.status='DRAFT';payload.autoSendEnabled=false}const r:any=await (payload.id?request.put(`/admin/activities/${payload.id}`,payload):request.post('/admin/activities',payload));form.value=r;editor.value=false;ElMessage.success(asTemplate?'模板已保存':'活动已保存');section.value=asTemplate?'templates':'activities';page.value=1;await load()}catch(e:any){ElMessage.error(e.message)}finally{saving.value=false}
}
async function status(row:any,value:string){
 accountTable.selectRow(row)
 try{await ElMessageBox.confirm(`确定${labels[value]}“${row.name}”？暂停/关闭只停止领取，不追缴已领取本金。`,'活动状态');await request.put(`/admin/activities/${row.id}`,{...row,status:value});await load()}catch(e:any){if(e?.message)ElMessage.error(e.message)}
}
function prepareSend(row:any){accountTable.selectRow(row);selected.value=row;chosen.value=[];recipientQuery.value='';matches.value=[];sendResult.value=null;sendOpen.value=true}
const targetIds=computed(()=>chosen.value.map(user=>user.id))
const recipientQuery=ref(''), matches=ref<{id:number,email:string}[]>([]), searching=ref(false), searchError=ref('')
let searchTimer: ReturnType<typeof setTimeout> | undefined, searchVersion=0
watch(recipientQuery,value=>{
 clearTimeout(searchTimer);const version=++searchVersion, query=value.trim();matches.value=[];searchError.value='';searching.value=!!query
 if(!query)return
 searchTimer=setTimeout(async()=>{try{const data:any=await request.get('/admin/activities/recipients/search',{params:{query}});if(version===searchVersion)matches.value=data}catch(e:any){if(version===searchVersion)searchError.value=e.message||'搜索失败'}finally{if(version===searchVersion)searching.value=false}},300)
},{flush:'sync'})
watch(sendOpen,open=>{if(!open){clearTimeout(searchTimer);++searchVersion;searching.value=false}})
onBeforeUnmount(()=>{clearTimeout(searchTimer);++searchVersion})
function addRecipient(user:{id:number,email:string}){if(sending.value||chosen.value.some(x=>x.id===user.id))return;if(chosen.value.length>=1000){ElMessage.warning('每批最多1000人');return}chosen.value.push(user)}
function removeRecipient(id:number){if(!sending.value)chosen.value=chosen.value.filter(x=>x.id!==id)}
function configureAuto(row:any){accountTable.selectRow(row);autoForm.value=JSON.parse(JSON.stringify(row));autoOpen.value=true}
async function saveAuto(){autoSaving.value=true;try{await request.put(`/admin/activities/${autoForm.value.id}/auto-send`,autoForm.value);autoOpen.value=false;ElMessage.success('自动发送设置已保存');await load()}catch(e:any){ElMessage.error(e.message)}finally{autoSaving.value=false}}
async function removeActivity(row:any){accountTable.selectRow(row);try{await ElMessageBox.confirm(`删除“${row.name}”？将停止发送和领取，已发放体验金及历史流水保留。`,'删除活动',{type:'warning',confirmButtonText:'删除',cancelButtonText:'取消'});await request.delete(`/admin/activities/${row.id}`);if(list.value.length===1&&page.value>1)page.value--;await load();ElMessage.success('活动已删除')}catch(e:any){if(e?.message)ElMessage.error(e.message)}}
async function send(){
 if(!targetIds.value.length||targetIds.value.length>1000||targetIds.value.some(x=>!Number.isSafeInteger(x)||x<=0)){ElMessage.warning('请选择1至1000位用户');return}
 sending.value=true
 try{await ElMessageBox.confirm(`向 ${targetIds.value.length} 位指定用户发送活动公告？每人可领取 ${selected.value.amount} U，实际领取仍受资格、期限和预算限制。`,'确认批量发送');sendResult.value=await request.post(`/admin/activities/${selected.value.id}/send`,targetIds.value);ElMessage.success('投递已完成')}catch(e:any){if(e?.message)ElMessage.error(e.message)}finally{sending.value=false}
}
async function report(row?:any){if(row){recipientModes.value=[row.accountMode||"REAL"];selected.value=row;recipientPage.value=1;filter.value='ALL';userFilter.value='';reportOpen.value=true}recipients.value=[];stats.value={};reportBusy.value=true;try{const [s,r]:any=await Promise.all([recipientTable.counters(`/admin/activities/${selected.value.id}/stats`),recipientTable.fixedQuery(`/admin/activities/${selected.value.id}/recipients`,{page:recipientPage.value-1,state:filter.value,userId:userFilter.value||undefined},50)]);stats.value=s;recipients.value=r.content;recipientTotal.value=r.totalElements}catch(e:any){ElMessage.error(e.message)}finally{reportBusy.value=false}}
async function showLedger(userId:number, mode?:any){if(mode)ledgerModes.value=[mode];ledger.value=[];try{const [a,r]:any=await Promise.all([ledgerTable.counters(`/admin/activities/users/${userId}/account`),ledgerTable.fixedQuery(`/admin/activities/users/${userId}/ledger`,{},50)]);account.value={...a,userId};ledger.value=r.content;ledgerOpen.value=true}catch(e:any){ElMessage.error(e.message)}}
onMounted(load)
</script>
<template>
 <section class="activity-admin">
  <header class="activity-admin-hero"><div><span>CAMPAIGNS & TRIAL CREDIT</span><h2>把一份礼遇，送到合适的人手中。</h2><p>定向投递 · 多语言公告 · 独立本金账户 · 领取与互动追踪</p></div><el-button v-permission="'announcement:create'" v-if="can('announcement:create')" type="primary" size="large" @click="edit()" :disabled="accountModes.includes('DEMO') || !accountModes.length">＋ 新建{{section==='templates'?'模板':'活动'}}</el-button></header>
  <div class="activity-admin-note">体验金与可提现资产隔离。新活动默认草稿，保存不等于发送；每个用户每个活动仅领取一次。</div>
  <el-tabs v-model="section" class="activity-tabs" @tab-change="page=1;load()"><el-tab-pane label="活动列表" name="activities"/><el-tab-pane label="模板" name="templates"/></el-tabs>
  <AccountTypeFilter v-model="accountModes" @change="page=1;load()" /><admin-table :row-key="(row: any) => `${row.accountMode || 'REAL'}:${row.id ?? row.userId}:${row.type || ''}`" table-key="ActivityManagement.1" :data="list" v-loading="loading" stripe><el-table-column prop="accountModeLabel" label="账户类型" width="110" />
   <el-table-column prop="id" label="ID" width="65"/><el-table-column prop="name" :label="section==='templates'?'模板名称':'活动名称'" min-width="230"><template #default="{row}"><strong>{{row.name}}</strong><el-tag v-if="row.template" size="small" style="margin-left:8px">模板</el-tag><small class="row-meta">{{row.defaultLocale}} · {{row.autoPopup?'自动弹出':'仅站内信'}} · {{row.animation}}</small></template></el-table-column>
   <el-table-column label="体验金" width="120"><template #default="{row}">{{Number(row.amount).toLocaleString()}} U</template></el-table-column>
   <el-table-column label="已领取 / 名额" width="145"><template #default="{row}">{{row.claimCount}} / {{row.maxClaims}}</template></el-table-column>
   <el-table-column label="已发 / 预算 (U)" width="165"><template #default="{row}">{{Number(row.granted).toLocaleString()}} / {{Number(row.budget).toLocaleString()}}</template></el-table-column>
   <el-table-column v-if="section==='activities'" label="自动发送" width="110"><template #default="{row}"><el-tag :type="row.autoSendEnabled?'success':'info'">{{row.autoSendEnabled?'已开启':'已关闭'}}</el-tag></template></el-table-column>
   <el-table-column v-if="section==='activities'" label="状态" width="90"><template #default="{row}"><el-tag :type="row.status==='ACTIVE'?'success':row.status==='CLOSED'?'info':'warning'">{{labels[row.status]}}</el-tag></template></el-table-column>
   <el-table-column label="截止时间" width="180"><template #default="{row}">{{date(row.endsAt)}}</template></el-table-column>
   <el-table-column label="操作" :width="section==='templates'?100:450" fixed="right"><template #default="{row}"><el-button v-permission="'announcement:edit'" v-if="can('announcement:edit')" link type="primary" @click="edit(row)" :disabled="accountModes.includes('DEMO') || !accountModes.length">编辑</el-button><template v-if="!row.template"><el-button v-permission="'announcement:create'" v-if="can('announcement:create')" link type="primary" @click="edit(row,true)" :disabled="accountModes.includes('DEMO') || !accountModes.length">复制</el-button><el-button v-permission="'announcement:edit'" v-if="can('announcement:edit')" link type="primary" :disabled="accountModes.includes('DEMO') || !accountModes.length || (row.template||row.status!=='ACTIVE')" @click="prepareSend(row)">发送</el-button><el-button v-permission="'announcement:detail'" v-if="can('announcement:detail')" link type="primary" @click="report(row)">回执</el-button><el-button v-permission="'announcement:edit'" v-if="can('announcement:edit')" link @click="status(row,row.status==='ACTIVE'?'PAUSED':'ACTIVE')" :disabled="accountModes.includes('DEMO') || !accountModes.length">{{row.status==='ACTIVE'?'暂停':'启用'}}</el-button><el-button v-permission="'announcement:edit'" v-if="can('announcement:edit')" link type="danger" :disabled="accountModes.includes('DEMO') || !accountModes.length || (row.status==='CLOSED')" @click="status(row,'CLOSED')">关闭</el-button><el-button v-permission="'announcement:edit'" v-if="can('announcement:edit')" link type="primary" :disabled="accountModes.includes('DEMO') || !accountModes.length" @click="configureAuto(row)">自动发送设置</el-button><el-button v-permission="'announcement:delete'" v-if="can('announcement:delete')" link type="danger" :disabled="accountModes.includes('DEMO') || !accountModes.length" @click="removeActivity(row)">删除</el-button></template></template></el-table-column>
  </admin-table><el-pagination v-model:current-page="page" :page-size="50" :total="total" layout="total, prev, pager, next" @current-change="load"/>
  <el-dialog append-to-body v-model="editor" :title="form.template?'编辑模板':form.id?'编辑活动公告':'新建活动公告'" width="min(1120px,96vw)" :close-on-click-modal="false">
   <div class="activity-editor-layout"><el-form label-position="top" class="activity-form">
    <el-form-item label="后台活动名称" required><el-input v-model="form.name" maxlength="120"/></el-form-item>
    <div class="form-grid"><el-form-item v-if="!form.template" label="活动状态"><el-select v-model="form.status"><el-option v-for="(label,key) in labels" :key="key" :label="label" :value="key"/></el-select></el-form-item><el-form-item label="每人体验金 (U)" required><el-input-number v-model="form.amount" :min="0.01" :max="1000000" :precision="2"/></el-form-item></div>
    <el-form-item label="未读重复发送"><el-switch v-permission="'announcement:edit'" v-model="form.repeatUnread"/><small class="setting-help">未打开公告就关闭时，下次进入页面仍会弹出；已读或已领取不重复，不重复发放体验金。</small></el-form-item>
    <div class="form-grid"><el-form-item label="进入页面自动弹出"><el-switch v-permission="form.id ? 'announcement:edit' : 'announcement:create'" v-model="form.autoPopup"/></el-form-item><el-form-item label="动画风格"><el-select v-model="form.animation"><el-option label="礼盒开启 + 彩带" value="GIFT"/><el-option label="金色礼遇 + 彩带" value="CONFETTI"/><el-option label="静态展示" value="NONE"/></el-select></el-form-item></div>
    <el-divider content-position="left">自由设计</el-divider><el-alert :closable="false" type="info" title="可视化设计按语言保存首屏、详情及领取成功页；文字、图片、GIF、背景和图文比例均可编辑。旧文案用于初始化设计及站内信摘要。"/><el-button v-permission="'announcement:edit'" type="primary" style="margin:12px 0" @click="designerOpen=true">打开可视化模板编辑器</el-button><el-tag v-if="form.layoutJson">已使用自由设计</el-tag>
    <el-divider content-position="left">多语言文案 · 支持 {amount} / {days} 参数</el-divider>
    <div class="form-grid"><el-form-item label="编辑语言"><el-select :model-value="language" @change="addLanguage"><el-option v-for="code in languages" :key="code" :label="code+(translations[code]?' · 已配置':' · 新增')" :value="code"/></el-select></el-form-item><el-form-item label="未配置语言的回退语言"><el-select v-model="form.defaultLocale"><el-option v-for="(_,code) in translations" :key="code" :label="String(code)" :value="code"/></el-select></el-form-item></div>
    <template v-if="translations[language]"><el-form-item label="客户看到的标题" required><el-input v-model="translations[language].title" maxlength="160"/></el-form-item><el-form-item label="活动正文" required><el-input v-model="translations[language].body" type="textarea" :rows="4" maxlength="10000"/></el-form-item><el-form-item label="细则小字" required><el-input v-model="translations[language].terms" type="textarea" :rows="3" maxlength="10000"/></el-form-item><div class="form-grid"><el-form-item v-for="(label,key) in {open:'打开按钮',close:'关闭按钮',claim:'领取按钮',success:'领取成功提示'}" :key="key" :label="label"><el-input v-model="translations[language][key]" maxlength="200"/></el-form-item></div><el-button v-permission="form.id ? 'announcement:edit' : 'announcement:create'" v-if="language!==form.defaultLocale" link type="danger" @click="delete translations[language];language=form.defaultLocale">移除此语言（客户将使用回退语言）</el-button></template>
   </el-form><aside class="activity-preview-wrap"><small>客户视角预览 · {{language}}</small><template v-if="form.layoutJson"><el-radio-group v-model="previewStage"><el-radio-button value="gift">首屏</el-radio-button><el-radio-button value="detail">详情</el-radio-button><el-radio-button value="success">成功</el-radio-button></el-radio-group><ActivityDesignView :design="form.layoutJson" :locale="language" :fallback="form.defaultLocale" :stage="previewStage" :amount="form.amount" :days="form.recentLoginDays" :eligible="true" @action="action=>{if(action==='claim')previewStage='success';if(action==='close')previewStage='gift'}"/></template><div v-else class="activity-preview"><div class="preview-reward"><span>EXCLUSIVE REWARD</span><div class="preview-gift">✦</div><strong>{{Number(form.amount||0).toLocaleString()}}<small> U</small></strong><p>领取后自动入账，无需充值</p></div><div class="preview-body"><h3>{{preview('title')}}</h3><p>{{preview('body')}}</p><div>{{preview('terms')}}</div><button v-permission="'session:self'" type="button">{{preview('claim')||'立即领取'}}</button></div></div><p class="preview-note">文本安全渲染，不支持 HTML / JavaScript。体验金本金不可提现或划转；实名规则不可被文案配置覆盖。</p></aside></div>
   <template #footer><el-button v-permission="'session:close'" @click="editor=false">取消</el-button><el-button v-if="can('announcement:create')" v-permission="'announcement:create'" :loading="saving" @click="save(!form.template)">{{form.template?'保存为活动':'另存为模板'}}</el-button><el-button v-permission="form.id ? 'announcement:edit' : 'announcement:create'" type="primary" :loading="saving" @click="save(form.template)">{{form.template?'继续保存模板':'保存活动'}}</el-button></template>
  </el-dialog>
  <el-dialog v-model="designerOpen" append-to-body fullscreen destroy-on-close :show-close="false" :close-on-press-escape="false"><ActivityTemplateEditor v-if="designerOpen" :value="form.layoutJson" :locale="language" :fallback="form.defaultLocale" :fallback-copy="translations[form.defaultLocale]" :copy="activeCopy" @save="value=>{form.layoutJson=value;designerOpen=false}" @cancel="designerOpen=false"/></el-dialog>
  <el-dialog append-to-body v-model="autoOpen" title="自动发送设置" width="min(640px,96vw)" :close-on-click-modal="false">
   <el-alert type="info" :closable="false" title="开启后，系统每分钟向符合规则的用户自动投递，每个活动每批最多500人；进入页面时也会补发，每人仅投递一次。活动须启用；登录天数、期限、名额及预算也约束定向发送或领取。"/>
   <el-form label-position="top" style="margin-top:18px" :disabled="autoSaving">
    <el-form-item label="开启自动发送"><el-switch v-permission="'announcement:edit'" v-model="autoForm.autoSendEnabled" active-text="开启" inactive-text="关闭"/></el-form-item>
    <div class="form-grid"><el-form-item label="最近登录天数（0 表示不限）"><el-input-number v-model="autoForm.recentLoginDays" :min="0" :max="365" :precision="0"/></el-form-item><el-form-item label="最多领取人数"><el-input-number v-model="autoForm.maxClaims" :min="Math.max(1,autoForm.claimCount||0)" :max="1000000" :precision="0"/></el-form-item><el-form-item label="发放总预算 (U)"><el-input-number v-model="autoForm.budget" :min="Math.max(Number(autoForm.amount||0),Number(autoForm.granted||0))" :max="1000000000" :precision="2"/></el-form-item></div>
    <div class="form-grid"><el-form-item label="开始时间（UTC，可留空）"><el-date-picker v-model="autoForm.startsAt" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss" placeholder="立即生效"/></el-form-item><el-form-item label="结束时间（UTC，可留空）"><el-date-picker v-model="autoForm.endsAt" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss" placeholder="不限期限"/></el-form-item></div>
   </el-form><template #footer><el-button v-permission="'announcement:edit'" @click="autoOpen=false">取消</el-button><el-button v-permission="'announcement:edit'" type="primary" :loading="autoSaving" @click="saveAuto">保存设置</el-button></template>
  </el-dialog>
  <el-dialog append-to-body v-model="sendOpen" :close-on-click-modal="!sending" :close-on-press-escape="!sending" :show-close="!sending" title="定向批量发送" width="min(640px,96vw)"><p>{{selected?.name}} · 每人 {{selected?.amount}} U</p><el-alert type="info" :closable="false" title="仅向指定且符合资格的用户投递。重复发送不会重复创建消息或发放本金。"/>
   <el-input v-model="recipientQuery" clearable maxlength="128" aria-label="搜索用户 ID 或邮箱" placeholder="输入用户 ID 或邮箱实时搜索" style="margin-top:18px" :disabled="sending"/>
   <p role="status" aria-live="polite">{{searching?'搜索中…':searchError||(recipientQuery.trim()&&!matches.length?'未找到匹配用户':'最多显示20位，请输入完整 ID 或邮箱缩小范围')}}</p>
   <ul class="recipient-results"><li v-for="user in matches" :key="user.id"><span>ID {{user.id}} · {{user.email || '未设置邮箱'}}</span><el-button v-permission="'announcement:edit'" :aria-label="`添加用户 ${user.id}`" :disabled="sending||chosen.length>=1000||targetIds.includes(user.id)" @click="addRecipient(user)">{{targetIds.includes(user.id)?'已添加':'添加'}}</el-button></li></ul>
   <div class="recipient-selected"><p>已选择 {{chosen.length}} / 1000 位用户</p><el-tag v-for="user in chosen" :key="user.id" :closable="!sending" @close="removeRecipient(user.id)">ID {{user.id}} · {{user.email}}</el-tag></div>
   <el-alert v-if="sendResult" type="success" :closable="false" :title="`新增发送 ${sendResult.sent}，已发送跳过 ${sendResult.duplicates}，资格不符 ${sendResult.ineligible}`"/><template #footer><el-button v-permission="'session:close'" :disabled="sending" @click="sendOpen=false">关闭</el-button><el-button v-permission="'announcement:edit'" type="primary" :loading="sending" @click="send" :disabled="!chosen.length||accountModes.includes('DEMO') || !accountModes.length">确认发送</el-button></template></el-dialog>
  <el-dialog v-model="reportOpen" :title="'投递与领取追踪 · '+(selected?.name||'')" width="min(1200px,96vw)"><div class="activity-stat-grid"><div v-for="(label,key) in {sent:'已发送',received:'已收到',opened:'已打开',closed:'已关闭',closedWithoutOpening:'未打开即关闭',claimed:'已领取'}" :key="key"><strong>{{stats[key]||0}}</strong><span>{{label}}</span></div></div><div class="recipient-filters"><el-select v-model="filter" @change="recipientPage=1;report()"><el-option v-for="(label,key) in {ALL:'全部',SENT:'发送但未收到',RECEIVED:'已收到',OPENED:'已打开',CLOSED:'已关闭',CLOSED_UNOPENED:'收到后未打开即关闭',CLAIMED:'已领取'}" :key="key" :value="key" :label="label"/></el-select><el-input v-model="userFilter" placeholder="用户ID" clearable style="width:180px" @change="recipientPage=1;report()"/><el-button v-permission="'announcement:detail'" :loading="reportBusy" @click="report()">刷新</el-button></div><AccountTypeFilter v-model="recipientModes" @change="recipientPage=1;report()" /><admin-table :row-key="(row: any) => `${row.accountMode || 'REAL'}:${row.id ?? row.userId}:${row.type || ''}`" table-key="ActivityManagement.2" :data="recipients" v-loading="reportBusy"><el-table-column prop="accountModeLabel" label="账户类型" width="110" /><el-table-column prop="userId" label="用户ID" width="105"/><el-table-column v-for="(label,key) in {sentAt:'发送时间',receivedAt:'收到时间',openedAt:'首次打开',closedAt:'最后关闭',claimedAt:'领取时间'}" :key="key" :label="label" min-width="155"><template #default="{row}">{{date(row[key])}}</template></el-table-column><el-table-column label="打开/关闭" width="100"><template #default="{row}">{{row.openCount}} / {{row.closeCount}}</template></el-table-column><el-table-column label="账户" width="80"><template #default="{row}"><el-button v-permission="'announcement:detail'" link type="primary" @click="showLedger(row.userId,row.accountMode)">流水</el-button></template></el-table-column></admin-table><el-pagination v-model:current-page="recipientPage" :page-size="50" :total="recipientTotal" layout="total,prev,pager,next" @current-change="report()"/></el-dialog>
  <el-dialog v-model="ledgerOpen" title="体验金账户与最近50笔流水" width="min(900px,95vw)"><p>用户 {{account.userId}} · 可用 {{Number(account.available)}} U · 占用 {{Number(account.frozen)}} U · 累计消耗 {{Number(account.consumed)}} U · 净收益 {{Number(account.profits)}} U</p><AccountTypeFilter v-model="ledgerModes" @change="showLedger(account.userId)" /><admin-table :row-key="(row: any) => `${row.accountMode || 'REAL'}:${row.id ?? row.userId}:${row.type || ''}`" table-key="ActivityManagement.3" :data="ledger"><el-table-column prop="accountModeLabel" label="账户类型" width="110" /><el-table-column prop="reason" label="业务原因" min-width="200"/><el-table-column prop="delta" label="本金变化"/><el-table-column prop="available" label="可用"/><el-table-column prop="frozen" label="冻结"/><el-table-column label="时间" width="180"><template #default="{row}">{{date(row.createdAt)}}</template></el-table-column></admin-table></el-dialog>
 </section>
</template>
<style scoped>
.activity-tabs{padding:0 24px}.setting-help{display:block;width:100%;color:#859076;line-height:1.7}.recipient-results{list-style:none;padding:0;max-height:240px;overflow:auto}.recipient-results li{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:8px;border-bottom:1px solid #eef1ea}.recipient-results li span{overflow-wrap:anywhere;min-width:0}.recipient-selected{max-height:200px;overflow:auto;margin:14px 0}.recipient-selected .el-tag{margin:4px;max-width:100%;height:auto;white-space:normal;overflow-wrap:anywhere}
.activity-admin{--el-color-primary:#73a43b;background:#fff;border:1px solid #e7ece1;border-radius:16px;overflow:hidden}.activity-admin-hero{padding:30px;display:flex;align-items:center;justify-content:space-between;gap:20px;background:linear-gradient(120deg,#f0f5e7,#fafcf6)}.activity-admin-hero span{font-size:10px;letter-spacing:2px;color:#819166}.activity-admin-hero h2{font-size:23px;color:#35442b;margin:12px 0}.activity-admin-hero p{font-size:12px;color:#7e896f;margin:0}.activity-admin-note{font-size:12px;color:#859076;padding:16px 24px;border-bottom:1px solid #eef1ea}.row-meta{display:block;color:#969e8d;font-size:11px;margin-top:6px}.el-pagination{padding:20px}.activity-editor-layout{display:grid;grid-template-columns:minmax(0,1fr) 330px;gap:34px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:0 18px}.form-grid :deep(.el-input-number),.form-grid :deep(.el-select),.form-grid :deep(.el-date-editor){width:100%}.activity-form{max-height:68vh;overflow-y:auto;padding-right:10px}.activity-preview-wrap>small{display:block;text-align:center;color:#899378;letter-spacing:1px;margin-bottom:15px}.activity-preview{border:1px solid #e1e8d8;border-radius:20px;overflow:hidden;box-shadow:0 18px 45px #30411b12;background:white}.preview-reward{text-align:center;background:radial-gradient(ellipse,#fcffef,#e8f0df);padding:24px 20px}.preview-reward>span{font-size:9px;letter-spacing:2px;color:#8d9b75}.preview-gift{font-size:60px;color:#91b34f;line-height:1.5}.preview-reward strong{font-size:54px;font-weight:700;color:#405330;letter-spacing:-3px}.preview-reward strong small{font-size:18px;letter-spacing:0}.preview-reward p{font-size:10px;color:#8c9a78}.preview-body{padding:24px}.preview-body h3{font-size:20px;color:#3a4830;line-height:1.4;margin:0 0 12px}.preview-body p{font-size:12px;line-height:1.8;color:#849076;white-space:pre-wrap}.preview-body>div{padding:12px;background:#f7f9f2;font-size:10px;line-height:1.6;border-radius:8px;color:#97a085;white-space:pre-wrap}.preview-body button{margin-top:20px;width:100%;border:0;border-radius:9px;padding:13px;background:#73b100;color:#fff}.preview-note{font-size:11px;line-height:1.8;color:#98a18b;margin:18px 8px}.activity-stat-grid{display:grid;grid-template-columns:repeat(6,1fr);gap:12px;margin-bottom:20px}.activity-stat-grid>div{background:#f5f8ef;border:1px solid #e7ecdF;padding:16px;border-radius:10px}.activity-stat-grid strong{display:block;font-size:26px;color:#557532}.activity-stat-grid span{font-size:11px;color:#89977a}.recipient-filters{display:flex;gap:12px;margin-bottom:18px}.recipient-filters>.el-select{width:220px}@media(max-width:850px){.activity-editor-layout{grid-template-columns:1fr}.activity-preview-wrap{display:none}.activity-stat-grid{grid-template-columns:repeat(3,1fr)}.activity-admin-hero{padding:20px}.activity-admin-hero h2{font-size:18px}}
</style>
