-- Generated by scripts/multitenant/build_manifest.py. Review SQL and manifest together.
-- MySQL 5.7; no business writes may run while nullable tenant columns are backfilled.
-- Missing optional tables are reported by the runner; unknown tables are fail-closed.
DELIMITER $$
CREATE PROCEDURE mt_exec(IN statement_text LONGTEXT)
BEGIN
 SET @mt_statement=statement_text;
 PREPARE mt_statement FROM @mt_statement;
 EXECUTE mt_statement;
 DEALLOCATE PREPARE mt_statement;
END$$
CREATE PROCEDURE mt_scope(IN table_arg VARCHAR(64))
scope_body: BEGIN
 DECLARE finished INT DEFAULT 0;
 DECLARE index_arg VARCHAR(64);
 DECLARE columns_arg TEXT;
 DECLARE primary_columns TEXT;
 DECLARE key_column VARCHAR(64);
 DECLARE table_count INT;
 DECLARE unchanged_timestamps TEXT;
 DECLARE unique_indexes CURSOR FOR
  SELECT INDEX_NAME,GROUP_CONCAT(CONCAT('`',COLUMN_NAME,'`',IF(SUB_PART IS NULL,'',CONCAT('(',SUB_PART,')'))) ORDER BY SEQ_IN_INDEX SEPARATOR ',')
  FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=table_arg
   AND NON_UNIQUE=0 AND INDEX_NAME<>'PRIMARY'
  GROUP BY INDEX_NAME HAVING SUM(COLUMN_NAME='tenant_id')=0;
 DECLARE CONTINUE HANDLER FOR NOT FOUND SET finished=1;
 SELECT COUNT(*) INTO table_count FROM information_schema.TABLES
  WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=table_arg;
 IF table_count=0 THEN LEAVE scope_body; END IF;
 IF EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=table_arg AND COLUMN_NAME='tenant_id')
 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Partial migration or already scoped table: restore verified backup before retry'; END IF;
 CALL mt_exec(CONCAT('ALTER TABLE `',table_arg,'` ADD COLUMN tenant_id BIGINT NULL'));
 SELECT GROUP_CONCAT(CONCAT(',`',COLUMN_NAME,'`=`',COLUMN_NAME,'`') SEPARATOR '') INTO unchanged_timestamps
  FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=table_arg AND EXTRA LIKE '%on update%';
 CALL mt_exec(CONCAT('UPDATE `',table_arg,'` SET tenant_id=1',IFNULL(unchanged_timestamps,'')));
 CALL mt_exec(CONCAT('ALTER TABLE `',table_arg,'` MODIFY tenant_id BIGINT NOT NULL, ADD CONSTRAINT `mt_t_',table_arg,'` FOREIGN KEY(tenant_id) REFERENCES tenant(id)'));
 SELECT GROUP_CONCAT(CONCAT('`',COLUMN_NAME,'`') ORDER BY SEQ_IN_INDEX SEPARATOR ',') INTO primary_columns
  FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=table_arg AND INDEX_NAME='PRIMARY';
 -- Preserve all historical IDs. Natural primary keys need tenant scope, including task watermarks.
 IF primary_columns NOT IN ('`id`','`user_id`','`admin_id`','`message_id`','`event_sequence`') THEN
  CALL mt_exec(CONCAT('ALTER TABLE `',table_arg,'` DROP PRIMARY KEY, ADD PRIMARY KEY(tenant_id,',primary_columns,')'));
 ELSE
  CALL mt_exec(CONCAT('ALTER TABLE `',table_arg,'` ADD UNIQUE KEY mt_tenant_identity(tenant_id,',primary_columns,')'));
 END IF;
 OPEN unique_indexes;
 index_loop: LOOP
  FETCH unique_indexes INTO index_arg,columns_arg;
  IF finished=1 THEN LEAVE index_loop; END IF;
  -- External deposit order identity remains globally unique. Backend account namespace is global.
  IF NOT (table_arg='deposit_record' AND columns_arg='`order_no`')
   AND NOT (table_arg='admin_user' AND columns_arg='`account`') THEN
   -- Existing single-column FKs may use this unique index. Retain a nonunique lookup
   -- before changing uniqueness; composite tenant FKs are added below as the boundary.
   CALL mt_exec(CONCAT('ALTER TABLE `',table_arg,'` ADD INDEX `mt_old_',LEFT(SHA2(index_arg,256),16),'`(',columns_arg,')'));
   IF table_arg='user_account' AND columns_arg IN ('`email`','`phone`') THEN
    CALL mt_exec(CONCAT('ALTER TABLE `',table_arg,'` DROP INDEX `',index_arg,'`'));
   ELSE
    CALL mt_exec(CONCAT('ALTER TABLE `',table_arg,'` DROP INDEX `',index_arg,'`, ADD UNIQUE KEY `',index_arg,'`(tenant_id,',columns_arg,')'));
   END IF;
  END IF;
 END LOOP;
 CLOSE unique_indexes;
 IF EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=table_arg AND COLUMN_NAME='created_at') THEN
  CALL mt_exec(CONCAT('ALTER TABLE `',table_arg,'` ADD INDEX mt_tenant_created(tenant_id,created_at)'));
 END IF;
 IF EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=table_arg AND COLUMN_NAME='status') THEN
  CALL mt_exec(CONCAT('ALTER TABLE `',table_arg,'` ADD INDEX mt_tenant_status(tenant_id,status)'));
 END IF;
END$$
CREATE PROCEDURE mt_link(IN child_arg VARCHAR(64),IN field_arg VARCHAR(64),IN parent_arg VARCHAR(64),IN parent_field VARCHAR(64))
link_body: BEGIN
 DECLARE invalid_rows BIGINT;
 DECLARE key_name VARCHAR(64);
 DECLARE parent_charset VARCHAR(64);
 DECLARE parent_collation VARCHAR(64);
 DECLARE child_collation VARCHAR(64);
 DECLARE field_type VARCHAR(128);
 DECLARE nullable_field VARCHAR(3);
 IF NOT EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=child_arg AND COLUMN_NAME=field_arg)
  OR NOT EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=parent_arg AND COLUMN_NAME=parent_field)
 THEN LEAVE link_body; END IF;
 SELECT CHARACTER_SET_NAME,COLLATION_NAME,COLUMN_TYPE INTO parent_charset,parent_collation,field_type
  FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=parent_arg AND COLUMN_NAME=parent_field;
 SELECT COLLATION_NAME,IS_NULLABLE INTO child_collation,nullable_field
  FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=child_arg AND COLUMN_NAME=field_arg;
 IF parent_collation IS NOT NULL AND NOT (parent_collation <=> child_collation) THEN
  -- Legacy native tables are latin1 while newly-created tables may be utf8mb4.
  -- Only ASCII identity columns can be harmonized without changing historical bytes.
  CALL mt_exec(CONCAT('SELECT COUNT(*) INTO @mt_nonascii FROM `',child_arg,'` WHERE HEX(`',field_arg,'`)<>HEX(CONVERT(`',field_arg,'` USING ascii))'));
  IF @mt_nonascii>0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Non-ASCII FK identity requires reviewed collation migration'; END IF;
  CALL mt_exec(CONCAT('ALTER TABLE `',child_arg,'` MODIFY `',field_arg,'` ',field_type,' CHARACTER SET ',parent_charset,' COLLATE ',parent_collation,IF(nullable_field='YES',' NULL',' NOT NULL')));
 END IF;
 SET key_name=CONCAT('mt_fk_',LEFT(SHA2(CONCAT(child_arg,':',field_arg,':',parent_arg),256),20));
 -- FK creation itself rejects any orphan and any tenant mismatch; never disable FK checks.
 CALL mt_exec(CONCAT('ALTER TABLE `',child_arg,'` ADD CONSTRAINT `',key_name,'` FOREIGN KEY(tenant_id,`',field_arg,'`) REFERENCES `',parent_arg,'`(tenant_id,`',parent_field,'`) ON UPDATE RESTRICT ON DELETE RESTRICT'));
END$$
DELIMITER ;

CALL mt_scope('activity_campaign');
CALL mt_scope('activity_delivery');
CALL mt_scope('admin_role');
CALL mt_scope('admin_role_menu');
CALL mt_scope('admin_table_preference');
CALL mt_scope('admin_user');
CALL mt_scope('announcement');
CALL mt_scope('asset_account');
CALL mt_scope('asset_history_1d');
CALL mt_scope('asset_history_1h');
CALL mt_scope('asset_history_1m');
CALL mt_scope('asset_history_4h');
CALL mt_scope('asset_history_baseline');
CALL mt_scope('asset_history_job_state');
CALL mt_scope('asset_history_quote_batch');
CALL mt_scope('asset_history_revision');
CALL mt_scope('asset_snapshot');
CALL mt_scope('balance_adjustment');
CALL mt_scope('contract_order');
CALL mt_scope('demo_account');
CALL mt_scope('demo_ledger');
CALL mt_scope('demo_order');
CALL mt_scope('deposit_credit_record');
CALL mt_scope('deposit_record');
CALL mt_scope('deposit_setting');
CALL mt_scope('financial_order');
CALL mt_scope('financial_product');
CALL mt_scope('financial_yield_record');
CALL mt_scope('inbox_letter');
CALL mt_scope('kyc_record');
CALL mt_scope('loan_personal_info');
CALL mt_scope('loan_record');
CALL mt_scope('loan_setting');
CALL mt_scope('manual_order_record');
CALL mt_scope('market_control_flow');
CALL mt_scope('market_control_hold');
CALL mt_scope('market_control_plan');
CALL mt_scope('market_control_publication');
CALL mt_scope('market_control_resume');
CALL mt_scope('market_control_sample');
CALL mt_scope('market_control_task');
CALL mt_scope('market_legacy_minute_snapshot');
CALL mt_scope('market_mixed_minute');
CALL mt_scope('market_simulation_source_candle');
CALL mt_scope('market_source_candle');
CALL mt_scope('market_source_event');
CALL mt_scope('market_source_quote');
CALL mt_scope('market_source_tick');
CALL mt_scope('operation_log');
CALL mt_scope('option_duration');
CALL mt_scope('option_order');
CALL mt_scope('simulation_seed');
CALL mt_scope('support_attachment');
CALL mt_scope('support_conversation');
CALL mt_scope('support_message');
CALL mt_scope('support_presence');
CALL mt_scope('symbol_duration');
CALL mt_scope('system_config');
CALL mt_scope('t_ai_model');
CALL mt_scope('trading_symbol');
CALL mt_scope('transfer_record');
CALL mt_scope('trial_account');
CALL mt_scope('trial_ledger');
CALL mt_scope('user_account');
CALL mt_scope('user_action');
CALL mt_scope('user_bank_card');
CALL mt_scope('user_digital_address');
CALL mt_scope('user_menu');
CALL mt_scope('verify_code');
CALL mt_scope('withdraw_record');
CALL mt_link('activity_delivery','user_id','user_account','id');
CALL mt_link('asset_account','user_id','user_account','id');
CALL mt_link('asset_snapshot','user_id','user_account','id');
CALL mt_link('balance_adjustment','user_id','user_account','id');
CALL mt_link('contract_order','user_id','user_account','id');
CALL mt_link('deposit_credit_record','user_id','user_account','id');
CALL mt_link('deposit_record','user_id','user_account','id');
CALL mt_link('financial_order','user_id','user_account','id');
CALL mt_link('financial_yield_record','user_id','user_account','id');
CALL mt_link('kyc_record','user_id','user_account','id');
CALL mt_link('loan_personal_info','user_id','user_account','id');
CALL mt_link('loan_record','user_id','user_account','id');
CALL mt_link('option_order','user_id','user_account','id');
CALL mt_link('transfer_record','user_id','user_account','id');
CALL mt_link('user_action','user_id','user_account','id');
CALL mt_link('user_bank_card','user_id','user_account','id');
CALL mt_link('user_digital_address','user_id','user_account','id');
CALL mt_link('user_menu','user_id','user_account','id');
CALL mt_link('withdraw_record','user_id','user_account','id');
CALL mt_link('demo_account','user_id','user_account','id');
CALL mt_link('demo_order','user_id','user_account','id');
CALL mt_link('demo_ledger','user_id','user_account','id');
CALL mt_link('trial_account','user_id','user_account','id');
CALL mt_link('trial_ledger','user_id','user_account','id');
CALL mt_link('simulation_seed','user_id','user_account','id');
CALL mt_link('inbox_letter','user_id','user_account','id');
CALL mt_link('support_conversation','user_id','user_account','id');
CALL mt_link('asset_history_1m','user_id','user_account','id');
CALL mt_link('asset_history_1h','user_id','user_account','id');
CALL mt_link('asset_history_4h','user_id','user_account','id');
CALL mt_link('asset_history_1d','user_id','user_account','id');
CALL mt_link('asset_history_baseline','user_id','user_account','id');
CALL mt_link('asset_history_revision','user_id','user_account','id');
CALL mt_link('manual_order_record','user_id','user_account','id');
CALL mt_link('user_account','parent_user_id','user_account','id');
CALL mt_link('admin_user','role_id','admin_role','id');
CALL mt_link('admin_role_menu','role_id','admin_role','id');
CALL mt_link('financial_order','product_id','financial_product','id');
CALL mt_link('financial_yield_record','product_id','financial_product','id');
CALL mt_link('financial_yield_record','order_id','financial_order','id');
CALL mt_link('deposit_credit_record','deposit_record_id','deposit_record','id');
CALL mt_link('activity_delivery','campaign_id','activity_campaign','id');
CALL mt_link('support_conversation','active_user_id','user_account','id');
CALL mt_link('support_conversation','admin_id','admin_user','id');
CALL mt_link('support_message','conversation_id','support_conversation','id');
CALL mt_link('support_presence','admin_id','admin_user','id');
CALL mt_link('support_attachment','message_id','support_message','id');
CALL mt_link('inbox_letter','admin_id','admin_user','id');
CALL mt_link('backend_login','user_id','user_account','id');
CALL mt_link('backend_login','admin_user_id','admin_user','id');
CALL mt_link('demo_ledger','order_id','demo_order','id');
CALL mt_link('manual_order_record','order_id','contract_order','id');
CALL mt_link('market_control_flow','task_id','market_control_task','id');
CALL mt_link('market_control_hold','task_id','market_control_task','id');
CALL mt_link('market_control_plan','task_id','market_control_task','id');
CALL mt_link('market_control_publication','task_id','market_control_task','id');
CALL mt_link('market_control_resume','task_id','market_control_task','id');
CALL mt_link('market_control_sample','task_id','market_control_task','id');
CALL mt_link('market_control_task','symbol_id','trading_symbol','id');
CALL mt_link('market_legacy_minute_snapshot','symbol_id','trading_symbol','id');
CALL mt_link('market_mixed_minute','symbol_id','trading_symbol','id');
CALL mt_link('market_simulation_source_candle','symbol_id','trading_symbol','id');
CALL mt_link('market_source_candle','symbol_id','trading_symbol','id');
CALL mt_link('market_source_event','symbol_id','trading_symbol','id');
CALL mt_link('market_source_quote','symbol_id','trading_symbol','id');
CALL mt_link('market_source_tick','symbol_id','trading_symbol','id');
CALL mt_link('asset_history_1m','quote_batch_id','asset_history_quote_batch','batch_id');
DELIMITER $$
CREATE TRIGGER `mt_immutable_activity_campaign` BEFORE UPDATE ON `activity_campaign` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_activity_delivery` BEFORE UPDATE ON `activity_delivery` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_admin_role` BEFORE UPDATE ON `admin_role` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_admin_role_menu` BEFORE UPDATE ON `admin_role_menu` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_admin_table_preference` BEFORE UPDATE ON `admin_table_preference` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_admin_user` BEFORE UPDATE ON `admin_user` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_announcement` BEFORE UPDATE ON `announcement` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_asset_account` BEFORE UPDATE ON `asset_account` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_asset_history_1d` BEFORE UPDATE ON `asset_history_1d` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_asset_history_1h` BEFORE UPDATE ON `asset_history_1h` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_asset_history_1m` BEFORE UPDATE ON `asset_history_1m` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_asset_history_4h` BEFORE UPDATE ON `asset_history_4h` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_asset_history_baseline` BEFORE UPDATE ON `asset_history_baseline` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_asset_history_job_state` BEFORE UPDATE ON `asset_history_job_state` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_asset_history_quote_batch` BEFORE UPDATE ON `asset_history_quote_batch` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_asset_history_revision` BEFORE UPDATE ON `asset_history_revision` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_asset_snapshot` BEFORE UPDATE ON `asset_snapshot` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_balance_adjustment` BEFORE UPDATE ON `balance_adjustment` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_contract_order` BEFORE UPDATE ON `contract_order` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_demo_account` BEFORE UPDATE ON `demo_account` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_demo_ledger` BEFORE UPDATE ON `demo_ledger` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_demo_order` BEFORE UPDATE ON `demo_order` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_deposit_credit_record` BEFORE UPDATE ON `deposit_credit_record` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_deposit_record` BEFORE UPDATE ON `deposit_record` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_deposit_setting` BEFORE UPDATE ON `deposit_setting` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_financial_order` BEFORE UPDATE ON `financial_order` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_financial_product` BEFORE UPDATE ON `financial_product` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_financial_yield_record` BEFORE UPDATE ON `financial_yield_record` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_inbox_letter` BEFORE UPDATE ON `inbox_letter` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_kyc_record` BEFORE UPDATE ON `kyc_record` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_loan_personal_info` BEFORE UPDATE ON `loan_personal_info` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_loan_record` BEFORE UPDATE ON `loan_record` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_loan_setting` BEFORE UPDATE ON `loan_setting` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_manual_order_record` BEFORE UPDATE ON `manual_order_record` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_market_control_flow` BEFORE UPDATE ON `market_control_flow` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_market_control_hold` BEFORE UPDATE ON `market_control_hold` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_market_control_plan` BEFORE UPDATE ON `market_control_plan` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_market_control_publication` BEFORE UPDATE ON `market_control_publication` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_market_control_resume` BEFORE UPDATE ON `market_control_resume` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_market_control_sample` BEFORE UPDATE ON `market_control_sample` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_market_control_task` BEFORE UPDATE ON `market_control_task` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_market_legacy_minute_snapshot` BEFORE UPDATE ON `market_legacy_minute_snapshot` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_market_mixed_minute` BEFORE UPDATE ON `market_mixed_minute` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_market_simulation_source_candle` BEFORE UPDATE ON `market_simulation_source_candle` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_market_source_candle` BEFORE UPDATE ON `market_source_candle` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_market_source_event` BEFORE UPDATE ON `market_source_event` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_market_source_quote` BEFORE UPDATE ON `market_source_quote` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_market_source_tick` BEFORE UPDATE ON `market_source_tick` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_operation_log` BEFORE UPDATE ON `operation_log` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_option_duration` BEFORE UPDATE ON `option_duration` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_option_order` BEFORE UPDATE ON `option_order` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_simulation_seed` BEFORE UPDATE ON `simulation_seed` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_support_attachment` BEFORE UPDATE ON `support_attachment` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_support_conversation` BEFORE UPDATE ON `support_conversation` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_support_message` BEFORE UPDATE ON `support_message` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_support_presence` BEFORE UPDATE ON `support_presence` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_symbol_duration` BEFORE UPDATE ON `symbol_duration` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_system_config` BEFORE UPDATE ON `system_config` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_t_ai_model` BEFORE UPDATE ON `t_ai_model` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_trading_symbol` BEFORE UPDATE ON `trading_symbol` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_transfer_record` BEFORE UPDATE ON `transfer_record` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_trial_account` BEFORE UPDATE ON `trial_account` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_trial_ledger` BEFORE UPDATE ON `trial_ledger` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_user_account` BEFORE UPDATE ON `user_account` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_user_action` BEFORE UPDATE ON `user_action` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_user_bank_card` BEFORE UPDATE ON `user_bank_card` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_user_digital_address` BEFORE UPDATE ON `user_digital_address` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_user_menu` BEFORE UPDATE ON `user_menu` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_verify_code` BEFORE UPDATE ON `verify_code` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
CREATE TRIGGER `mt_immutable_withdraw_record` BEFORE UPDATE ON `withdraw_record` FOR EACH ROW BEGIN IF NEW.tenant_id<>OLD.tenant_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Tenant is immutable'; END IF; END$$
DELIMITER ;
ALTER TABLE user_account
 ADD COLUMN normalized_email VARCHAR(128) GENERATED ALWAYS AS (LOWER(TRIM(email))) STORED,
 ADD COLUMN normalized_phone VARCHAR(32) GENERATED ALWAYS AS (NULLIF(TRIM(phone),'')) STORED,
 ADD UNIQUE KEY uk_tenant_normalized_email(tenant_id,normalized_email),
 ADD UNIQUE KEY uk_tenant_normalized_phone(tenant_id,normalized_phone),
 ADD INDEX ix_tenant_online(tenant_id,last_activity_at,id);
ALTER TABLE user_account MODIFY id BIGINT NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7000001;
ALTER TABLE user_account ADD COLUMN last_page_code VARCHAR(32),
 ADD COLUMN last_page_seen_at DATETIME(6), ADD COLUMN last_page_sequence BIGINT,
 ADD COLUMN last_device_type VARCHAR(16);
ALTER TABLE support_conversation ADD COLUMN legal_hold BIT NOT NULL DEFAULT 0;
ALTER TABLE support_conversation ADD COLUMN control_actor_id BIGINT NULL,
 ADD CONSTRAINT mt_support_control_actor FOREIGN KEY(control_actor_id) REFERENCES control_admin(id);
ALTER TABLE inbox_letter MODIFY admin_id BIGINT NULL, ADD COLUMN control_actor_id BIGINT NULL,
 ADD UNIQUE KEY uk_inbox_control_request(tenant_id,control_actor_id,request_id,user_id),
 ADD CONSTRAINT mt_inbox_control_actor FOREIGN KEY(control_actor_id) REFERENCES control_admin(id);
ALTER TABLE admin_user ADD COLUMN must_change_password BIT NOT NULL DEFAULT 0;
INSERT INTO backend_login(normalized_account,tenant_id,subject_type,admin_user_id,enabled)
 SELECT LOWER(TRIM(account)),tenant_id,'ADMIN',id,enabled FROM admin_user;
INSERT INTO backend_login(normalized_account,tenant_id,subject_type,user_id,enabled)
 SELECT LOWER(TRIM(email)),tenant_id,'AGENT',id,IF(status='normal',1,0) FROM user_account WHERE user_type='agent';
-- Revoke pre-tenant sessions. The runner fingerprints history excluding only these known ephemeral fields.
UPDATE admin_user SET current_token=NULL,updated_at=updated_at;
UPDATE user_account SET current_token=NULL,updated_at=updated_at;
INSERT INTO tenant_policy(tenant_id,policy_key,policy_value,locked,version)
 VALUES(1,'retention.auto_delete_enabled','false',1,0),(1,'retention.keep_days','365',1,0);
INSERT INTO tenant_schema_version(version,applied_at,minimum_application_epoch,business_activation_ready)
 VALUES(2026092902,UTC_TIMESTAMP(6),2026092902,0);
DROP PROCEDURE mt_link;
DROP PROCEDURE mt_scope;
DROP PROCEDURE mt_exec;
